### ISSUE TITLE
TRLSubDetail PrintEmpty

### ISSUE THREAD

**Issue by natividade** [fortesinformatica/fortesreport-ce#1]
Olá!
Eu utilizava o FortesReport no Delphi 7 e agora migrei para o Delphi XE2.
Possuo alguns relatórios que utilizam as bandas de subdetail para que o usuário selecione que partes ele quer adicionar ao relatório.
No D7 isto funcionava bem com a propriedade printempty da subdetail, agora no XE2 isso não funciona mais.
Como faço para ter a mesma funcionalidade?
Grato.

**Comment by marciomartins** [comment]
Desculpe a demora estive afastado muito tempo do projeto por falta de tempo.
Estou retomando as atividades e pretendo assim como outros colaboradores que o FRCE recebe os ajustes e melhorias necessárias.
Se o problema persistir, favor me contactar por e-mail para que possamos providenciar o ajustes o mais rápido possível.
Mais uma vez desculpe a demora em responder.
