### ISSUE TITLE
Fortes Report para Delphi 2007

### ISSUE THREAD

**Issue by scalon** [fortesinformatica/fortesreport-ce#10]
Por Favor alguém tem o pacote do Frotes que funcione no Delphi 2007(RLibWinD2007vcl)??
Se sim onde posso baixar?
Como faço para instalar?
Desde já Muito Obrigado pela Atenção e Ajuda!!

**Comment by marciomartins** [comment]
Desculpe a demora, se o problema persistir na versão atual, favor reabrir o chamado ou me contactar por e-mail.
