### ISSUE TITLE
Problemas para instalar o Fortes Report no Delphi 2007

### ISSUE THREAD

**Issue by dennisstar07** [fortesinformatica/fortesreport-ce#100]
Boa noite. Instalei o Fortes Report CE conforme li no forum do ACBR e tive vários problemas, Vou adicionar o log de instalação para ver se alguém pode me dar uma luz nesse problema. Obrigado.

[log_Delphi_2007.txt](https://github.com/fortesinformatica/fortesreport-ce/files/191221/log_Delphi_2007.txt)

**Comment by juliomar** [comment]
O erro relatado pode ser algumas situações, executar como administrador, path muito longo, o local onde está o executável do instalador não ficou no raiz e assim ele não acha o dpk pra compilar.
se persiste o erro favor criar novo issue detalhando melhor
