### ISSUE TITLE
Problemas no RecordRange = rrCurrentOnly

### ISSUE THREAD

**Issue by HugoPSL** [fortesinformatica/fortesreport-ce#101]
Após imprimir relatório com RecordRange = rrCurrentOnly de um datasource com mais registros o ponteiro sempre retorna no próximo registro ao invés de ficar posicionado no mesmo.Se puderem ajustar isso seria legal pois evitaria controles adicionais de ponteiros.
Grato
Hugo

**Comment by juliomar** [comment]
Boa tarde
favor efetuar testes com mudanças subidas
se persistir favor reportar em novo issue
