### ISSUE TITLE
Erro ao usar o assistente de instalação do fortes

### ISSUE THREAD

**Issue by eraldocg** [fortesinformatica/fortesreport-ce#106]
Caminho: E:\SED_Desenvolvimento\FortesReport\XE8
Versão do delphi: Delphi XE8 (1)
# Plataforma: Win64(1) ou win32

Setando parâmetros de plataforma...
Criando diretórios de bibliotecas...
Adicionando library paths...

Compiling package frce.dpk
"C:\Program Files (x86)\Embarcadero\Studio\16.0\bin\dcc32.exe" "frce.dpk" --no-config -B -$O- -$W+ -$Y- -M -Q -H- -W- -DRELEASE -U"C:\Program Files (x86)\Embarcadero\Studio\16.0\lib\Win64\release" -U"c:\program files (x86)\embarcadero\studio\16.0\lib\Win64\release;E:\Documentos\Embarcadero\Studio\16.0\Imports;c:\program files (x86)\embarcadero\studio\16.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\16.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\16.0\include;C:\Program Files (x86)\Raize\CS5\Lib\RS-XE8\Win64;E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -U"E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -I"c:\program files (x86)\embarcadero\studio\16.0\lib\Win64\release;E:\Documentos\Embarcadero\Studio\16.0\Imports;c:\program files (x86)\embarcadero\studio\16.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\16.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\16.0\include;C:\Program Files (x86)\Raize\CS5\Lib\RS-XE8\Win64;E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -R"c:\program files (x86)\embarcadero\studio\16.0\lib\Win64\release;E:\Documentos\Embarcadero\Studio\16.0\Imports;c:\program files (x86)\embarcadero\studio\16.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\16.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\16.0\include;C:\Program Files (x86)\Raize\CS5\Lib\RS-XE8\Win64;E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -N0"E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -LE"E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -LN"E:\SED_Desenvolvimento\FortesReport\XE8\Binary\LibD22x64" -NS"Winapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell"
Embarcadero Delphi for Win32 compiler version 29.0
Copyright (c) 1983,2015 Embarcadero Technologies, Inc.
Fatal: F1026 File not found: 'frce.dpk'
Compilation failure

**Comment by juliomar** [comment]
Seu delphi é trial?
executou o instalador como administrador?

**Comment by juliomar** [comment]
Sugestão é deixar o path menor e verificar se não está muito grande no library path assim ele não irá funcionar.,
ou você fez copia para um local errado o exe deve de estar na pasta raiz do git

**Comment by Tigerclaw1980** [comment]
Copie o arquivo do fortes Report (depois de instalado) frce.bpl para a pasta:
C:\users\Public\Documents\Embarcadero\Studio\21.0\Bpl\frce.bpl  (21.0 é o Delphi 10.4 Sydney, veja qual é seu Delphi)

Copie o arquivo frce.dcp para a pasta:
C:\users\Public\Documents\Embarcadero\Studio\21.0\Dcp\frce.dp

E tente instalar novamente. Funcionou comigo e achei a solução na unha.

**Comment by juliomar** [comment]
Não é a solução . ocorreu algo ou está usando o executável do instalador errado
ao fazer isso tu vai ocasionar erros futuramente seja pra atualizar e instalar.
o instalador faz o seguinte, adicionar o path onde ficar o bpl e o dcp as variaveis de embiente do windows e dai sim compila
agora se existir em outros locais no seu micro o mesmo arquivo ele vai dar erro e não vai conseguir instalar
