### ISSUE TITLE
Exportar Excel em uma Única Planilha

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#107]
Olá...

Estou usando o Fortes Report 4.0 VCL. Coloquei um RLXLSFilter1 para exportar os dados em Excel. A exportação ocorre sem problemas. Mas eu preciso que tudo fique concentrado em apenas uma única planilha, e ele cria uma planilha para cada página do relatório. Existe alguma propriedade que faça ele funcionar dessa maneira?

Desde já agradeço a atenção

**Comment by juliomar** [comment]
Migre para a versão CE! 
acho que assim poderá fazer novamente testes para verificar a possibilidade

**Comment by bnobre** [comment]
Na verdade a versão que citei, 4.0 VCL, já é a Community Edition.

**Comment by MarcioMiguel** [comment]
Basta usar a propriedade foOneSheetOnly.

**Comment by bnobre** [comment]
Grato MarcioMiguel, funcionou perfeitamente.

**Comment by MarcioMiguel** [comment]
Opa! estamos ai! Sempre que pudermos ajudar é muito bom....
