### ISSUE TITLE
Erro de Formato de Arquivo do Excel ao Exportar Relatório

### ISSUE THREAD

**Issue by sidneim** [fortesinformatica/fortesreport-ce#109]
Ola,

Tenho um relatório que quando tem apenas um registro ou nenhum exporta para o Excel e tenta abrir o mesmo no OpenOffice ocorre o seguinte erro: "Formato de arquivo do Excel desconhecido ou sem suporte."
![image](https://cloud.githubusercontent.com/assets/2439826/15967143/c9831436-2efc-11e6-944e-be55164bd19d.png)

Este mesmo relatório gerando ele com mais registros funciona perfeitamente.

Algum já passou por algum caso deste?

Obrigado,
Sidnei

**Comment by tonygyn** [comment]
Ola, 
Também estou com problema na exportação do relatório para excel. Após instalar a versão do Fortes Report CE ao exportar um relatório para excel o mesmo não exporta as informações contidas em RLDBText, apenas o que estão em RLLabel.
Alguém já possou por isto ?

**Comment by rodrigoalvesgit** [comment]
Boa tarde.

"tonygyn" o seu problema deve ser porque não os RLDBText não esteja lingado num DataSoure e este num DataSet, Utilize as propriedade DataSourse e DataField.
Espero ter lhe ajudado.

O problema ocorre comigo também de não abrir o arquivo gerado em excel do Fortes, apresentando o mesmo erro. Já tentei abrir em outros visualizadores de excel e o erro persiste.

Alguém tem alguma solução para esta geração?

Rodrigo

**Comment by tonygyn** [comment]
Bom dia rodrigo.
Muito obrigado pela resposta, porém o componente esta linkado, pois o relatório exporta para pdf perfeitamente, ou para qualquer outro export, menos o excel que sai faltando a inforamação do campo.

Grato.

**Comment by juliomar** [comment]
Chegou a atualizar e recompilar?
favor testar novamente e se persistir abrir novo issue com um projeto exemplo e mais detalhes

**Comment by Alt-C-Developer** [comment]
Tive este problema em alguns relatórios meus, e descobrir que as informações não saem na mesma linha linha se estiverem alinhadas com classificação diferente, tipo Uns alinhados ao topo outras alinhadas botton deverá todos da mesma linha com o mesmo alinhamento. 
Quanto as informações que não aparecem, tipo os dados não são exibido, pode ser que o top do componente dos dados esta setado para ser impresso na possição 0(zero), deve ser no minimo com top = 1
