### ISSUE TITLE
Problemas ao instalar o Fortes no delphi7

### ISSUE THREAD

**Issue by MarcoNadai** [fortesinformatica/fortesreport-ce#11]
Baixei o Pacote atual do componente e ao compilar o pacote no d7 ele da varios erros de diretivas de compilação.

preciso atualizar o fortes para poder utilizar o acbrSAT e acbrDanfenfe do Trunk2.

fico no aguardo de alguma dica.

desde já muito obrigado.

**Comment by Oda2** [comment]
Qual erro que está dando?

**Comment by aquiniti** [comment]
O erro é na  RLUtils.pas 
... and CharInSet(AText[AIndex], SPC) 

tem que mudar na declaração para:

{$IFDEF DELPHI7}
function CharInSet(C: AnsiChar; const CharSet: TSysCharSet): Boolean; overload;
function CharInSet(C: WideChar; const CharSet: TSysCharSet): Boolean; overload;
{$ENDIF}

e nas funções:
{$IFDEF DELPHI7}
function CharInSet(C: AnsiChar; const CharSet: TSysCharSet): Boolean;
begin
  Result := C in CharSet;
end;

function CharInSet(C: WideChar; const CharSet: TSysCharSet): Boolean;
begin
  Result := (C < #$0100) and (AnsiChar(C) in CharSet);
end;
{$endif}

**Comment by marciomartins** [comment]
Favor verificar se o problema persistir na a versão atual. Se sim, favor me contactar por e-mail para que eu possa agilizar o ajuste.

mm.marciomartins@gmail.com
