### ISSUE TITLE
problema com instalação no delphi Seattle  - "Can't load package C:\forte\binary\libd32\frce.bpl" 

### ISSUE THREAD

**Issue by LEANDRORICK02** [fortesinformatica/fortesreport-ce#111]
Boa tarde estou com o Delphi Seattle instalado na minha maquina.  Fiz a instalação do  Fortes Report Ce normalmente . Porem quando eu abro o Delphi me aparace uma mesagem de erro  dizendoo seguinte: "Can't load package C:\FORTES REPORT CE\BINARY\LIBD23\FRCE.BPL'". Gostaria de saber se alguem poria me ajudar com este problema

**Comment by juliomar** [comment]
Bom dia
verifique no log de instalação se o seu delphi não está como trial.
se o problema continuar abrir novo issue com o log do instalador em anexo
