### ISSUE TITLE
Erro com RLGroup

### ISSUE THREAD

**Issue by faustoalves1968** [fortesinformatica/fortesreport-ce#112]
Estou com um problema no RLGroup que esta me deixando de cabelo em pé..
Tenho um relatório de contas a pagar, agrupado por fornecedor, ao final de cada fornecedor ele dá um total deste fornecedor, o problema é quando termina a página sem imprimir a banda summary.
Ele faz novamente o header mostra o total mas por esta em outro registro mostra o o fornecedor seguinte.
Exemplo..
FORNECEDOR: JOÃO DA SILVA
DUPLICATA  A                     150,00
DUPLICATA  B                     100,00

---

vamos supor que termine a página sem imprimir o total do JOÃO DA SILVA
Começa outra página 
FORNECEDOR  JOSE RIBEIRO
Total do fornecedor:           250,00

**Comment by alanvcb** [comment]
Tenho o mesmo problema que o fausto. Segue print . O total da pagina de baixo é da ordem de serviço 32, contudo aparece com o numero 41 e o cliente da ordem 41

![erro fortes](https://cloud.githubusercontent.com/assets/20326487/16634388/c8f5bff8-43a3-11e6-9bc5-a18cc5517e22.png)

**Comment by juliomar** [comment]
Boa tarde
o problema ainda persiste?
se sim abrir um novo issue com um projeto de exemplo para poder efetuar os devidos testes e debug
