### ISSUE TITLE
 Fortes Report - Cópia Carbono (Carbon Copies)

### ISSUE THREAD

**Issue by fagner-frserv** [fortesinformatica/fortesreport-ce#114]
Srs.

Preciso resolver uma questão de um cliente. Ele faz a emissão de alguns documentos (recibo, pedido, protocolos), e estou adaptando para impressão na mesma página (formato que ele já usa em seu sistema atual).

Tem algum recurso no Fortes Report CE, que possibilita a impressão nesse formato (Cópia do mesmo documento em uma unica página)?

**Comment by fagner-frserv** [comment]
Alguém!?

**Comment by faustoalves1968** [comment]
Eu também tenho essa necessidade, lembro-me que no QuickReport tem um componente chamado Composite.. mas nada no fortes.

**Comment by dimom** [comment]
Conseguiu algo ?

**Comment by flaudemir79** [comment]
Na RLBand tem uma propriedade CarbonCopies, só colocar a quantidade que se precisa!

**Comment by juliomar** [comment]
Nosso amigo detalhou acima como fazer
Obrigado
