### ISSUE TITLE
 Fortes Report CE impressão sai diferente de acordo com a impressora

### ISSUE THREAD

**Issue by scalon** [fortesinformatica/fortesreport-ce#116]
Eu uso o delphi 2007 , acbrtrunk 2 e o fortesreport CE, e está acontecendo uma coisa muito estranha. Em determinadas impressoras um relatório feito no fortes imprimi normal sem problemas do tamanho certo as fontes enfim imprimi corretamente mas em outra impressora mesmo eu vendo as configurações da impressora como estar tipo papel  A4, 1 pagina por folha tudo certo ele imprimi pequeno como se tivesse a opção 2 ou 3 paginas por folha.

No caso testo em uma impressora lexmark e sai normal já em uma Hp laser ele imprimi pequeno com se tivesse configurado 3 paginas por folha mesmo não estando com essa configuração nas propriedades da impressora.

Quando eu executo a versão do programa (versão gerada ainda no trunk1) esse problema não ocorre. Agora o executável gerado já na versão acbrtrunk 2  acontece esse problema.

Já tentei mudar outras configurações da impressora, mas o problema persisti.

Alguém já passou por isso?
Tem alguma propriedade no Fortes Report CE que faz o relatório em formato pequeno?

Desde já Muito Obrigado pela Atenção!!

**Comment by juliomar** [comment]
Boa tarde
o problema ainda persiste?
se sim abra um novo issue detalhando como ocorrer na impressora citada
