### ISSUE TITLE
Fortes Report -ce Impressão cortando

### ISSUE THREAD

**Issue by dangrasoftware** [fortesinformatica/fortesreport-ce#117]
Estou usando componentes ACBr com FortesReport-ce. A visualização do pdf fica normal, porem ao imprimir o relatório imprime cortando linhas acima e caracteres à esquerda e à direita. Há varios relatos no forum ACBr a respeito do problema. Já foram feitos testes em várias impressoras. Temos problemas com impressoras lexmark, HP Laserjet e HP Deskjet (essas foram as impressoras que eu testei). Não resolve alterar as margens dos relatórios. Aparentemente, a fonte impressa não é a mesma do pdf, os caracteres ficam maiores e portando são cortados na impressão. Ocorre com boletos bancários e notas fiscais eletrônicas. O erro ocorre em Delphi 7, Delphi XE3 (esses os que utilizo), mas há relatos no forum com usuários de outras versões do Delphi. O problema não ocorre com relatórios em FastReport.

**Comment by smelchi** [comment]
Este problema não é devido ao fonte do windows estar com resolução alterada?

**Comment by juliomar** [comment]
Exatamente ou falta das fontes !
se o problema persiste abra novo issue com projeto de exemplo pra testarms
