### ISSUE TITLE
Propriedade NextReport

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#118]
Olá a todos,

Uso a propriedade NextReport para unir 2 relatórios. O problema é que o segundo relatório fica em uma segunda página, e na verdade preciso que o segundo relatório fique logo abaixo do espaço em branco do primeiro formando uma página única.

É possivel?

Desde já agradeço a atenção de todos

**Comment by juliomar** [comment]
Boa tarde
acho que não, o código não foi feito para isso.

**Comment by bnobre** [comment]
E existe alguma maneira de eu fazer isso???
