### ISSUE TITLE
Deslocamento de texto ao imprimir

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#119]
Olá a todos, 

Em alguns relatório do Fortes tenho esse problema, no preview o relatório está perfeito, mas ao imprimir parte do texto se desloca sobre outro, causando distorção.

Observei que ao diminuir/aumentar o zoom no preview, o deslocamento também acontece, só fica normal em 100%. Estou usando a última versão do Fortes atualmente.

Segue alguns anexos esboçando o problema.

Preview em 100%
![preview](https://cloud.githubusercontent.com/assets/14187449/17893816/6e80d3ba-691d-11e6-9c41-7840bc744e79.JPG)

Papel impresso, representado aqui por saída em PDF que sai distorcida exatamente como no impresso.
![impresso](https://cloud.githubusercontent.com/assets/14187449/17893826/75bb6a50-691d-11e6-9eca-9ba9ac0df453.JPG)

Preview em 80%
![80porcento](https://cloud.githubusercontent.com/assets/14187449/17893831/79ecb188-691d-11e6-9ecc-8d6363407d9a.JPG)

Preview em 120%
![120porcento](https://cloud.githubusercontent.com/assets/14187449/17893832/7c2b71aa-691d-11e6-9fed-a604373e8f42.JPG)

**Comment by juliomar** [comment]
Boa tarde
é isso mesmo.
precisa fica 100%
