### ISSUE TITLE
Para salvar um arquivo, o segundo filtro da mesma extensão de arquivos não é selecionado

### ISSUE THREAD

**Issue by welitimbtos** [fortesinformatica/fortesreport-ce#121]
Boa Tarde, 
Descobri que quando vai salvar um relatório independente dos filtros já existentes, se eu adiciono um posteriormente que contém a mesma extensão de um já adicionado, quando eu seleciono este último o relatório é salvo com os padrões do primeiro filtro na ordem de filtros.

**Comment by welitimbtos** [comment]
Consegui corrigir o problema, mas não sei se está nos padrões do projeto.
Deste modo, ele pega a instância do filtro selecionado, e não mais pela extensão do nome. 

[Source.zip](https://github.com/fortesinformatica/fortesreport-ce/files/435223/Source.zip)

**Comment by marciomartins** [comment]
Obrigado, vou analisar.
Você também pode fazer um pull request, caso esteja tudo certo já faço a integração direta no repositório.

**Comment by dopidaniel** [comment]
Aparentemente suas modificações foram efetuadas em uma versão antiga dos fontes do Fortes...

**Comment by dopidaniel** [comment]
Apliquei nos fontes, uma possível correção para o problema, baseado nas suas sugestões...
Favor baixar as atualizações e testar...
