### ISSUE TITLE
Executar um comando após fechar a Pré-visualização

### ISSUE THREAD

**Issue by csrabelo** [fortesinformatica/fortesreport-ce#125]
Boa noite,
gostaria de saber qual a melhor maneira de executar um comando após fechar a "Pré-visualização" de um relatório. Minha intenção é dar a opção ao usuário poder enviar o relatório que acabou de visualizar por e-mail.

Exemplo:
//Para visualizar o relatório usei o comando:
  RLReport1.Preview();

//Imagino que para executar um comando assim que fechar o "Preview" o ideal seria um evento tipo //"AfterPreview" ou algo do gênero.

Fico no aguardo

Agradeço pela atenção

**Comment by marciomartins** [comment]
Caro, para dúvidas sobre utilização favor utilizar o grupo http://tech.groups.yahoo.com/group/fortesreport/
Vou criar um fórum para para gerenciar melhor estas requisições.
