### ISSUE TITLE
Imprimir em PDF sem depender da resolução da tela.

### ISSUE THREAD

**Issue by smelchi** [fortesinformatica/fortesreport-ce#126]
Ao gerar um PDF em um computador onde o usuário aumentou a resolução do fonte para 125%, o relatório gerado aumentou também, cortando uma parte.

Tem como gerar PDF sem depender da resolução da tela?

Obrigado

Sérgio

**Comment by smelchi** [comment]
Ninguém interage aqui, não temos respostas nem positivas nem negativas?

**Comment by marciomartins** [comment]
Caro, para dúvidas sobre utilização favor utilizar o grupo http://tech.groups.yahoo.com/group/fortesreport/
Vou criar um fórum para para gerenciar melhor estas requisições.

**Comment by dopidaniel** [comment]
Possível correção em: 
https://github.com/fortesinformatica/fortesreport-ce/pull/297
