### ISSUE TITLE
Publicação excluída - PDF sai errado com fonte do Windows a 125%

### ISSUE THREAD

**Issue by smelchi** [fortesinformatica/fortesreport-ce#128]
Se o usuário aumenta o fonte para 125%, a impressão sai errrada.

Outros geradores de relatórios do Delphi não sofrem este efeito.

Fonte do relatório não tem nada a ver com fonte do Windows.

Minha publicação foi excluída. 

Se não conseguem resolver isso, publiquem que infelizmente o Fortes Report funciona assim.

**Comment by juliomar** [comment]
Já foi publicado isso em outros locais.
e não foi excluída foi fechada
