### ISSUE TITLE
Exceção ao exibir preview

### ISSUE THREAD

**Issue by dmpimenta** [fortesinformatica/fortesreport-ce#131]
Bom dia pessoal.
Comecei a usar o fortes report recentemente e em um teste que realizei aqui ocorreu a seguinte exceção: 

Project project1 raised exception class 'External: SIGSEGV'.
 In file '../Source/RLPreviewForm.pas' at line 597:
S.Align := alNone;

* Uso lazarus 1.6.2-1 com fpc 3.0.0 em ambiente linux 64bit (gtk2).
* O erro não ocorre quando imprimo.
* Comentando as linhas 597 e 610 do RLPreviewForm.pas o relatório é exibido normalmente.

Valeu pela força :)

**Comment by juliomar** [comment]
Boa tarde
favor atualizar pois estamos rodando com versão superior do lazarus e não ocorre o erro.
