### ISSUE TITLE
Erro ao carregar imagem

### ISSUE THREAD

**Issue by mtsys** [fortesinformatica/fortesreport-ce#133]
Estou usando o AcBR Boleto, e estava tudo funcionando na impressão do relatório e do nada começou a dar a mensagem:

LayoutBoleto: Erro durante a preparação do relatório EInvalidGraphic(Bitmap image is not valid). 
Na minha máquina funciona.

Fiz uma mini aplicação e na minha máquina funciona e no cliente não, linha com erro:

RLImage1.Picture.LoadFromFile(caminho);

**Comment by regyssilveira** [comment]
Verifique o caminho da imagem é o arquivo de bitmap usado no cliente, já vi isto acontecer quando o caminho está com algum carácter inválido ou a imagem não existe e também quando o bitmap não é um bitmap válido.

**Comment by mtsys** [comment]
O arquivo se tornou inválido. Obrigado pela dica.
