### ISSUE TITLE
Exceção ao instanciar relatório com RLRichText. (Lazarus em linux 64Bit)

### ISSUE THREAD

**Issue by dmpimenta** [fortesinformatica/fortesreport-ce#134]
Boa tarde a todos.
Ao instanciar um form com um RLReport contendo um RLRichText no seu detail é disparada uma
exceção ao executar a linha 311 do RLRichText.pas.

* Project sisEduca raised exception class 'External: SIGSEGV'.

Este erro não ocorre em ambiente windows.

Substituí a linha 311 que contém: 
else if Boolean(Buffer^) then
por
else if (Buffer <> nil) and (Boolean(Buffer^)) then

Após a mudança ficou funcionando normalmente.
Espero ter ajudado.

Dario Pimenta.

**Comment by juliomar** [comment]
Boa tarde
verifique se o erro já não foi corrigido 
caso negativo faça um fork altere e envie um pull request
