### ISSUE TITLE
RichText com Imagens

### ISSUE THREAD

**Issue by ealemes** [fortesinformatica/fortesreport-ce#136]
Utilizo JvRichText da Jedi que permite também colocar imagens porem quando vou imprimir com RLRichText ou RLDBRichText as imagens não aparecem.
Tem alguma dica para funcionar?

Grato

**Comment by juliomar** [comment]
Não.
a princípio deva não estar contemplando esse caso.
se quiser sugerir código faça um fork e depois de alterado envie um pull request.
