### ISSUE TITLE
Problema com alinhamento no TRLRichText

### ISSUE THREAD

**Issue by dmpimenta** [fortesinformatica/fortesreport-ce#137]
Boa tarde pessoal.
Estou tendo problemas com o alinhamento (Vertical) entre palavras no TRLRichText (e também com o TRLDBRichText). Podemos reproduzir o problema com o seguinte código:

`TRLRichText.Lines.Add({\rtf1\ansi\deff0 {\fonttbl {\f0 Monotype Corsiva;}}\ql\f0\fs20\i\b Alô \fs40 Mundo!});
`

Que produz a saída:

![captura de tela de 2017-03-08 16 16 51](https://cloud.githubusercontent.com/assets/23313469/23719488/66f94102-041a-11e7-80f3-6fd6eb150c4a.png)

* Percebam o problema de alinhamento da palavra "World".

Algumas considerações:
* Estou usando o Lazarus 1.6.2 com FPC 3.0.0 rodando em Linux 64Bit (Debian Jessie)
* O RTF inserido funciona normalmente com o LibreOffice, WordPad e MSWord.

Desde já agradeço por qualquer orientação.

Dario Pimenta.

**Comment by juliomar** [comment]
Boa tarde
sugere alguma correção? se sim
envie um pull request de seu fork
