### ISSUE TITLE
Erro Delphi Tokyo

### ISSUE THREAD

**Issue by jmcsoftware** [fortesinformatica/fortesreport-ce#140]
instalei manualmente o fortes no tokyo , e acontece o erro:

[dcc32 Error] RLMetaVCL.pas(305): E1012 Constant expression violates subrange bounds

na linha if ASource = succ(taCenter) then

isso na compilacao dos meus projetos.  

Se eu compilar o mesmo projeto no Seatle o erro acima nao acontece.

**Comment by juliomar** [comment]
Boa noite
irei fazer testes e resolvendo subo um pull request

**Comment by jmcsoftware** [comment]
Origado pelo retorno ,


A instalacao feita manual ocorre sem problemas do componente


No buil de um projeto q acontece o erro.


O engracado q no primeiro dia compilou normal todo o projeto. Mas sem fazer nenhuma alteracao no projeto no outro dia da esse erro q foi informado.


Grato.

**Comment by jmcsoftware** [comment]
Fortes Versao 411.


Tirando o succ compila normal , mas na execucao do relatorio da erro de range check error



JMC

________________________________

**Comment by juliomar** [comment]
como assim fortes 411?/
acabei de fazer testes e funcionou perfeitamente

**Comment by jmcsoftware** [comment]
revisao 411


[cid:e06da8e1-6786-4a69-9e1d-aa9cc6c3b0fe]

________________________________

**Comment by jmcsoftware** [comment]
sera pq instalei manual no tokyo , ja saiu atualizacao para o instalador no Tokyo ?


________________________________

**Comment by juliomar** [comment]
Pode ser! não foi aceito o pull request mas tu pode adicionar um remote enquanto isso e pegar a atualização do meu GitHub até aceitar aqui e depois retorna o remote

**Comment by jmcsoftware** [comment]
Desculpe a ignorancia no GitHub mas como consigo pegar as suas alteracoes feitas ?



________________________________

**Comment by juliomar** [comment]
deve adicionar a sua pasta um remote apontando para o meu repositorio
baixar ele e pedir para fazer um merge ou rebase

**Comment by jmcsoftware** [comment]
liberaram sua atualizacao juliomar , mas ainda continuo com o erro na compilacao de alguns projetos no tokyo.  Os mesmos projetos no berlin nao acontece o erro abaixo:

[dcc32 Error] RLMetaVCL.pas(305): E1012 Constant expression violates subrange bounds

na linha 306 da unit RLMETAVCL  ->   if ASource = succ(taCenter) then

**Comment by juliomar** [comment]
Sim ! 
isso é algo especifico ou qualquer relatório que rode vai dar o problema?

**Comment by jmcsoftware** [comment]
o problema nao e na execucao do projeto , o projeto nem compila com o erro acima no tokyo. No berlim o mesmo projeto compila normal

**Comment by regyssilveira** [comment]
eu tenho projetos aqui no Tokyo com o Fortes e aparentemente está tudo normal, poderia dar uma ideia do cenário para tentar simular aqui?

**Comment by jmcsoftware** [comment]
tambem quando faco um projeto novo o erro nao acontece , so no projeto existente. Mas o engracado e que nao faco alteracao nenhuma no projeto e no berlin compila normal sem erros. Se alguem puder visualizar remoto conversamos no skype jmcsoftware

**Comment by jmcsoftware** [comment]
descoberto o problema , sao os filtros pdf ou excel nos projetos existentes.
quando se retira o componente dos filtros e inclue novamente a compilacao executa sem problemas.

**Comment by educmsilva** [comment]
Instalei normal o Fortes, mais ele não aparece na minha paleta quando crio o projeto.. Alguem sabe porque?

**Comment by juliomar** [comment]
Estranho é algo local no seu micro! tenho no Berlin, Tokyo, XE7 e outras versões sem problema algum e instalado usando o instalador

**Comment by educmsilva** [comment]
O que pode ser, setei as pastas la no Library e mesmo assim nada...

**Comment by educmsilva** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/27840853/25282667/91aa5258-2687-11e7-972e-7e78dd311ff3.jpg)

**Comment by juliomar** [comment]
Resolveu seu problema?
caso negativo favor detalhar mas refiz o teste e está funcionando no tokyo, inclusive no update 2
