### ISSUE TITLE
Banda + Panel + Memo Autosize

### ISSUE THREAD

**Issue by tbalbinos** [fortesinformatica/fortesreport-ce#141]
Boa tarde pessoal, vejam na imagem, que o Memo não expande para mostrar o conteúdo de forma correta. o link do código do projeto está abaixo.

![fortes](https://cloud.githubusercontent.com/assets/10819836/24719050/b02cf134-1a0e-11e7-9caa-a8e531ca5cb1.png)

Ps: Utilizei delphi berlin, o mesmo código no delphi 2010 ocorre o erro.

Imagem do erro:
https://drive.google.com/open?id=0B2_wjC5DhS3xdkpEQ3l6X0d3bFE

Codigo Fonte:
https://drive.google.com/file/d/0B2_wjC5DhS3xa2w1ZnpXeFNUUW8/view?usp=sharing

**Comment by tbalbinos** [comment]
![fortes](https://cloud.githubusercontent.com/assets/10819836/24719050/b02cf134-1a0e-11e7-9caa-a8e531ca5cb1.png)

**Comment by juliomar** [comment]
Assim que possível irei testar.

**Comment by dopidaniel** [comment]
Notei que você inseri cada um dos campos em um TRLPanel.. isso deve estar atrapalhando o calculo de expansão do Fortes...

Para desenhar as bordas do campo... você pode usar a Propriedade "TRLDBText.Borders" ou ainda o TRLDraw

**Comment by igorbastosib** [comment]
Não sei no seu contexto, mas no meu os, onde tbm enfrentei este problema, meu relatório específico não terá mais que 50 linhas de dados, então fica aceitável fazer da forma como vou explicar.

Segue código: http://textuploader.com/dmbz6

Meu RLDBMemo está diretamente no RLBand4, AutoSize, WordWrap e com alinhamento à Esquerda. O campo vinculado a ele é o Observacao que é do tipo Blob. Este campo possui possibilidade de ter várias linhas e cada linha ser extremamente grande, sendo assim eu estipulei um tamanho para a coluna de 38 caracteres.
Basicamente eu jogo o Observacao em um StringList, assim eu sei ou Lines.Count, depois percorro cada linha do StringList verificando se vou precisar de mais linhas, ou seja, se as linhas de Observacao tem mais de 38 caracteres, assim eu identifico as linhas adicionais e por fim, multiplico o resultado pelo tamanho da minha linha.

Isso resolveu o problema do AutoSize não estar funcionando corretamente, mas sei que é uma solução extremamente específica e temporária. Espero ter ajudado.

**Comment by dopidaniel** [comment]
Fechando... Problema pode ser resolvido por design
