### ISSUE TITLE
 Configuração da impressão não é respeitada no Fortes Report

### ISSUE THREAD

**Issue by leotelles** [fortesinformatica/fortesreport-ce#142]
Bom dia. Um de nossos clientes usa a impressora em modo econômico, definido através das preferências de impressão em Painel de Controle > Dispositivos e Impressoras (Windows). O usuário deseja alterar essa configuração, voltando para o modo normal de impressão apenas ao imprimir a nota fiscal no nosso sistema (utilizamos o ACBrNFe para gerar as impressões, através da ferramenta Fortes Report).

Ao clicar em imprimir no nosso sistema, é aberta aquela tela de visualização da impressão gerada pelo Fortes Report. Nessa tela, é possível selecionar a impressora e clicar no botão Propriedades para alterar as configurações da impressão. A tela de propriedades é a mesma que é aberta ao ir em Painel de Controle > Dispositivos e Impressoras > Preferências de Impressão. O problema é que as alterações feitas nessa tela de configuração do Fortes não são respeitadas ao imprimir a nota. No caso, o usuário clica nas propriedades da impressora através da visualização do Fortes, clica na opção Modo Economia para desmarcá-la, imprime a nota e eis que a impressão continua saindo em modo econômico.

Detalhe: se o usuário faz o mesmo procedimento em qualquer outro software instalado no computador (qualquer editor de texto, leitor de pdf, etc) o problema não ocorre, ou seja, a configuração alterada é respeitada, imprimindo exatamente como ele configurou. Apenas nas impressões geradas pelo nosso sistema (via ACBr + Fortes) a configuração alterada não é respeitada.

Alguém já enfrentou esse problema ou tem alguma orientação que possa nos ajudar? Desde já agradeço.

**Comment by juliomar** [comment]
Boa noite 
a principio não .. poderia informar a marcar e modelo da impressora?

**Comment by leotelles** [comment]
Nossa impressora: HP Laser Jet Professional M1132 MFP
Impressora do nosso cliente: HP Laser Jet Pro M201DW

Testamos nesses dois equipamentos. Em outros softwares (Word, por exemplo) o problema não ocorre ao usar os mesmos equipamentos.

**Comment by adilsonpazzini** [comment]
Estou com o Mesmo problema . porem identificamos que na hora de imprimir , ele esta pegando as configuracoes da Impressora Default .. por exemplo , se eu tiver uma Impressora "bematech mp 4200 th" e uma "HP 1100" Instalada no computador , e a impressora Default estiver a "bematech mp 4200 th" , se eu na hora de imprimir escolher a "HP 1100" , A impressao sai na "HP 1100" porem com as configuracoes da "bematech mp 4200 th" .

Fiz esse mesmo teste usando o CUTEPDF como impressora Padrao no Windows , e pedi pra imprimir imprimir no "HP 1100" , Porem o relatorio esta configurado no Fortes como Paisagem , porem ao enviar para impressao na "HP 1100" , Ele tranforma em Paisagem , pois e assim que no CUTE PDF esta .. 

Esse problema tambem me parece acontecer em impressoes diretas, usando o Printer.BeginDoc .

Se alguem estiver passando pelo mesmo problema . tenta fazer esse teste tambem. 

Pra ver se conseguimos resolver .

Obrigado .
Sem mais , 
Adilson Pazzini .

**Comment by juliomar** [comment]
Continua a ocorrer?
segurem alguma modificação? favor enviar um pull request
