### ISSUE TITLE
Não encontra package "frce.bpl" no Delphi Seattle

### ISSUE THREAD

**Issue by zamineduardo** [fortesinformatica/fortesreport-ce#143]
Bom dia Amigos,
Fiz a instalação do FortesReport-CE no Delphi Seattle com Windows 10-64b, ele instalou tudo certo sem nenhum erro.
Quando vou abrir o Delphi da a seguinte mensagem:
"Can't load package C:\Fortes\Binary\LibD23\frce.bpl. Não foi possível encontrar o módulo especificado. Do you want to attempt to load this package the next time a project is loaded?"

Baixei todo o instalador dia 05/06/2017.
Agradeço a ajuda e atenção de todos.
Obrigado
Eduardo Zamin

**Comment by juliomar** [comment]
Anexe o log mas é quase certeza que seu delphi é trial e naõ consegue compilar na linha de comando

**Comment by zamineduardo** [comment]
[log_Delphi_10_Seattle.txt](https://github.com/fortesinformatica/fortesreport-ce/files/1052679/log_Delphi_10_Seattle.txt)

Olá Juliomar,
Aqui esta o log da instalação.
Obrigado
Eduardo

**Comment by regyssilveira** [comment]
Veja a mensagem do log:
"This version of the product does not support command line compiling."

Seu Delphi é Trial, então não possui compilador por linha de comando, dai não gera o BPL.

**Comment by zamineduardo** [comment]
Obrigado pelo retorno Regyssilveira,
Existe alguma forma para eu conseguir usar o Fortes com esta versão trial que eu tenho?
Obrigado
Eduardo

**Comment by regyssilveira** [comment]
Baixa pelo GetIT ou abre o pacote e compila e instala, a primeira opção é a mais simples.

**Comment by zamineduardo** [comment]
Obrigado Regys, ou tentar as 2 opções

**Comment by zamineduardo** [comment]
Bom dia,
Obrigado Regys e Juliomar, consegui instalar graças as dicas de vocês, abrindo o pacote, compilando e instalando \0/.
Quero agradecer também a todos que estão ajudando a manter e desenvolver mais funcionalidades para o Fortes Report, uma ferramenta fantástica.
Abraços boa semana para todos.
Eduardo
