### ISSUE TITLE
Largura e altura da TRLAngleLabel não são respeitadas

### ISSUE THREAD

**Issue by leotelles** [fortesinformatica/fortesreport-ce#144]
Bom tarde. Estou com o seguinte problema ao utilizar o Fortes Report: eu crio uma TRLAngleLabel em tempo de execução já definindo o Height e o Width. Mas a largura e a altura que eu defini não são respeitadas. Estou criando com a propriedade AutoSize desabilitada, mas mesmo assim a label fica com o tamanho do texto que está no Caption e não com o tamanho que eu defini. Alguém já enfrentou algo do tipo e poderia me dar uma ajuda?

**Comment by juliomar** [comment]
Boa tarde
a princípio não .
caso ainda esteja com o problema poderia anexar um projeto exemplificando o problema em um novo issue.
