### ISSUE TITLE
Erro ao visualizar PDF no Firefox

### ISSUE THREAD

**Issue by mtsys** [fortesinformatica/fortesreport-ce#145]
Estou usando o AcBR Boleto, e gerando o PDF do boleto a partir do Fortes Report. Ao abrir ele no Chrome ele mostra tudo ok, porém se abrir o mesmo arquivo no FireFox, ele é fica com todos os caracteres em formato de desenho.

Postei a dúvida no stackoverflow

https://pt.stackoverflow.com/questions/210743/problemas-com-arquivo-pdf?noredirect=1#comment430862_210743

Será que tem alguma coisa que estou fazendo de errado?

**Comment by juliomar** [comment]
Parece não estar levando as fontes junto com o pdf por isso o erro.
