### ISSUE TITLE
Bug in fortesreport

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#146]
Olá,

Favor verificar se este bug esta presente no Fortes Report, segue o link:
http://www.pilotlogic.com/sitejoom/index.php/forum/pl-fortesreport/3795-bug-in-fortesreport

Dear Deeloper

I found a bug in FortesReport :

In preview mode Find doesn't work, i get an empty Search Dialog .

Modify :

rlfinddialog.pas

Add :

constructor CreateNew(AOwner: TComponent; Num: Integer=0); override;

constructor TfrmRLFindDialog.CreateNew(aOwner: TComponent; Num: Integer=0);
begin
inherited CreateNew(aOwner,Num);
Init;
end;

because we use CreateNew and not Create method to call this form.

Thank you Attila

Thanks Sir
we will check and fix this

**Comment by juliomar** [comment]
Boa tarde
você é da pilotlogic?
está sugerindo correções? se sim faça um fork aplique as mudanças e faça um pull request
poderia detalhar melhor o problema e um exemplo
