### ISSUE TITLE
Problema na instalação do FortesReport no Lazarus

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#15]
Olá,

Estou tentando instalar o Fortes no Lazarus 1.4.2 e esta apresentados erros, conforme o anexo e não instala.

--
Edson

**Comment by elidorio** [comment]
![fortesreport3](https://cloud.githubusercontent.com/assets/2966579/8892265/1980aef4-3326-11e5-974d-63aa9e064091.png)
![fortesreport2](https://cloud.githubusercontent.com/assets/2966579/8892266/19876870-3326-11e5-923e-8ef594cbb36e.png)

**Comment by marciomartins** [comment]
Obrigado pelo detalhamento. Com relação à versão para o Lazarus por enquanto ainda continua separada, pois tivemos alguns problema para integrar, e devido a falta de temos resolvemos deixar separado por enquanto, mas logo retomaremos para que seja uma única versão, pois acreditamos que seria o melhor para o produto e para a comunidade.
Qualquer dúvida pode entrar em contato comigo direto pelo e-mail mm.marciomartins@gmail.com
