### ISSUE TITLE
Problema com Background distribuido

### ISSUE THREAD

**Issue by RodrigoMartinho** [fortesinformatica/fortesreport-ce#150]
Quando utilizo o Background com o Arrange baDistributed e coloca a opção para o usuário poder optar ou não pela impressão, na primeira vez funciona, mas depois não funciona mais.

RLReport.Background.Picture := nil;

RLReport.Background.Picture.LoadFromFile('C:\fundo.bmp');
RLReport.Background.Arrange := baDistributed;

Pelo que notei, o erro ocorre no RLReport.pas, quando está com o tipo baDistributed nas duas procedures PaintTo, ele joga B := needAuxBitmap; eu mudei para B := TBitmap.Create; e ai funcionou, porém, não sei se é o certo.

**Comment by juliomar** [comment]
Bom dia
poderia fazer o fork alterar e gerar um pull request para que analisemos a sua sugestão de correção 
e se possível anexar imagens com o erro aqui comentado.

**Comment by juliomar** [comment]
Bom dia 
foi aceito algo que fazia mudança para essa situação 
atualize seu fork e refaça os testes 
problemas abra novo issue.
