### ISSUE TITLE
Nota fiscal eletrônica com problemas no ACBR

### ISSUE THREAD

**Issue by GeovaniPO** [fortesinformatica/fortesreport-ce#151]
Olá amigos!

Uso o ACBR e o Fortes Report CE para impressão de Notas fiscais eletrônicas porém os arquivos PDF gerado pelo Fortes report distorce e com isso encobre informações importantes como dígitos de números etc...
Sabem me informar se esse problema pode ser resolvido com uma atualização ou de alguma outra forma?

**Comment by juliomar** [comment]
confere as fontes usadas do windows e também o zoom do sistema.

**Comment by GeovaniPO** [comment]
Olá Juliomar, obrigado pelo retorno.
Não consegui entender a sua explicação.
Poderia me dar mais detalhes?


Obtenha seu próprio e-mail assinatura
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

2017-07-13 11:33 GMT-03:00 Juliomar Marchetti <notifications@github.com>:

**Comment by juliomar** [comment]
Fontes do windows. depois o zoom também do windows.

**Comment by GeovaniPO** [comment]
Olá Juliomar!
Olhei o zoom da fonte do windows e está em normal, 100%.
A fonte deve ser alguma específica?



Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

2017-07-13 19:42 GMT-03:00 Juliomar Marchetti <notifications@github.com>:

**Comment by juliomar** [comment]
A princípio não.
por favor anexe um pdf para que possa visualizar aqui .

**Comment by GeovaniPO** [comment]
Olá, bom dia!

Seguem duas imagens, uma do preview da NFe ainda alinhada e a segunda é um
print do PFD depois de salvo pelo usuário.





Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

2017-07-17 20:43 GMT-03:00 Juliomar Marchetti <notifications@github.com>:

**Comment by juliomar** [comment]
Não veio.

**Comment by GeovaniPO** [comment]
Olá, Bom dia!
Estranho, as imagens estão anexadas no e-mail.
Vou enviar novamente.




Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

2017-07-18 15:50 GMT-03:00 Juliomar Marchetti <notifications@github.com>:

**Comment by juliomar** [comment]
Anexe aqui, não sei pra qual e-mail está enviando mas não tenho nenhum aqui.

**Comment by GeovaniPO** [comment]
Me parece que não tem como adicionar imagens aqui. 
Não encontrei.
Estava enviando direto do e-mail.

**Comment by GeovaniPO** [comment]
Olá!
Encontrei o local para anexar as imagens. rs

Preview da nota na tela e Print do PDF salvo

![nf-e no sistema](https://user-images.githubusercontent.com/26914190/28372349-d9724b52-6c75-11e7-91f8-b31fb540f2d3.png)
![pdf nf-e](https://user-images.githubusercontent.com/26914190/28372350-d97a4aaa-6c75-11e7-96f0-7938ead37a64.png)

**Comment by aloisiopires** [comment]
Olá.

Também estou com esse problema do pdf gerado cortando informações importantes.
Vi que não houve mais interações nessa postagem.

Como resolver esse erro?

Agradeço desde já.

**Comment by juliomar** [comment]
Bom dia
esse erro é por falta de fontes padrões no micro
favor rever as fontes que está instalada no windows.
geralmente é arial, tahoma, segou ou corrier ou corrier new
