### ISSUE TITLE
Erro usando o Fortes sem impressora instalada

### ISSUE THREAD

**Issue by drungrin** [fortesinformatica/fortesreport-ce#155]
O Fortes deve ser capaz de usar filtros sem impressoras instaladas.

Ocorre a exception "Nenhuma impressora encontrada"

Pull Request já existe para isso https://github.com/fortesinformatica/fortesreport-ce/pull/149

Porém sem atividades.

**Comment by juliomar** [comment]
Boa noite !
favor aguardar projeto OpenSource deve se ter paciência
já está sendo analisado.
