### ISSUE TITLE
Não funciona a propriedade da fonte  Orientation

### ISSUE THREAD

**Issue by MichelPereiraSeicon** [fortesinformatica/fortesreport-ce#157]
Bom dia,
Quanto alteramos a fonte em sua propriedade Orientation, aparentemente não esta sendo transmitida corretamente ao componente pois se comporta muito estanhamente.
No preview sai de um jeito e na impressao de outro.

**Comment by MichelPereiraSeicon** [comment]
Corrigi os componentes RLLabel e RLMemo
Segue abaixo os arquivos, por favor coloquem na nova versão.
[FortesReport.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1271776/FortesReport.zip)

**Comment by juliomar** [comment]
Bom dia
não foi possível aplicar as alterações
além de aplicar um formatado de código existem mudanças que não corresponde ao relatado acima
favor refazer o que deseja e anexar novamente em um novo issue para que possa ser aplicado ou fazer um pull request diretamente no git com as alterações
