### ISSUE TITLE
Imprimindo em Paisagem em vez de Retrato

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#159]
Bom dia a Todos,

Estamos utilizando uma HP M125a multifuncional laser, quando uso o relatorio com o Pagesetup em papersize com fpCustom PaperHeight = 160 e PaperWidth = 210 esta imprimindo em Paisagem ao inves de retrato. Porém se eu utilizar uma impressora jato de tinta, imprime corretamente. Liguei para HP e eles disseram que é problema no sistema. Fizemos um teste no word e funcionou. O que vcs acham que pode ser?
Grato

**Comment by dominioararangua** [comment]
Boa tarde Juliomar,

Nesse caso o que eu posso fazer?

Grato

**Comment by dominioararangua** [comment]
Tenho a impressora e tenho o manual, onde tenho que verificar?

**Comment by juliomar** [comment]
Bom dia
ler os comandos que é usado nela e verificar se os mesmos precisam ser tratado nos fontes do fortes, basta baixar e ler todos os fontes para entender como funciona e assim corrigir caso necessário.

**Comment by juliomar** [comment]
se quiser enviar modificações favor enviar um pull request no git
