### ISSUE TITLE
RLReport não imprime paisagem

### ISSUE THREAD

**Issue by fmlamberti** [fortesinformatica/fortesreport-ce#160]
Estou tentando imprimir em modo paisagem em uma HP M1212nf MPF mas só sai retrato, consequentemente cortando o texto a ser impresso. A impressora está em rede. 
Antes funcionava perfeitamente. Depois da atualização para Fortes 4.0 com fontes datados de 27.01.2017 parou. Inclusive atualizei o componente hoje com os fontes datados de 24.06.2017, mas nada aconteceu.
Já fiz de tudo inclusive forçar a impressora a imprimir em paisagem mas nem assim.

**Comment by fmlamberti** [comment]
@juliomar  conseguiu verificar esta situação da impressão em paisagem ?

**Comment by fmlamberti** [comment]
Ainda não resolvi @juliomar . O que fiz para meus clientes pararem de me perturbar foi colocar alguns relatórios em retrato. Mas a impressão em paisagem nada ainda.

**Comment by juliomar** [comment]
Poderia anexar um projetinho de exemplo ressaltando o erro para que possa ser visto?

**Comment by juliomar** [comment]
Confere no código que tem tratamento para modelos e marcas especificas de impressoras.
