### ISSUE TITLE
Fortes report não exportando todas as colunas para excel

### ISSUE THREAD

**Issue by EvandroFujii** [fortesinformatica/fortesreport-ce#161]
Para melhor entendimento meus relatórios são dinâmicos ou seja o usuário escolhe quais colunas irá visualizar, imprimir portanto ele pode selecionar "n" campos.
Após atualizar a versão do fortes report ele não esta exportando todas as colunas que eu seleciono dos meus relatórios para excel extensão .xls, somente as colunas visíveis na visualização são exportadas.
Na versão anterior todas as colunas eram exportadas mesmo que elas são fossem exibidas na visualização. 

![listagem_prod_1](https://user-images.githubusercontent.com/32574632/31284350-aa931f9e-aa8e-11e7-88d6-c26cc0de5616.PNG)
![listagem_prod_2](https://user-images.githubusercontent.com/32574632/31284354-ad8dc4e2-aa8e-11e7-91ee-c54160c5ee20.PNG)
![listagem_prod_3](https://user-images.githubusercontent.com/32574632/31284359-b07918f0-aa8e-11e7-8f2d-4df24619e8a3.PNG)

**Comment by juliomar** [comment]
Boa tarde
tente usar o filtro para xlsx

**Comment by EvandroFujii** [comment]
Obrigado Juliomar pela atenção, utilizando este filtro xlsx a aparência ficou bem melhor as colunas, linhas ficaram bem mais ajustadas mas ainda meu problema persiste.

**Comment by juliomar** [comment]
Estranho.
o problema persiste? se sim favor criar novo issue e anexar um projeto de exemplo onde ocorra o erro.
