### ISSUE TITLE
Fortesreport x64

### ISSUE THREAD

**Issue by lecobrandao** [fortesinformatica/fortesreport-ce#162]
Estou migrando minha aplicação para x64 com o Delphi XE 10.1 Berlin e estou obtendo um erro ao tentar compilar o Fortesreport para a plataforma Windows x64.

_E2213 Bad packaged unit format: C:\Program Files (x86)\Embarcadero\Studio\18.0\lib\Win64\release\rtl.dcp.System - Expected version: 31.0, Windows Unicode(x86) Found version: 31.0, Windows Unicode(x64)_

[log_Delphi_10.1_Berlin.txt](https://github.com/fortesinformatica/fortesreport-ce/files/1553223/log_Delphi_10.1_Berlin.txt)

**Comment by juliomar** [comment]
Bom dia
esse erro remete ao delphi e não ao fortes
tente limpar instalações anteriores que tenha do fortes em seu micro e mantenha somente em um local 
se o problema persistir abra novo issue com maiores detalhes.
