### ISSUE TITLE
Fortes x64

### ISSUE THREAD

**Issue by lecobrandao** [fortesinformatica/fortesreport-ce#164]
Erro persiste ao tentar instalar o fortes escolhendo a opção x64. Segue log de erros.

[log_Delphi_10.1_Berlin.txt](https://github.com/fortesinformatica/fortesreport-ce/files/1600482/log_Delphi_10.1_Berlin.txt)

**Comment by juliomar** [comment]
Boa tarde
não escolha x64.
instale como win32
depois crie um projeto e add a plataforma x64 e veja que os componentes estão disponiveis

**Comment by lecobrandao** [comment]
Boa tarde!
Instalei com win32 e funciona normalmente. Os componentes ficam disponíveis e consigo utilizá-los normalmente. Mas realmente preciso da versão x64 para colocar no meu servidor x64. 
Existe alguma solução?

**Comment by juliomar** [comment]
Bom a primeira sugestão tire de dentro da pasta do sistema
program files é protegido do sistema, igual ao ACBr é proposital ter uma pasta e fora de lá assim funcionara 
a segunda após instalar aponte no library path do x64 no delphi os sources e irá funciona.

**Comment by lecobrandao** [comment]
A pasta LibD24x64 está em branca. Talvez por conta do erro na instalação.

**Comment by juliomar** [comment]
conforme falei aponte para o Source e tente então rodar
