### ISSUE TITLE
Comentário sobre meu issue #119

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#166]
Obrigado por ter me respondido Juliomar, mas eu já havia observado que em 100% no preview fica normal... O problema é que na impressão não fica, conforme relatei.

**Comment by juliomar** [comment]
Qual marca e modelo da impressora? ou em todas? ou no pdf

**Comment by bnobre** [comment]
Em todas e ao gerar o arquivo PDF também... Comentei no issue #119 sobre a discrepância entre as visualizações por achar que esse bug poderia ter relação com o problema na impressão

**Comment by juliomar** [comment]
Bom estranho uso somente para danfe , dacte etc 
mas não fica diferente

**Comment by bnobre** [comment]
Mas como pode constatar no meu fica... E olha que já migrei do Delphi 7 para o Delphi 2010 em outro computador e continua a mesma problemática

**Comment by juliomar** [comment]
Sugere alguma correção? ou algo que possa ser feito?

**Comment by bnobre** [comment]
Não

**Comment by dopidaniel** [comment]
É algo fundo nos fontes do Fortes, que ainda não conseguimos identificar...

Pelo que notei, o problema só ocorre em Sistemas Operacionais configurados para usar o Fontes com mais de 96 DPI... Deixe a fonte do Windows com o tamanho padrão...
