### ISSUE TITLE
Salvar PDF com fonte externa ao Windows

### ISSUE THREAD

**Issue by igorbastosib** [fortesinformatica/fortesreport-ce#167]
Contexto: 
Estou criando um relatório com e estou utilizando uma fonte externa ao Windows (Akkurat.ttf), salvando em PDF e enviando para os clientes. 
O problema é que como o relatório está utilizando uma fonte externa ao Windows, ele fica totalmente diferente nas máquinas dos Clientes. Nos Clientes o relatório abre o PDF utilizando a Calibri (que já vem no Windows). 

É possível carregar a fonte externa no PDF para que o mesmo seja aberto corretamente em qualquer PC?
Ou fixar para que a fonte não seja alterada onde não a tenha?

Fiz um teste simples utilizando o Word: gerei um texto todo com a fonte Akkurat, salvei em PDF e abri em um PC sem a mesma instaladao, o PDF abriu normalmente com a fonte escolhida.
Percebi que o PDF do Word segue com a Fonte embedded, mas isso não acontece no PDF do FortesReport.

PDF Word: http://666kb.com/i/dpzx3eht6b6g24e3d.jpg
PDF FortesReport: http://666kb.com/i/dpzx2xnimj9nvjyvt.jpg

Estou utilizando o seguinte código para salvar o PDF:

```
VFrmRelOpu.RLReport1.Prepare;
VFrmRelOpu.RLReport1.SaveToFile(System.IOUtils.TPath.Combine(VRelatoriosPath, VRelName));
```

**Comment by rftd** [comment]
O a versão de PDF implementada no Fortes não tem opção de incorporar a fonte no pdf.

**Comment by igorbastosib** [comment]
Qual Unit trabalha com essa conversão para PDF, gostaria de trabalhar para implementar a função. É muito útil.

**Comment by rftd** [comment]
SynPDF tem esta função 
qualquer lib pdf que tenha implementado no minimo PDF 1.4 e com este suporte, mas ai você teria que criar um exporte para o fortes que use esta lib

**Comment by igorbastosib** [comment]
Obrigado rftd. Vou ver se consigo implementar e mando o código p vcs atualizarem, se quiserem.
