### ISSUE TITLE
Sumiu Opção para compilar FPC/Lazarus

### ISSUE THREAD

**Issue by rodilson** [fortesinformatica/fortesreport-ce#17]
Márcio Martins,
Atualizei o componente para a versão atual via svn e desapareceu a opção de compilar o pacote para o FPC/Lazarus. Acredito que tem a ver com a atualização que você teve de retornar (de acordo com sua mensagem na pagina principal deste).
Como proceder para termos a opção que existia para FPC/Lazarus na versão atual?

Grato pela atenção

**Comment by marciomartins** [comment]
A versão em SVN no SourceForge foi descontinuada, a versão oficial é esta.
Com relação à versão para o Lazarus por enquanto ainda continua separada, pois tivemos alguns problema para integrar, e devido a falta de temos resolvemos deixar separado por enquanto, mas logo retomaremos para que seja uma única versão, pois acreditamos que seria o melhor para o produto e para a comunidade.
Qualquer dúvida pode entrar em contato comigo direto pelo e-mail mm.marciomartins@gmail.com
