### ISSUE TITLE
Caracteres especiais substituídos por "?"

### ISSUE THREAD

**Issue by luizmenin** [fortesinformatica/fortesreport-ce#170]
Após a atualização dos fontes para a última versão, começou a ocorrer a seguinte situação:
A visualização do relatório está correta, porém, ao enviar o comando para salvar em PDF, no arquivo os caracteres especiais são substituídos por "?".

**Comment by dopidaniel** [comment]
Por favor anexe um mini projeto, que seja capaz de reproduzir o problema...

**Comment by luizmenin** [comment]
Segue projeto de exemplo conforme solicitado.

[FortesExemplo.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1736590/FortesExemplo.zip)

**Comment by dopidaniel** [comment]
Não consegui reproduzir o problema... mesmo usando o seu **FortesExemplo.exe**
Veja uma imagem da Saída...

![image](https://user-images.githubusercontent.com/9051702/36377059-4ff42890-1554-11e8-941e-faa460039f84.png)

Eu uso Win10 Pro, 64, em Português...   

Qual é o seu sistema operacional ?

**Comment by dopidaniel** [comment]
Ok... agora que notei que o problema seria na geração do PDF... mas mesmo assim, não consegui reproduzir  o problema... mesmo usando o seu Executável... Veja um teste em anexo:
[teste.pdf](https://github.com/fortesinformatica/fortesreport-ce/files/1736645/teste.pdf)

**Comment by luizmenin** [comment]
O sistema operacional é o Windows 10, 64, Português.
Você tentou rodar pelo executável enviado ou você recompilou o projeto?
Sim, a simulação é feita através do botão "Salvar" da janela Preview.
O resultado da minha simulação está no "ArquivoGerado.pdf" dentro da pasta Win32\Release.

**Comment by dopidaniel** [comment]
Sim, testei com o seu próprio .EXE... também não consegui reproduzir o problema, compilando o Demo...
Mas realmente notei que o seu PDF anexado está com problemas de Encoding...

Procurei por diferenças na Unit **RLUtils.pas**,  no método:
 function GetAnsiStr(AString: String): AnsiString;

mas não notei nenhuma modificação recente que pudesse causar o problema...

**Comment by luizmenin** [comment]
Para conseguir instalar o componente, precisei fazer uma modificação na Unit RLReport.pas. Será que não é isso?
Dentro da function GetFieldText, ao chamar SmartGetFieldDisplayText, somente um parâmetro é requisitado, mas ele tenta passar (F, FDisplayMask).
Alterei para:
`Result := SmartGetFieldDisplayText(F{, FDisplayMask})`

**Comment by dopidaniel** [comment]
Tente reverter a modificação... verifique ainda se você possui outras modificações em suas Units...
Os fontes do repositório estão compilando sem erros em D7 a DXE10 e Lazarus/FPC

**Comment by dopidaniel** [comment]
Incapaz de reproduzir o problema...
