### ISSUE TITLE
Impressão REDE

### ISSUE THREAD

**Issue by jadielson** [fortesinformatica/fortesreport-ce#174]
Caros, 
Tenho uma pequena solução para restaurante e estou fazendo a migração dos relatório para o fortes report, como é sabido por muito o sistema para restaurante é bem dinâmico em termo de impressão.

Exemplo: tenho um cadastro de impressoras onde é apontada o caminho de todas, com isso quando o garçom ou o atendente no balcão digita um pedido o sistema envia o produto para uma determina impressora que está vinculada ao produto, fazendo assim a impressão na cozinha, caixa, balcão de bebidas, etc..

Bem, não estou sabendo como fazer o envio da impressão para cada ponto através do fortes report.
-> tipo: \\192.168.10.1\cozinha ou \\192.168.10.1\bebidas e assim por diante.

Onde posso colocar esse endereço dentro do fortes reporte para ele entender que o produto tem que ser impressora naquele determinado caminho que foi definido no cadastro (impressora) ?

Atc,
Jadielson Rodrigues
Obrigado pela ajuda.

**Comment by dopidaniel** [comment]
Você deve fazer esse mapeamento usando recursos de rede do sistema operacional... como por exemplo, instalando uma impressora remota...

**Comment by jadielson** [comment]
A pergunta não é essa de como fazer isso no S.O., mais sim como colocar essa informação no fortes report de forma que ele saiba que a impressão tem q sair no \\192.168.10.10\cozinha.

**Comment by dopidaniel** [comment]
Não é uma tarefa para o Fortes... 

No Fortes, você apenas tem a possibilidade de informar o  **Nome da Impressora,** conforme instalado no Windows...
