### ISSUE TITLE
Please make this change RLRichText to avoid crash.

### ISSUE THREAD

**Issue by Soner-A** [fortesinformatica/fortesreport-ce#176]
When you add TRLRichText without text on runtime, then the programm crashes, please make this change to avoid crash.
Bold marked line, other lines show where to change. Add the condition "**_Assigned(Buffer) and_**" 
in RLRichText.pas 
procedure RichTextParse(...);
function NextCh(var ACh: char): Boolean;
begin
  if RefusedChCount > 0 then
  begin
    ACh := RefusedCh[RefusedChCount];
    Dec(RefusedChCount);
  end  
**else if  _Assigned(Buffer) and_ Boolean(Buffer^) then**  //LINE 323, change this
  begin
    ACh := Buffer^;
    Inc(Buffer);
  end

**Comment by dopidaniel** [comment]
Thanks for the bug report and analysis...
Could you please submit a Pull Request for this issue ?

**Comment by dopidaniel** [comment]
Applied in Pull
https://github.com/fortesinformatica/fortesreport-ce/pull/178
