### ISSUE TITLE
Corte de impressão - Fortes Report

### ISSUE THREAD

**Issue by fabricio-controla** [fortesinformatica/fortesreport-ce#179]
Bom dia amigos, venho expor um problema que tem afetado a impressão do componente RLMemo.

Para simular o problema é só colocar um RLReport em um form e depois colocar um RLMemo vou colocar aqui o código do form exemplo, basta copiar e colar em um form

object RLReport1: TRLReport
  Left = 98
  Top = 28
  Width = 280
  Height = 378
  Margins.LeftMargin = 2.000000000000000000
  Margins.TopMargin = 2.000000000000000000
  Margins.RightMargin = 2.000000000000000000
  Margins.BottomMargin = 9.000000000000000000
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  PageSetup.PaperSize = fpCustom
  PageSetup.PaperWidth = 74.000000000000000000
  PageSetup.PaperHeight = 100.000000000000000000
  PrintDialog = False
  ShowProgress = False
  object RLMemo1: TRLMemo
    Left = 26
    Top = 86
    Width = 227
    Height = 34
    Behavior = [beSiteExpander]
    Borders.Sides = sdCustom
    Borders.DrawLeft = True
    Borders.DrawTop = True
    Borders.DrawRight = True
    Borders.DrawBottom = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    Lines.Strings = (
      
        'R DOUTOR JOSE NEUBERT DE OLIVEIRA 9999 - B RECREIO SAO JUDAS TAD' +
        'EU')
    ParentFont = False
  end
  object RLDraw1: TRLDraw
    Left = 26
    Top = 63
    Width = 227
    Height = 15
    Brush.Color = clGray
  end
end

Nas imagens vocês podem ver o problema da impressão, já tentei achar uma solução olhando os fontes do fortes, mas o máximo que consegui foi chegar na conclusão que o problema está na hora de fazer o cálculo de limite disponível para a linha para fazer o wordwrap, eu acho que esta relacionado com a função CanvasTextWidth do arquivo RLReport.pas.

Não sei se tem algo relacionado a diferença de pixels por polegada video x impressora. Pessoal, confesso que já fiquei tonto de tanto olhar este código, mas não consegui evoluir.

Peço a ajuda de vocês para que juntos possamos resolver este bug do fortes, pois ele afeta tudo que utilizar o RLMemo e fizer o wordwrap.

Só lembrando que nem sempre o problema é observado, isso depende do texto que deve ser impresso, por isso já coloquei um caso em que o problema ocorre.

No mini projeto para demonstrar o problema eu adicionei um RLDraw1 com a mesma largura do RLMemo e como vocês poderão observar a borda do RLMemo obedece exatamente o mesmo tamanho do RLDraw, ou seja, a largura do RLMemo está correta.

Segue a imagem do projeto na IDE e o resultado da impressão.

O problema é relacionado ao código que calcula que o texto deve continuar na linha de baixo já que não irá "caber" dentro da área do componente. 

O arquivo erro_report.zip contém o mini projeto para reprodução do problema, ele está configurado para uma impressão em bobina, mas o problema ocorre também em impressão no formato A4 ou outros.

Muito obrigado pessoal, espero que tenha conseguido expor com clareza a situação.

Abraço a todos

Fabricio 
![na_ide](https://user-images.githubusercontent.com/37443696/37520328-5253f2fe-28fb-11e8-84fc-1f07811e94a6.jpg)
![na_impressora](https://user-images.githubusercontent.com/37443696/37520329-52778c00-28fb-11e8-95f4-e7ece2d7d78e.jpg)
[erro_report.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1819133/erro_report.zip)

**Comment by fabricio-controla** [comment]
pessoal, ninguém tem uma ideia sobre o problema?
isso afeta todo mundo que utilizar o RLMemo, vamos tentar resolver.
com o meu pouco conhecimento já esgotei as tentativas, mas juntos podemos multiplicar o conhecimento .

**Comment by juliomar** [comment]
Acho que não estão usando ou não tem o problema pois ninguém interagiu. 
mas diga o que tu alterou no fonte do Fortes pra tentar corrigir?

**Comment by fabricio-controla** [comment]
É claro que deve ser analisado para ser feito da melhor forma possível,
não sou especialista em componentes, só encontrei um jeito "alternativo"
pra resolver meu problema.
Fiz as alterações abaixo e resolveu o problema, se incluir isso no
repositório oficial acredito que cedo ou tarde irá resolver o problema
de mais alguém. 

alteração no arquivo RLMetaFile.pas 

function TRLGraphicSurface.TextWidth(const AText: String): Integer;
var
B: TBitmap;
begin
B := NeedAuxBitmap;
B.Canvas.Font.Assign(FFont);
/////////////////////////////////////////////////////////////////////////////////////////////
/// incluido por Controla para resolver o problema de estouro do limite
do compoente
/////////////////////////////////////////////////////////////////////////////////////////////
if fsItalic in B.Canvas.Font.Style = false then
begin
B.Canvas.Font.Style := B.Canvas.Font.Style + [fsItalic];
end;
/////////////////////////////////////////////////////////////////////////////////////////////
Result := B.Canvas.TextWidth(AText);
end; 

alteração no arquivo RLReport.pas 

function CanvasTextWidth(Canvas: TObject; const AText: string): Integer;
var
B: TBitmap;
begin
if Canvas is TRLGraphicSurface then
begin
Result := (Canvas as TRLGraphicSurface).TextWidth(AText);
end
else if Canvas is TCanvas then
begin
/////////////////////////////////////////////////////////////////////////////////////////////
/// incluido por Controla para resolver o problema de estouro do limite
do compoente
/////////////////////////////////////////////////////////////////////////////////////////////
B := NeedAuxBitmap;
B.Canvas.Font.Assign((Canvas as TCanvas).Font);
if fsItalic in B.Canvas.Font.Style = false then
begin
B.Canvas.Font.Style := B.Canvas.Font.Style + [fsItalic];
end;
/////////////////////////////////////////////////////////////////////////////////////////////
Result := B.Canvas.TextWidth(AText);
end
else
begin
Result := 0;
end;
end; 

Em 11/07/2020 20:43, Juliomar Marchetti escreveu:

> Acho que não estão usando ou não tem o problema pois ninguém interagiu.
> mas diga o que tu alterou no fonte do Fortes pra tentar corrigir? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/fortesinformatica/fortesreport-ce/issues/179#issuecomment-657148355
[2]

**Comment by juliomar** [comment]
Suba um pull request caso queira contribuir com sua alteração
