### ISSUE TITLE
Access violation ao abrir form com FortesReport

### ISSUE THREAD

**Issue by tporto** [fortesinformatica/fortesreport-ce#181]
Olá!

Uso o Lazarus 1.8 no ambiente Linux 64x Ubuntu.

Criei um formulário de relatório com FortesReport e ao fazer a chamada do form tenho um ACESS VIOLATION, debugando retorna "IMPRESSORA NÃO ENCONTRADA", já instalei uma impressora virtual e mesmo assim continua o erro, já no windows funciona. O relatório é bem simples e fiz a chamada do form e Report.Preview();

O erro é disparado ao criar o form:

form := TForm.Create(Application);

**Comment by juliomar** [comment]
consegue anexar um simples projeto que rode no seu linux
também qual usa KDE, gnome etc?

**Comment by tporto** [comment]
É muito simples fazer o teste, basta adicionar o Report no form e clicar na pré-visualização que verá o erro. Testei no ubuntu, mint e manjaro.

**Comment by tporto** [comment]
![captura de tela de 2018-04-01 20 46 21](https://user-images.githubusercontent.com/4909952/38178688-53ce8248-35ee-11e8-83b4-a90cf403a792.png)

**Comment by juliomar** [comment]
vou precisar levantar uma VM linux pra testar.

**Comment by tporto** [comment]
Testei com a versão do SVN e funcionou, mas essa do GIT continua com problema.

**Comment by juliomar** [comment]
Versão do svn? não tem nenhum svn mantido agora é só no GIT 
tu não está falando de versão antiga do fortes?

**Comment by tporto** [comment]
@juliomar em um post no forum do acbr, o Daniel fala que pode ser usado tanto o GIT como SVN e postou os links de ambos. Mas como disse que posso está usando uma versão desatualizada, baixei essa via git e deu tudo certo.
