### ISSUE TITLE
POS-58

### ISSUE THREAD

**Issue by AAppelt** [fortesinformatica/fortesreport-ce#182]
Vinha utilizando a versão de 10/2017 sem problemas, atualizei e agora ao tentar imprimir em impressora POS-58(58mm) a impressão sai como a da foto abaixo, a impressão pdf sai normal.  
Voltando a versão do fortes, volta a imprimir normal.
![image](https://user-images.githubusercontent.com/32494269/37708126-4b5bfee6-2ce4-11e8-85b6-6519a19acd31.png)

**Comment by juliomar** [comment]
consegue anexar um projeto para que possamos usar de exemplo e se basear para fazer ocorrer o mesmo?

**Comment by AAppelt** [comment]
Boa tarde!
desculpa a demora, vou providenciar um projeto de exemplo e disponibilizo.
Obrigado.

**Comment by AAppelt** [comment]
Segue fonte de impresso testado com vários clientes.
[Mini Projeto Fortes.zip](https://github.com/fortesinformatica/fortesreport-ce/files/2036755/Mini.Projeto.Fortes.zip)

**Comment by AAppelt** [comment]
Alguma idéia ou solução mesmo que temporária para este caso?

**Comment by juliomar** [comment]
O problema maior é conseguir reproduzir sem a impressora. ela é xingling? qual o fabricante?
