### ISSUE TITLE
Janela de Diálogo para salvar o relatório em PDF desaparece e tela fica travada

### ISSUE THREAD

**Issue by alexandrewindel** [fortesinformatica/fortesreport-ce#183]
Olá...Estou tendo um problema na hora de visualizar um relatório e imprimir ele como Microsoft PDF Print. Na hora de salvar, se eu clicar no relatório, a janela de diálogo desaparece e a tela fica travada. 

Recursos técnicos que estou usando:
- Ferramenta de linguagem de programação: Delphi 10 Seatle
- Sistema Operacional: Windows 10 Professional
- Versão do Fortes Report: FortesReport Community Edition 4.0 VCL

Passos para reprodução: 
1- Visualizar o relatório e clicar no botão Imprimir. Selecionar no tipo da impressora "Microsoft Print to PDF". (Imagem1.png)
![imagem1](https://user-images.githubusercontent.com/37911908/38107383-2a125f48-3368-11e8-8de5-38b7d0f39995.png)

2- Uma caixa de diálogo abrirá para selecionar o local onde deseja salvar o PDF. (Imagem 2)

![imagem2](https://user-images.githubusercontent.com/37911908/38107440-59da2f76-3368-11e8-942c-2877265f780a.png)

3- Não clicar nem em salvar e nem em cancelar. Clicar em qualquer local fora da caixa de diálogo. A janela desaparecerá e a tela ficará travada, impedindo que feche o relatório ou realize uma outra opção. (Imagem3.png)

![imagem3](https://user-images.githubusercontent.com/37911908/38107536-9e9d8068-3368-11e8-963e-84eb05fbd140.png)

**Comment by juliomar** [comment]
consegue com algum dos exemplos ocorrer o mesmo problema?
ou anexar um projeto como exemplo

**Comment by alexandrewindel** [comment]
sim...estou anexando um exemplo bem básico, onde tenho no formulário um botão com o rótulo "imprimir". É só clicar no botão e conseguirá reproduzir os passos acima. Junto com o anexo, estou enviando também o arquivo do programa compilado (*.exe).

[ProjectoFortes.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1868796/ProjectoFortes.zip)

**Comment by juliomar** [comment]
Testei aqui seu exe e seu fonte e não ocorreu oproblema
porque não usa direto o filtro PDF e salva sem usar essa impressora local
