### ISSUE TITLE
Ao imprimir o relatório em PDF aparece a mensagem "printer is not currently printing"

### ISSUE THREAD

**Issue by alexandrewindel** [fortesinformatica/fortesreport-ce#184]
Estou tendo um problema na hora de visualizar um relatório e imprimir ele como Microsoft PDF Print. Na hora de salvar, se eu esperar 1 minuto com a caixa de diálogo aberta e depois clicar em cancelar, mostra a seguinte mensagem "printer is not currently printing"

Recursos técnicos que estou usando:

Ferramenta de linguagem de programação: Delphi 10 Seatle
Sistema Operacional: Windows 10 Professional
Versão do Fortes Report: FortesReport Community Edition 4.0 VCL
Passos para reprodução:

1- Visualizar o relatório e clicar no botão Imprimir. Selecionar a impressora "Microsoft Print to PDF" e clicar em OK. 

![imagem1](https://user-images.githubusercontent.com/37911908/38109023-12791f70-336d-11e8-8d38-5fc4ef6a6e8a.png)

2- Uma janela de diálogo abrirá para salvar o local onde o pdf será impresso. 

![imagem2](https://user-images.githubusercontent.com/37911908/38109066-44e19eb0-336d-11e8-98b8-1f38cc040d07.png)

3- Aguardar aproximadamente 1 minuto com a janela de diálogo aberta e clicar em cancelar. Irá exibir uma mensagem "printer is not currently printing". 

![imagem3](https://user-images.githubusercontent.com/37911908/38109167-a5984cae-336d-11e8-9af4-649db4500f4e.png)

**Comment by juliomar** [comment]
não é do mesmo problema que já foi postado?
anexe um projeto de exemplo

**Comment by alexandrewindel** [comment]
O erro é diferente, nesse caso agora eu cancelei a impressão. Também anexando o projeto de exemplo para reproduzir o erro.

[ProjectoFortes.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1868802/ProjectoFortes.zip)

**Comment by alexandrewindel** [comment]
Boa tarde...vocês conseguiram reproduzir o erro mencionado acima? Existe possibilidade de haver alguma solução?

**Comment by lcalice** [comment]
Bom dia... Estou tendo o mesmo problema... Descobriram alguma solução?

**Comment by juliomar** [comment]
Tente trocar essa impressora de PDF padrão ou usem o filtro PDF para gerar o arquivo
