### ISSUE TITLE
Implementar segunda via de Pedido já pronto.

### ISSUE THREAD

**Issue by VitorGSilva** [fortesinformatica/fortesreport-ce#186]
Prezdos, boa tarde!

Desenvolvi um pedido de vendas a um cliente que a principio utilizaria uma lx300 com formulário continuo 2 vias (conforme exemplo anexo), só que agora mudou de ideia. Utilizará uma impressora por computador e gostaria que saísse 2 vias por padrão (via estabelecimento e via cliente). 

Minha dúvida é: com base no exemplo anexo, qual a forma mais fácil e rápida de aplicar a segunda via ?

Se possível vocês teriam o endereço ou arquivo de help do Fortes?
Procurei, mas não encontrei nada..
[FrmTesteImpressao.zip](https://github.com/fortesinformatica/fortesreport-ce/files/1886520/FrmTesteImpressao.zip)

**Comment by juliomar** [comment]
Não tem no projeto arquivo de Help.
quem sabe futuramente exista algo disponível

**Comment by VitorGSilva** [comment]
Obrigado pelo retorno juliomar..

**Comment by marcioarp** [comment]
Bom dia Vitor, estou com problema parecido, você conseguiu resolver?

**Comment by juliomar** [comment]
Ai quem vem uma coisa se tem que imprimir duas vias e é a mesma coisa chama duas vezes a impressão.
acho que é mais do software de vocês do que tentar modificar a forma que o componente trabalha
