### ISSUE TITLE
Impressão pelo Fortes sai na bandeija errada na impressora Samsung

### ISSUE THREAD

**Issue by FFTobias** [fortesinformatica/fortesreport-ce#187]
Boa tarde.

Estamos tendo um problema com a impressora Multifuncional Samsung ProXpress SL-M4070FR Laser.
Esta impressora possui duas bandejas na qual o cliente usa a de cima com folha serrilhada (manual) para impressão de recibos e a debaixo (bandeja) com folha normal.
No Windows, nas impressoras disponíveis aparecem as duas (Samsung(manual) e Samsung(bandeja1) porém na hora da impressão com o FORTESREPORT mesmo escolhendo a opção(Samsung MANUAL) a impressão sai na bandeja 1(que é a debaixo).

**Comment by juliomar** [comment]
Não tenho a impressora pra testar e entender.
se conseguir debugar os fontes e entender o que ele está fazendo para essa impressora e depois trazer alguma coisa aqui pra discutirmos e entender
