### ISSUE TITLE
Quebrar linhas no componente TRLAngleLabel

### ISSUE THREAD

**Issue by ALOISIO1911** [fortesinformatica/fortesreport-ce#188]
Bom dia,

Tenho um trabalho para executar, onde o nome das matérias escolares aparecem no relatório num ângulo de 90º. Porém algumas matérias têm um nome muito longo, fazendo com que apareçam cortados qdo impressos, como por exemplo: LÍNGUA ESTRANGEIRA MODERNA INGLÊS. Eu precisaria que existisse uma propriedade que permitisse ao componente quebrar o texto e N linhas, tal qual se faz com o TQRLabel e o TQRDBText do QuickReport no delphi, quando usamos a propriedade WORDWRAP como TRUE.

Fico no aguardo.

**Comment by juliomar** [comment]
Olá. que lembro não tem no componente
mas se quiser tentar implementar e enviar ou até mesmo uma ideia é tu saber o tamanho e quebrar o texto antes de colocar no componente pode ser que funcione
