### ISSUE TITLE
Atalho para a o botão imprimir no Preview

### ISSUE THREAD

**Issue by DavilaJunior** [fortesinformatica/fortesreport-ce#189]
Prezados,

Durante o processo de migração dos meus sistemas para a ferramenta Lazarus estou usando o Fortes Report para gerar os relatórios, todas as outras ferramentas que eu usava tinha esse atalho para acionar o botão de imprimir, em consequência disso meus clientes me solicitaram esse recurso.

Implementei no FormKeyDown da RLPreviewForm, mas gostaria de saber se é possível que este recurso seja atualizado no repositório e disponibilizado a todos os usuários.

Obrigado.

**Comment by juliomar** [comment]
Bom  deixarei aqui o comentário para fazer um fork dos fontes e enviar o pull request.
