### ISSUE TITLE
Corrigir Instalador para instalar liso no delphi 2006

### ISSUE THREAD

**Issue by farnetani** [fortesinformatica/fortesreport-ce#190]
**VER180 = delphi 2006**

Substituir Linhas: **779, 1397, 1431**
`RawBytes: {$IfDef VER180}AnsiString{$Else}RawByteString{$EndIf};`

Substituir Linhas: **1441**
`Result := {$IfDef VER180}String(RawBytes){$Else} UTF8ToUnicodeString(RawBytes){$EndIf};`

Fazendo isso, a instalação foi perfeita!

**Comment by juliomar** [comment]
Olá é possível você fazer um fork, aplicar as mudanças sugeridas e efetuar um pull request para que possa ser validado?
