### ISSUE TITLE
Exemplo de envio do relatório por e-mail

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#191]
Olá...

Já pesquisei exaustivamente na internet um exemplo sobre como enviar o relatório exibido no Preview por e-mail, com aquele botão ENVIAR PARA, mas não achei nada concreto.

Muitos comentam sobre um tal exemplo sendmail.zip, mas não consigo achá-lo. Parece que todos os fóruns oficiais do Fortes Report que o mencionavam deixaram de existir.

Outra dica foi colocar um RLPreviewSetup1 e programar o envio em seu evento OnSend, até consegui, mas tive alguns inconvenientes.

1 - Primeiro eu tentei programar o envio para apenas para UM único relatório, no OnSend do RLPreviewSetup1 eu programei para salvar um PDF do relatório em questão, enviar por e-mail (componente ACBrMail) anexando o PDF criado e depois excluir o PDF. Até aí tudo certo, o problema é que eu descobri que TODOS os relatórios passam a enxergar o código configurado nesse RLPreviewSetup1, e o código da geração do PDF é específica para esse relatório que está em um form específico. Esse comportamento do RLPreviewSetup1  de todos enxergarem ele e seus eventos é normal?

2 - Após constatar que todos os relatórios estavam enxergando o RLPreviewSetup1 e todos os seus eventos, resolvi colocar o mesmo no meu Data Module e criar um código universal de envio de e-mail. Até aí tudo bem, o problema é novamente na geração do PDF, pois cada relatório está em um Form diferente, portanto como fazer um código para gerar o PDF independente do relatório que acionar o OnSend do RLPreviewSetup? Algo como "RLQualquerUm.SaveToFile(ExtractFilePath(Application.ExeName) + 'relatorio.pdf');"

**Comment by juliomar** [comment]
Anexe o projeto de exemplo pequeno para que possamos junto trabalhar nele e quem sabe arrumar uma solução.
e quem sabe até colocar na pasta de exemplos

**Comment by OsmarDeLuca** [comment]
em outras palavras ele e eu tambem gostaria de saber como saber qual foi o RLReport que chamou onsend já descobri que quem chama o Send é TRLPreviewForm
procedure TXXX.RLPreviewSetup1Send(Sender: TObject);
begin
   showmessage(Sender.ClassName);
mas como chegar ao RLReport que chamou o Preview que chamou o TRLPreviewForm?

**Comment by OsmarDeLuca** [comment]
RLPreview,   RLPreviewForm, RLReport, RLFilters, RLPDFFilter
