### ISSUE TITLE
Dúvida sobre os Filtros

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#192]
Olá...

Tenho duas dúvidas sobre filtros...

1 - Basta eu colocar somente um componente de filtro (RLPDFFilter1, RLXLSFilter1, etc) em qualquer form e o mesmo é visto por todos os RLReports, aparecendo assim no campo "Usar Filtro" da caixa de diálogo Salvar da Pré-Visualização. Esse comportamento é normal? Eu achava que tinha que colocar um componente de filtro em cada form que tivesse um RLReport, mas aí aparece vários filtros iguais no campo "Usar Filtro" da caixa de diálogo Salvar da Pré-Visualização.

2 - Na caixa Salvar da Pré-Visualização, sempre é sugerido o valor "Padrão" no campo "Usar Filtro" da caixa de diálogo Salvar da Pré-Visualização. Como posso sugerir o valor "Documento PDF"?

**Comment by resanches** [comment]
Também estou com essa dúvida de como deixar a opção "Documento PDF" padrão no momento de salvar o relatório. Nas versões antigas do Fortes, tinha  o componente RLSaveDialogSetup onde era possível apontar para o RLPDFFilter.

Alguém pode nos ajudar?

**Comment by juliomar** [comment]
Favor atualizar, reinstalar e testar o FilterDefault no RLReport

sobre os filtros notem que é pensado em por exemplo ter um filter pronto para cada local, tenho um que vai exportar e ter nome e titulo para estoque e outro lá para o financeiro.
no caso quando não se faz necessário vários sugiro usar um DM e colocar um único no sistema todo
