### ISSUE TITLE
Instalar fortesreport no delphi 10.2.3 Tokio - Starter

### ISSUE THREAD

**Issue by RobsonCatunda** [fortesinformatica/fortesreport-ce#193]
Não consigo instalar o fortesreporter no delphi starter 10.2.3 Tókio.
Baixei pelo github. O instalador diz que a instalação foi bem sucedida, e o caminho da libd25 está lá em tools->options->libraby->library path.
Porém a paleta dos componentes não aparece.
Se tentar instalar pelo pacote dá erro na compilação.
Como resolvo?
![erro](https://user-images.githubusercontent.com/30703496/42361725-3e62b7e4-80c6-11e8-90c9-b18a5a08bc83.png)

![image](https://user-images.githubusercontent.com/30703496/42361586-a17f7e80-80c5-11e8-935d-c41e4eb241e4.png)

**Comment by juliomar** [comment]
Bom o instalador não funciona para o Starter!
tem que instalar vi pacote frce.dpk
confira a lista de componentes e remova e faça a instalação manual.

**Comment by RobsonCatunda** [comment]
Instalando com o dpk apresenta o erro da imagem que anexei anteriormente.
Eu já havia instalado o fortesreport logo após ter instalado o delphi. Mas quando fui instalar o ACBr ele não instalava. Dava tudo como ok mas não estava lá, não criava bpl nem arquivo algum.
Pesquisando, encontrei alguém com o mesmo problema, Nesse link:  https://www.projetoacbr.com.br/forum/topic/43897-instala%C3%A7%C3%A3o-acbr-delphi-tokio-1023/?tab=comments#comment-289329

Nele Juliomar responde que o problema é a versão do fortesreport e o DSILVA diz que deu certo.
Então vou fazer a mesma coisa. desinstalei o fortesreport mas não consegui mais reinstalar.
Já tentei via instalador e via dpk.
Existem uns rtl's na pasta do delphi mas o fortesreport não encontra, também não sei se são esses que ele procura. Na pasta de instalação do fortesreport não tem nenhum.
![image](https://user-images.githubusercontent.com/30703496/42397364-0a1f0048-813c-11e8-970b-a0d85a244568.png)

**Comment by juliomar** [comment]
Primeiro de tudo ao rodar a instalação do DPK no delphi starter o mesmo está faltando as unit scope names por isso dos erros se for pelo dpk.
outra coisa ele deve gerar o arquivos dcu, dcp e bpl  em um local único e adicionar path no library do delphi antes do ACBr
sugiro ver o último code rage onde mostro algumas coisas em video
