### ISSUE TITLE
Dúvida referente ao Fortes para D5 + XLSFilter

### ISSUE THREAD

**Issue by leandroguilhrm** [fortesinformatica/fortesreport-ce#194]
Existe alguma versão do Fortes para o Delphi 5 que já tenha a propriedade "foOneSheetOnly" no XLSFilter?

Uso uma versão para o Delphi 7 que já tem essa opção mas não encontrei em nenhum lugar uma versão para o Delphi 5 que também tenha essa opção.

Obrigado!

**Comment by juliomar** [comment]
boa tarde
não foi feito o suporte a essa versão do delphi?
