### ISSUE TITLE
Error exporting XLS (Linux 64 bits)

### ISSUE THREAD

**Issue by esimat** [fortesinformatica/fortesreport-ce#198]
I have had some troubles when exporting to xls in 64 bits systems (access violation). I have solved applying attached diff, but I'm not sure if this changes can affect another parts or produce new errors.
[RlXlsFilter.diff.zip](https://github.com/fortesinformatica/fortesreport-ce/files/2514481/RlXlsFilter.diff.zip)

I'm using Lazarus (SVN version) with fpc 3.0.4

**Comment by dopidaniel** [comment]
I did some changes based on yours and this previous issue

https://github.com/fortesinformatica/fortesreport-ce/commit/d6e455f545e35c4b7c4f36a1275c4f1a1343cf3b

Please try the the Patch below

[FortesReportCE_Source.zip](https://github.com/fortesinformatica/fortesreport-ce/files/2520771/FortesReportCE_Source.zip)

**Comment by esimat** [comment]
Great! Patch applied and filters (xls and xlsx) works ok

**Comment by dopidaniel** [comment]
Patch applied
