### ISSUE TITLE
PDF em branco

### ISSUE THREAD

**Issue by elizeuandrade** [fortesinformatica/fortesreport-ce#2]
Bom dia,

utilizo o delphi 7 com o fortes na versao 3.72B, e ao gerar salvar o pdf apenas em alguns casos o PDF  ficou todo em branco, sem absolutamente nada visivel na tela. a aplicacao ja gerou mais de 30000 pdf, apenas 345 apresentaram este problema, estou analisando se algum caracter especial ou sequencia especifica pode ter causado este erro. Analisei um pdf "em branco" a partir de um editor de texto e constatei que todos os dados estão presentes porem com as "posicoes" negativas. A titulo de testes alterei manualmente as posicoes e alguns dados apareceram no visualizador de pdf. 
Na aplicacao utilizamos o report sem conexao direta com banco, apenas preenchendo os labels e memo´s, nao alteramos posicao em run-time nunca. O report nao tem pré-visualizacao antes de ser salvo para PDF. Nao consegui reproduzir o problema em testes simulados, mas ele continua ocorrendo em producao. Dentro do PDF "em branco" abrindo em um editor de texto, fora as posicoes incorretas, notei que a linha onde indica o LastPage nao foi substituido pelo valor real, ficando desta forma: 
"({LastPageNumber}) Tj"
em um pdf normal com duas paginas ficaria desta forma: "(2) Tj"

**Comment by marciomartins** [comment]
Desculpe a demora, se o problema persistir na versão atual, favor reabrir o chamado ou me contactar por e-mail.
