### ISSUE TITLE
RLGroup não pára de quebrar página

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#20]
Olá a todos,

Após atualizar o meu componente do 3.72 para o 4, todos os relatórios que possuo RLGroup passam a quebrar a página após o mesmo, mesmo com a opção PageBreaking como pbNone. Uso o delphi 7.

Alguém sabe do que se trata?

**Comment by marciomartins** [comment]
Vou verificar, mas se puder passar um protótipo simulando o problema, agiliza a solução.

Obrigado.

**Comment by bnobre** [comment]
Olá amigo,

Grato pela sua pronta ajuda.

Segue em anexo a unit que consta o relatório em si. Você só receberá erros
quanto as conexões a base de dados e tal, mas o relatório todo e a forma
como estou fazendo está ai. Se achar necessário, monto um projeto com base
de dados específico para esse teste e te mando, pois o problema ocorre
também em projetos novos.

Mando em anexo o resultado final do relatório (preview) em PDF, para
analisar o que acontece. Se reparar ele quebra a página após o fim do
RLGroup, ao invés de dar continuidade como fazia antes. Atente que a opção
PageBreaking está pbNone. Se tirar o RLGroup ele NÃO quebra, que é o que
deveria fazer

PS: Está em Delphi 7

Em 8 de setembro de 2015 18:03, Marcio Martins <notifications@github.com>
escreveu:

**Comment by bnobre** [comment]
Olá, sou novo aqui no Git. 

Respondi por e-mail e não sei se recebeu meus anexos. Como não vejo como anexar arquivos diferentes de imagens por aqui, segue link dos arquivos via Mega, caso precise.

https://mega.nz/#!zV8BlBKT!pfD5fmNKdPkzopXV0gzYd652Juw-L6d-u6hArF7tp-A
https://mega.nz/#!3BsWUKhQ!OpuiSb5s-HFFHyR8kr8c3TVEMDmQ9BrilFbnGhLcy40

Abraços

**Comment by marciomartins** [comment]
Você está usando a última versão disponível aqui?

**Comment by bnobre** [comment]
Estou usando a versão que segue no link abaixo:
https://mega.nz/#!6AsjALTb!hbTik1BiTvPEOrOZn9q--bgqF7Tup8qsobY44Op_-aw

Realizarei o download do componente agora e efetuarei a instalação para ver se corrige o problema. Um instante

**Comment by bnobre** [comment]
Olá amigo, tentei instalar o pacote baixado há pouco em meu Delphi 7. Estou recebendo o seguinte erro em anexo.

![erro_fortes](https://cloud.githubusercontent.com/assets/14187449/9764979/3e1a88e4-56e8-11e5-8521-c59c68645958.JPG)

Na verdade, quando tentei efetuar a instalação semanas atrás do Fortes 4 em lugar do 3.72, recebi o mesmo erro. Precisei da versão 4.0 para utilizar em conjunto com os componentes de DANFE do ACBr, que foram projetados sobre tal versão. No fórum do ACBr, descobri não ser o único com tal problema no Delphi 7, segue link abaixo:

http://www.projetoacbr.com.br/forum/topic/22849-problema-na-instala%C3%A7%C3%A3o-do-fortes-report/?page=2

O Rafael Dias, no mesmo tópico, postou dia 19-06-15 o instalador com as correções comentadas no tópico em https://github.com/rftd/fortesreport-ce. E é esse que estou usando.

A questão é que esse do Rafael está dando esse problema de quebrar a página no RLGroup, e o mantido aqui no Git oficial ainda está apresentando tal erro na instalação.

**Comment by bnobre** [comment]
Olá amigo,

Segui um procedimento no fórum do ACBr e a princípio corrigiu esse erro do "Undeclared identifier: TRect"... Fiz o seguinte, tirei o Sources do Library Path, deixando apenas o diretório Win32_D7_vcl que consta em Binary. Também copiei para o Win32_D7_vcl o arquivo RLReport.res do Source. Com isso finalmente consegui instalar com sucesso usando o componente do próprio Git oficial. Fiz o procedimento correto???

Após isso comecei recebera seguinte mensagens nos meus relatórios: "Property UnlimitedHeight does not exist". Simplesmente ignorei, salvei e agora está tudo funcionando PERFEITAMENTE.

Sabe do que seria essa mensagem e o porque de ter ocorrido tal erro?

De qualquer forma agradeço a atenção e a ajuda.

Abraços

**Comment by marciomartins** [comment]
Quanto ao problema do RLGroup, resolveu?

**Comment by bnobre** [comment]
Sim amigo. Depois dos procedimentos que citei funcionou.

2015-09-09 15:20 GMT-03:00 Marcio Martins <notifications@github.com>:
