### ISSUE TITLE
RlRichtext component does not have BIDI mode for UTF8 text and does need sometime to hold some text lines

### ISSUE THREAD

**Issue by DeveloperAMK** [fortesinformatica/fortesreport-ce#200]
Dear Sir all, 

thank you very much for you great efforts indeed. I have some issues with RichText and other text components that do not have BIDImode. 

BIDI  Allows the text to start from right to left. if the text is justified and half a line was remained, the half line will come from the right to left.

I have attached a sample project which shows the problem.

Another issue is that If I try t assign some more lines, it takes some time to fit them inside the Richtext component.

Thank you very much indeed
[richText_test.zip](https://github.com/fortesinformatica/fortesreport-ce/files/2653145/richText_test.zip)

**Comment by juliomar** [comment]
thank you. I saw your example and it really has this problem, did you manage to change the fonts so that it gets some solution? if you want to send a pull request

**Comment by DeveloperAMK** [comment]
Thanks,

I tried, changing the font type does not help.

cheers
