### ISSUE TITLE
Issue cloning TRLPolygonObject

### ISSUE THREAD

**Issue by cdvdt** [fortesinformatica/fortesreport-ce#201]
I found an issue when cloning a TRLPolygonObject, both original and copy are printed at same place, even when the copy is displaced, i sent a patch to fix it.

[RLMetaFile.pas.diff.txt](https://github.com/fortesinformatica/fortesreport-ce/files/2700228/RLMetaFile.pas.diff.txt)

**Comment by dopidaniel** [comment]
Looks like ok... Can you please provide a Pull request for that ?
