### ISSUE TITLE
Change Proposal on TRLCustomReport

### ISSUE THREAD

**Issue by cdvdt** [fortesinformatica/fortesreport-ce#202]
I'm working on printing multiple reports in the same page and needed marking the prepare method from TRLCustomReport as virtual so i can implement my own behavior over this method, it being called from the current implementation of preview and print mechanisms. I'm sending a patch for it.
[RLReport.pas.diff.txt](https://github.com/fortesinformatica/fortesreport-ce/files/2700275/RLReport.pas.diff.txt)

**Comment by dopidaniel** [comment]
Looks like ok... Can you please provide a Pull request for that ?
