### ISSUE TITLE
Codificação de caracteres na unit RLConsts.pas

### ISSUE THREAD

**Issue by maico-smaniotto** [fortesinformatica/fortesreport-ce#204]
Qual a possibilidade de utilizar UTF-8 na unit RLConsts? 
Eu estava fazendo algumas modificações, adicionando novas mensagens, mas percebi que vários caracteres estão quebrados (principalmente no idioma Russo) e não consegui recuperá-los. Olhando nos logs percebi que a unit em questão teve a codificação alterada para CP-1252. Qual é o motivo disso ter sido feito? Penso que, para suportar também o alfabeto cirílico, seria obrigatório utilizar um padrão unicode.

**Comment by dopidaniel** [comment]
O motivo de usar ANSI, é manter o suporte ao Delphi 7
