### ISSUE TITLE
Alterar o tamanho da fonte impressa na mensagem Promocional do Cupom Fiscal

### ISSUE THREAD

**Issue by Jean1dev** [fortesinformatica/fortesreport-ce#206]
O fortes tem suporte a essa alteração?
De acordo com a resposta que tive no forum " for em Fortes, tem que editar o dfm, se for em fast tem que alterar o fr3 e se for ESC POS, tem que ver se ele suporta a alteração.﻿﻿"

Mais Informações no Topico do Forum do AcBr [https://www.projetoacbr.com.br/forum/topic/49122-alterar-o-tamanho-da-fonte-impressa-na-mensagem-promocional-do-cupom-fiscal/?tab=comments#comment-324507](url)

**Comment by dopidaniel** [comment]
Os relatórios do ACBr, já possuem vários Labels que ajustam o tamanho da fonte, quando necessário...
Veja por exemplo o método: TACBrSATExtratoFortesFr.DiminuirFonteSeNecessario
