### ISSUE TITLE
Problema na renderização do código de barras bcCode128C no Linux

### ISSUE THREAD

**Issue by fbafabio** [fortesinformatica/fortesreport-ce#207]
Ao renderizar um código de barras bcCode128C no Linux com 44 caracteres (tamanho de uma chave de NFe) e AutoSize ON a renderização ocorre de forma errônea não sendo possível realizar a leitura do código, porém alterando o a propriedade  AutoSize para OFF e modificando o Width de 286 (valor definido pelo AutoSize) para 289﻿ a renderização ocorre corretamente conforme pode ser visto na imagem

![bccode128c](https://user-images.githubusercontent.com/23403590/52447794-fd46dd00-2b18-11e9-8697-9949b7c8d6d4.jpg)

**Comment by juliomar** [comment]
Show Fábio.
sugere alguma correção ou mudança ao fontes? consegue mandar um pull request com elas
