### ISSUE TITLE
Impressao Cortando

### ISSUE THREAD

**Issue by EduardoMacena** [fortesinformatica/fortesreport-ce#208]
Quando imprimo um relatório que esta na largura 80mm esta cortando o topo, a esquerda e direita, vi uma resposta dizendo que poderia ser o tamanho da fonte do windows, só que esta o tamanho padrão, alguém poderia me ajudar!

**Comment by juliomar** [comment]
Zoom do windows chegou a verificar?
também tentou configurar a impressora padrão do windows.
