### ISSUE TITLE
Instalar Win64

### ISSUE THREAD

**Issue by igorbastosib** [fortesinformatica/fortesreport-ce#209]
Estou tentando compilar para Win64 mas estou recebendo erros.
Rad Studio 10.3.1
Versão do Fortes Report: 460

Compila, instala e roda normalmente para Win32 (tanto no instalador qnt no Package), mas ao tentar compilar Win64 dá erro no Instalador (https://textuploader.com/1d5ih) e ao tentar compilar manualmente o package percebi que não possui plataforma Win64 (http://666kb.com/i/e3acqbgukev9m8dfk.jpg).

Qual forma correta de instalar o FR CE para Win64?

Desde já, agradeço!

**Comment by igorbastosib** [comment]
Acho que consegui: 
removi tds dependências, 
apaguei a pasta, 
baixei de novo, 
abri o PKG pelo delphi, 
adicionei o Win64, 
salvei, 
fechei tudo, 
abri o instalador, 
instalei o Win32, 
adicionar a pasta Trunk\Source ao Library Win64, 
comentei um código que dava erro (https://textuploader.com/1d17b)
e deu certo

**Comment by dopidaniel** [comment]
obrigado por reportar a solução.... Fechando
