### ISSUE TITLE
FortesReport-CE BDS2006

### ISSUE THREAD

**Issue by Elias-Diagnosys** [fortesinformatica/fortesreport-ce#21]
Boa tarde!
Eu não encontrei o FortesReport-CE (versão compatível com o ACBr trunk 2) para o Borland Developer Studio 2006, teria como me enviar os arquivos ou dizer onde posso encontrá-los? 

Desde já, obrigado pela atenção.

**Comment by marciomartins** [comment]
Elias, boa tarde.
Realmente ainda não temos o pacote para Borland Developer Studio 2006, se você puder criar a partir de um outro pacote e nos enviar, agradecemos e logo disponibilizamos para todos.

Os fontes mais recentes são estes.

**Comment by Elias-Diagnosys** [comment]
Tentei e não consegui, vou tentar outra solução. Obrigado.
