### ISSUE TITLE
DisplayMask não formata valores inteiros

### ISSUE THREAD

**Issue by guibverardi** [fortesinformatica/fortesreport-ce#211]
Quando alimento a propriedade DataFormula de um TRLDBText, e a coluna da query que recebe um valor NUMERIC, acaba recebendo um valor inteiro como por exemplo, "2,00", a mascara fica como na imagem em anexo. 

![Impressao](https://user-images.githubusercontent.com/46457332/57707304-c57e9280-763d-11e9-8150-5dfe9d76d940.png)

  Fiz uma análise e percebi que isso ocorre, pois dentro da unit RLReport na função ApplyMask ao analisar o "VarType(AValue) " (linha 8409) o tipo da Variant em um AValue como 2 é diferente de todas as opções analisadas no if, então ele acaba não formatando como número. Porém, analisando mais a fundo verifiquei que se alimentado a propriedade DataField ao invés de DataFormula, é chamada a função SmartGetFieldDisplayText, que está dentro da RLUtils, para talvez formatar o campo. Porém meu problema com essa função, é que existe uma verificação para ver se o Field é um TFloatField (linha 1099) e no meu caso o Field acaba sendo um TFMTBCDField então não recebe a formatação numérica neste caso também.

  Com isso, sugiro alterar a função SmartGetFieldDisplayText na linha 1099 para verificar se o campo é um TNumericField e não um TFloatField. Ou se alguém tiver alguma dica de configuração que eu não esteja usando, irei analisar.

**Comment by juliomar** [comment]
Por favor envia pra nos o pull request para validarmos
