### ISSUE TITLE
Fortes Report - Cópia Carbono

### ISSUE THREAD

**Issue by ednergassen** [fortesinformatica/fortesreport-ce#212]
Bom dia!

Estou com a mesma dificuldade que o colega postou no link abaixo:
https://github.com/fortesinformatica/fortesreport-ce/issues/114

A propriedade CarbonCopies realmente duplica o número de vezes que estou querendo gerar o recibo na mesma folha. No entando, a duplicação das bandas se dá em ordem, Ex: Tenho uma banda do tipo Header ela imprime duas vezes primeiro, para depois ser impressa o detalhe. Estou precisando que imprima a banda header primeiro, após o detalhe, e em seguida repita a operação, a fim de criar uma cópia do documento na mesma folha.

Desde de já agradeço a atenção!

Att,

Edner R. Gassen

**Comment by ednergassen** [comment]
Para relatório simples, onde todas as informações do mesmo conste dentro da banda detalhe, funciona, mas minha dificuldade é quando tenho válidos detalhes e footers.

**Comment by juliomar** [comment]
Por favor anexe um exemplo pequeno para podermos entender
