### ISSUE TITLE
Problema ao marcar "Range checking" nas opções do compilador/Runtime Errors

### ISSUE THREAD

**Issue by arvanus** [fortesinformatica/fortesreport-ce#213]
Ao marcar na opção Runtime Errors, Range Checking=True, o fortes dá o seguinte erro:
`[dcc32 Error] RLMetaVCL.pas: E1012 Constant expression violates subrange bounds`
nas seguintes linhas:
`    if ASource = succ(taCenter) then`
e
`    MetaTextAlignmentJustify: Result := succ(taCenter);`

Investigando o problema descobri o seguinte:
Internamente o Fortes usa o 
`TRLTextAlignment = (taLeftJustify, taRightJustify, taCenter, taJustify);`
Porém nestes métodos que dão erro, usa o 
`  TAlignment = (taLeftJustify, taRightJustify, taCenter);`

Pesquisando sobre o método succ, (http://www.delphibasics.co.uk/RTL.asp?Name=Succ), ele faz o seguinte:

> The Succ function increments an ordinal value, and returns this value.

Isso explica o erro em questão!
No caso, em vários locais temos seguinte código:
`ToMetaTextAlignment(TAlignment(Alignment))`, que transforma uma variável de 4 opções em outro tipo com apenas 3.

Não vou propor uma solução, pois ainda não revisei o suficiente o código do Fortes, mas se algum programador mais experiente no componente puder ajudar, a comunidade agradece :)
Imagino que teríamos que remover o TAlignment e usar apenas o TRLTextAlignment ou algo assim...

Relacionado com #140

**Comment by JanRoza** [comment]
Arvanus, EMBBlaster,

Thanks for putting me on the the right track.
I made some changes in RLMetaVCL.pas and now Fortesreport compiles okay in Lazarus Trunk with FPC 3.3.1.
Attached is the zipped modified RLMetaVCL.pas.

[RLMetaVCL.zip](https://github.com/fortesinformatica/fortesreport-ce/files/4150320/RLMetaVCL.zip)


Jan Roza

**Comment by juliomar** [comment]
Estamos verificando e logo vai subir uma correção para isso.
