### ISSUE TITLE
Impressão diferente na Laser e na Jato de Tinta

### ISSUE THREAD

**Issue by cefantacini** [fortesinformatica/fortesreport-ce#214]
Fiz um relatório usando o fortes, de meia página A4, na laser a impressão sai correta, porem na jato de tinta, distorce.

Vou postar duas imagens para ficar mais facil de entender.

Se alguém tiver alguma dica...

a parte do código que faz a configuração:
  if GE_MeiaFolha
  then
    begin
      RL.PageSetup.PaperSize := fpCustom;
      RL.PageSetup.Orientation := poPortrait;
      RL.PageSetup.PaperHeight := 297/2;
      RL.PageSetup.PaperWidth := 210;
      RL.Margins.TopMargin := 5;
      RL.Margins.BottomMargin := 5;
      LbDescricao.Font.Size := 8;
      LbQuantidade.Font.Size := 8;
      LbUnitario.Font.Size := 8;
      LbTotal.Font.Size := 8;
      MMProDesc.Font.Size := 8;
      LbProQuant.Font.Size := 8;
      LbProUnit.Font.Size := 8;
      LbProTot.Font.Size := 8;
      ProdColHead.Height := 16;
      ProdDetalhe.Height := 16;
    end
  else
    begin
      RL.PageSetup.PaperSize := fpA4;
      RL.PageSetup.Orientation := poPortrait;
      RL.Margins.TopMargin := 5;
      RL.Margins.BottomMargin := 5;
    end;

![Certo](https://user-images.githubusercontent.com/52102276/60043436-75600a80-9696-11e9-96de-4347bd3f5c05.jpeg)
![Errado](https://user-images.githubusercontent.com/52102276/60043438-75f8a100-9696-11e9-976b-8b153f520c51.jpeg)

**Comment by juliomar** [comment]
Que impressoras são? modelo marca? Anexe um projeto pequeno mostrando o problema e também versão do delphi/lazarus usado

**Comment by arvanus** [comment]
Posso estar redondamente enganado, mas tem cara de a impressora estar configurada uma como retrato, e a outra como paisagem
Dá uma conferida se não pode ser isso
