### ISSUE TITLE
problem with fortes memo

### ISSUE THREAD

**Issue by beba1992** [fortesinformatica/fortesreport-ce#215]
execuse me 
I am using fortes reports .. when I transport the text from a form memo to Rlmemo the text is out of the bounds of the RLMemo 
the instruction I have used is:
Report.RLmemo.Lines := Form. memo.lines 
so the text in the fortes memo is out of the bounds :(
how to solve it?

**Comment by dopidaniel** [comment]
Try
Report.RLmemo.Lines.Text := Form. memo.lines.Text

**Comment by beba1992** [comment]
> Try
> Report.RLmemo.Lines.Text := Form. memo.lines.Text

I've tried it but the problem still appear unfortunately :(

**Comment by juliomar** [comment]
did the autosize of him and the band arrive?

**Comment by juliomar** [comment]
#217
