### ISSUE TITLE
problem with fortes memo bounds  

### ISSUE THREAD

**Issue by beba1992** [fortesinformatica/fortesreport-ce#217]
Execuse me 
I am using fortes reports .. when I transport the text from a form memo to Rlmemo or when I take text from db to RLDBMemo the text is out of the bounds of the Memo 
the instruction I have used is:
Report.RLmemo.Lines := Form. memo.lines 
so the text in the fortes memo is out of the bounds :(
how to solve it? 

![memo ](https://user-images.githubusercontent.com/52370597/60873213-a3b91a80-a23e-11e9-9f99-86a8616c69ed.jpg)

**Comment by dopidaniel** [comment]
When do you attribute the Text ?
Do you use a "BeforePrint", event ?

**Comment by beba1992** [comment]
No I am in the normal form using the Instruction
Report.RLmemo.lines = Form.Memo.Lines
