### ISSUE TITLE
RLPrintDialog.pas missing button translation

### ISSUE THREAD

**Issue by JanRoza** [fortesinformatica/fortesreport-ce#218]
Hi,
I noticed that the Propriedades button in the PrintDialog is not translated when using other language than Portugees. I already added the missing statement in the RLPrintDialog.pas file.
Maybe this unit can be included in the next update.

Regards
Jan Roza
[RLPrintDialog.zip](https://github.com/fortesinformatica/fortesreport-ce/files/3432252/RLPrintDialog.zip)

**Comment by dopidaniel** [comment]
Please update your sources...
note line 705 of RLPrintDialog.pas... there is a fix for translation of the same component...
