### ISSUE TITLE
Lazarus 2.0.5 problem

### ISSUE THREAD

**Issue by patyigit** [fortesinformatica/fortesreport-ce#219]
Hi everybody !

I've been trying to migrate from Lazarus 1.8.5 to a newer one for a while, but I still have some minor issues. Today, for example, I tried 2.0.5, which worked fine until a report was printed. The application did nothing here without any error message. In the editor, a preview window of FortesReport CE indicates an Access violation error. Can anyone tell me that Lazarus 2.0.5 Linux 64bit is really a problem with FortesReport CE ? The FortesReport CE was installed from OPM.

Xubuntu 18.0.4 LTS 64bit, FPC 3.0.5, Lazarus 2.0.5 64bit installed with FpcUpDelux (FPC Fixes 3, Lazarus Fixes 2).

**Comment by dopidaniel** [comment]
I'm not sure if Fortes Report CE is updated on OPM...
Please try with sources from GitHub

**Comment by patyigit** [comment]
Thanks ! You're right, removed from the Lazarus IDE, downloaded from GitHub, installed and yes, everything works as expected ! I am writing to OPM Admin to update the package ...
