### ISSUE TITLE
Instalação XE2

### ISSUE THREAD

**Issue by nazarenoneto** [fortesinformatica/fortesreport-ce#22]
[DCC Error] RLDraftFilter.pas(597): E2033 Types of actual and formal var parameters must be identical

{$if CompilerVersion >= cvDelphiXE3}
function LinePrinterStart(const PrnName, DocName: String): NativeUInt;
{$else}
function LinePrinterStart(const PrnName, DocName: String): Cardinal;
{$ifend}
var
  di: TDocInfo1;
begin
  FillChar(di, SizeOf(di), 0);
  di.pDocName := PChar(DocName);
  di.pOutputFile := nil;
  di.pDatatype := 'RAW';
  OpenPrinter(PChar(PrnName), Result, nil);
  StartDocPrinter(Result, 1, @di);
  StartPagePrinter(Result);
end;

Resolvido fazendo a seguinte alteração:

{$ifdef DELPHIXE2_UP or FPC}
function LinePrinterStart(const PrnName, DocName: String): NativeUInt;
{$else}
function LinePrinterStart(const PrnName, DocName: String): Cardinal;
{$endif}
var
  di: TDocInfo1;
begin
  {$ifndef FPC}
  FillChar(di, SizeOf(di), 0);
  di.pDocName := PChar(DocName);
  di.pOutputFile := nil;
  di.pDatatype := 'RAW';
  OpenPrinter(PChar(PrnName), Result, nil);
  StartDocPrinter(Result, 1, @di);
  StartPagePrinter(Result);
  {$else}
  //note: implement RLDraftFilter.LinePrinterStart
  {$endif}
end;

**Comment by marciomartins** [comment]
Bom dia Nazareno, vou verificar e já retorno.
Obrigado.

**Comment by marciomartins** [comment]
Ajustado. Favor atualizar.
Obrigado.

**Comment by nazarenoneto** [comment]
Obrigado!
