### ISSUE TITLE
Patch: German constants for FortesReport-CE

### ISSUE THREAD

**Issue by marsupilami79** [fortesinformatica/fortesreport-ce#220]
Hello,

I translated FortesReport-CE to German. The necessary changes are attached to this post.
Best regards,

Jan

[RLConsts-German.pas.patch.txt](https://github.com/fortesinformatica/fortesreport-ce/files/3590013/RLConsts-German.pas.patch.txt)

**Comment by dopidaniel** [comment]
patch applied
