### ISSUE TITLE
Patch: TRLPrinterWrapper.ExecuteSetup didn't work + reapplying printer settings before printing

### ISSUE THREAD

**Issue by marsupilami79** [fortesinformatica/fortesreport-ce#221]
Hello,

The function TRLPrinterWrapper.ExecuteSetup didn't work correctly for me now for quite some time. Settings didn't get applied to the printer.
Also I had the problem that somehow printer settings got destroyed between printing documents and had to be set again and again.

The attached patch adresses these both issues - although it might not be perfect.

Best regards,

Jan
[printer settings.patch.txt](https://github.com/fortesinformatica/fortesreport-ce/files/3590037/printer.settings.patch.txt)

**Comment by dopidaniel** [comment]
After a quick verification... looks like it's not compatible with Lazarus/FPC (and Linux)...

Did you test on Lazarus/FPC, environment ?

**Comment by marsupilami79** [comment]
You are right. These things only do work on Delphi/Windows. They will not work with Lazarus and probably are not needed there. So I assume that these changes need to be surrounded by $IFNDEF FPC like the original implementation of TRLPrinterWrapper.ExecuteSetup was?

**Comment by dopidaniel** [comment]
Yes... that will be good enough to keep FPC compiling compatibility...

**Comment by dopidaniel** [comment]
patch applied
