### ISSUE TITLE
Edição de um relatório no TRLPreview em run-time

### ISSUE THREAD

**Issue by lsjack93** [fortesinformatica/fortesreport-ce#223]
Estou tentando utilizar a opção de Editing que o TRLPreview tem, mas quando habilito só cria uns quadradinhos em volta do texto, não me permite editar, precisa de mais alguma configuração pra isso funcionar?

**Comment by juliomar** [comment]
Acho que nunca funcionou.
mas caso queira tentar alterar o componente para funcionar. envia o pull request
