### ISSUE TITLE
Compilation broken since rev. 466

### ISSUE THREAD

**Issue by zoran-vucenovic** [fortesinformatica/fortesreport-ce#224]
Revision 466 broke compilation in Lazarus -- tried on Linux and Windows.

On Linux (Mint 19.2, fpc 3.0.4, Lazarus 2.0.5):

Compile package frce 4.0: Exit code 1, Errors: 4
RLPrinters.pas(82,14) Error: Identifier not found "PDeviceMode"
RLPrinters.pas(82,25) Error: Error in type definition
RLPrinters.pas(115,46) Error: Identifier not found "HWND"
RLPrinters.pas(129,41) Error: Identifier not found "HWND"

On Windows the compilation stops on different line (fpc 3.0.4, Lazarus 2.0.5 -- there are more messages, but I paste only error messages here):

Compile package frce 4.0: Exit code 1, Errors: 8, Warnings: 4, Hints: 5
RLPrinters.pas(930,11) Error: identifier idents no member "GetPrinter"
RLPrinters.pas(931,49) Error: Incompatible type for arg no. 2: Got "LongWord", expected "PHANDLE"
RLPrinters.pas(941,68) Error: Wrong number of parameters specified for call to "SetPrinter"
printers.pas(476,20) Error: Found declaration: SetPrinter(AnsiString);
RLPrinters.pas(971,13) Error: identifier idents no member "GetPrinter"
RLPrinters.pas(972,51) Error: Incompatible type for arg no. 2: Got "LongWord", expected "PHANDLE"
RLPrinters.pas(980,70) Error: Wrong number of parameters specified for call to "SetPrinter"
printers.pas(476,20) Error: Found declaration: SetPrinter(AnsiString);

**Comment by dopidaniel** [comment]
yes.. I'm trying to fix it...

**Comment by dopidaniel** [comment]
I applied a possible fix... please update and try it...

**Comment by zoran-vucenovic** [comment]
Now compiles on Windows, but on Linux it still doesn't work...

On linux:
Compile package frce 4.0: Exit code 1, Errors: 1
RLPrinters.pas(135,41) Error: Identifier not found "HWND"

**Comment by zoran-vucenovic** [comment]
Can I reopen this somehow?

**Comment by dopidaniel** [comment]
Please Update and try again...

**Comment by zoran-vucenovic** [comment]
Thank you, compiles well now.
