### ISSUE TITLE
Problema con DataFormula en Lazarus 2.0.4

### ISSUE THREAD

**Issue by hoyosfelix** [fortesinformatica/fortesreport-ce#227]
Hola,
Estoy utilizando FortesReport 4.0 en Lazarus 2.0.4 con el componente IBX 2.3.3 para conectar a Firebird.
En la versión anterior de FortesReport podía concatenar, en la propiedad DataFormula de TRLDBText,   campos de la base de datos de esta manera: 
  **_CODIGO+' - '+DESCRIPCION_**  
y el resultado era por ejemplo:
  **10AB - MONITOR**
Actualmente, acepta esa fórmula pero al momento de previsualizar el reporte el campo aparece vacío.
Pregunto si es un problema del FortesReport o del IBX?
Habría alguna manera de solucionar esto?

Gracias y saludos cordiales.

**Comment by juliomar** [comment]
Hola, ¿puede adjuntar un pequeño proyecto de datos que puede ser con sqlite para hacer lo mismo para que podamos ayudarlo?
curiosamente, no se han realizado cambios a este respecto y debería estar funcionando.

**Comment by hoyosfelix** [comment]
Hola juliomar,
Gracias por responder.
La diferencia que encontré con la versiónes anterior es que antes no era necesario colocar en el form ningún RLExpressionParser para concatenar campos con strings.
La solución que encontré al problema es colocar un RLExpressionParser en el form y con eso ya pude lograr la concatenación.
Saludos cordiales.
