### ISSUE TITLE
Fazer o RLLabel.visible = False no beforePrint não funciona

### ISSUE THREAD

**Issue by giovanimdelcol** [fortesinformatica/fortesreport-ce#228]
Em versões anteriores passar o rllabel.visible=False no beforeprint dele fazia com que o mesmo não fosse impresso. Na versão atual (Delphi Rio), isso não ocorre.

**Comment by juliomar** [comment]
Hum acho que era um bug 
veja algo assim
procedure TForm1.RLLabel1BeforePrint(Sender: TObject; var AText: string;
  var PrintIt: Boolean);
begin
  PrintIt := false;
