### ISSUE TITLE
GetIt package for RAD Studio has a wrong URL

### ISSUE THREAD

**Issue by DeveloppeurPascal** [fortesinformatica/fortesreport-ce#229]
This problem is still present on package downloadable with 10.3.3 Rio. Can you please fix it ? (not a real big problem, but it would be better for users to find your repository than a 404 page)

https://quality.embarcadero.com/browse/RSP-20103

**Comment by juliomar** [comment]
Thanks for the report.
and sorry for the delay in responding.
I need to fix this with Getit

**Comment by juliomar** [comment]
I will take advantage and upload information of the version working on the Sydney version.
I will close the issue
thank you again
