### ISSUE TITLE
FortesReport CE does not compile with FPC 3.3.1

### ISSUE THREAD

**Issue by JanRoza** [fortesinformatica/fortesreport-ce#233]
I just installed a trunk version of Lazarus (2.1.0) and Free Pascal (3.3.1) and am unable to compile FortesReport CE anymore.
Complier returns message "RLMetaVCL.pas(305,18) Error: Range check error while evaluating constants (3 must be between 0 and 2)".
Compiling with Free Pascal 3.0.4 gives no errors and compiles OK.

**Comment by dopidaniel** [comment]
Try to insert the line below, on End of on **RLReport.inc**

{$R-}

**Comment by EMBBlaster** [comment]
Duplicate of #213
