### ISSUE TITLE
Problemas na instalação Fortes Report após alteração de 19/12/2019

### ISSUE THREAD

**Issue by NetSoft-Claudio** [fortesinformatica/fortesreport-ce#234]
Boa tarde,

Após ter feito a atualização do Fortes Report hoje "08/01/2020" o mesmo não está sendo instalado no Delphi 7, pois foi feito uma alteração no Fortes Report em Dezembro de 2019 e acredito que está alteração não comportou bem para Delphi 7.

veja que o erro da instalação está se referindo ao arquivo RLPrinters.pas que se encontra na pasta "Source" do "Fortes Report" :

O erro está indicando o arquivo RLPrinters.pas na linha (969), conforme abaixo:

Se eu comentar essas linhas, dai instala normalmente o "Fortes Report".

procedure TRLPrinterWrapper.CreateDeviceMode(WindowHandle: HWND);
var
  Device, Driver, Port: array[0..MAX_PATH] of char;
  PrinterHandle: THandle;
  OldModeHandle: THandle; //hDeviceMode
  OldDeviceMode: PDeviceMode; //PrinterDevMode
  NewModeHandle: THandle;
  NewDeviceMode: PDeviceMode;
  BytesNeeded: Integer;
begin
  Printer.GetPrinter(Device, Driver, Port, OldModeHandle);
  if WinSpool.OpenPrinter(@Device, PrinterHandle, nil) then
  try
    OldDeviceMode := GlobalLock(OldModeHandle);
    try
      BytesNeeded := WinSpool.DocumentProperties(WindowHandle, PrinterHandle, Device, nil, nil, 0);
      if BytesNeeded < 0 then
        raise Exception.Create('The call to DocumentProperties failed.');
      NewModeHandle := GlobalAlloc(GHND, BytesNeeded);
      NewDeviceMode := GlobalLock(NewModeHandle);
      try
        case WinSpool.DocumentProperties(WindowHandle, PrinterHandle, Device, NewDeviceMode^, OldDeviceMode^, DM_OUT_BUFFER or DM_IN_PROMPT or DM_IN_BUFFER) of
          IDOK: begin
            Printer.SetPrinter(Device, Driver, Port, NewModeHandle);
            ClearSavedDevMode;
            SavedPrinterSettings.DevMode := GetMemory(BytesNeeded);
            SavedPrinterSettings.Bytes := BytesNeeded;
            SavedPrinterSettings.PrinterName := Printer.Printers[Printer.PrinterIndex];
            CopyMemory(SavedPrinterSettings.DevMode, NewDeviceMode, BytesNeeded);
          end;
          IDCANCEL: // do nothing
          else raise Exception.Create('Something went wrong with setting the new printer parameters.');
        end;
      finally
        GlobalUnlock(NewModeHandle);
      end;
    finally
      GlobalUnlock(OldModeHandle);
    end;
  finally
    WinSpool.ClosePrinter(PrinterHandle);
  end;
end;

 Citar

**Comment by dopidaniel** [comment]
Apliquei uma possível correção.. Favor atualizar os Fontes e verificar se está tudo ok...

**Comment by NetSoft-Claudio** [comment]
Bom dia Daniel,

 

Obrigado pelo retorno, atualizei os fontes e deu tudo certo!

 

Abs

Claudio

 

De: Daniel Simões de Almeida [mailto:notifications@github.com] 
Enviada em: quinta-feira, 9 de janeiro de 2020 00:10
Para: fortesinformatica/fortesreport-ce
Cc: NetSoft-Claudio; Author
Assunto: Re: [fortesinformatica/fortesreport-ce] Problemas na instalação Fortes Report após alteração de 19/12/2019 (#234)

 

Apliquei uma possível correção.. Favor atualizar os Fontes e verificar se está tudo ok...
