### ISSUE TITLE
Senha na exportação do PDF

### ISSUE THREAD

**Issue by frrodrigo** [fortesinformatica/fortesreport-ce#236]
Alguma opção na hora de exportação para PDF no FortesReport colo﻿car uma senha para que o usuário so consiga abrir o pdf se digitar essa senha

 ﻿uso ele para criar alguns relatórios e não achei essa opção no componente, alguém ja fez ou teria outra forma de usar com senha ?

Ex: Fatura de Cartão estão vindos com senha no pdf e preciso fazer o mesmo em alguns relatórios feito em FortesReport

**Comment by juliomar** [comment]
não. 
caso queira tentar implementar e enviar o pull request será validado
