### ISSUE TITLE
Erro no TRLRichText - Não quebra a linha

### ISSUE THREAD

**Issue by wmalmeida** [fortesinformatica/fortesreport-ce#237]
O componente não gera a quebra de linha de forma correta, conforme a imagem abaixo. 
Aproveitando, apesar que o TRLMemo quebra a linha corretamente a propriedade WordWarp não esta funcionado direito, a linha ultrapassa a área do texto.
Alguma orientação para isso ?
Tem como implementar o RlMemo e o RlRichText apartir do Memo e RichText nativos do delphi ?

![errorichtext](https://user-images.githubusercontent.com/61016688/74445320-f4d46100-4e54-11ea-8cb5-e6e85fde7f54.png)
![erro2](https://user-images.githubusercontent.com/61016688/74449413-4ed82500-4e5b-11ea-852b-8a7c9e4d3cd5.jpg)

**Comment by juliomar** [comment]
TRLRichText tem que usar configurações se pegar um no delphi e rodar e tentar formatar ele e dai pegar os dados vai entender o que falei pois não vai ser só a quebra de linha ele vai interpretar o RTF.
Sim o RLMemo vai tentar mostrar pra você tudo o que estiver nele. se estiver pra quebrar linha ou autosize ele vai fazer isso.

se quiser tentar pode ficar a vontade e enviar o pull request depois
