### ISSUE TITLE
Cada grupo em uma folha

### ISSUE THREAD

**Issue by rodrigo-ogioni** [fortesinformatica/fortesreport-ce#238]
Bom dia,
Tenho um cliente que tem um relatorio de produtos por grupo, entao fiz um detail com subdetail.
Esse cliente quer cada grupo em um folha, teria que fazer isso?

Grato

**Comment by IsaiasSantosS** [comment]
Tenta usar a propriedade pagebreaking do RLGroup

**Comment by juliomar** [comment]
Sim tem mas lembre que o ORDER BY do sql deve seguir também o mesmo do grupo.
