### ISSUE TITLE
Error "Bitmap with unknown compression (8192)" FPC 3.2.0 rc1

### ISSUE THREAD

**Issue by patyit** [fortesinformatica/fortesreport-ce#239]
Can't Preview or print any picture, "Bitmap with unknown compression (8192)" error in the fallowing FortesCE RLMetaVCL.pas unit, procedure FromMetaGraphic :

> function FromMetaGraphic(const ASource: String): TGraphic;
var
  S: TStringStream;
  T: String;
begin
  if ASource = '' then
    Result := nil
  else
  begin
    S := TStringStream.Create(ASource);
    try
      S.Seek(0, soFromBeginning);
      T := S.ReadString(3);
      if T = 'NIL' then
        Result := nil
      else if T = 'BMP' then
        Result := TRLBitmap.Create
      else if T = 'ICO' then
        Result := TIcon.Create
      else
        Result := nil;
      if Assigned(Result) then
        Result.LoadFromStream(S); //<-- "Bitmap with unknown compression (8192)"
    finally
      S.free;
    end;
  end;
end; 

FPC 3.2.0 rc1 changelog, says :
TStringStream now observes system encoding
 
    **Old behaviour:** TStringStream copied bytes as-is from the string specified in the constructor.
    **New behaviour:** Now bytes are fetched from the string using the encoding of the string.
    Reason: Delphi-compatibility
    Remedy: Pass a string with the correct encoding to TStringStream
    svn: 36758

Se on Lazarus forum : [https:]https://forum.lazarus.freepascal.org/index.php/topic,49451.0.html(url)

**Comment by juliomar** [comment]
Did you manage to run FRCE on FPC 3.2.0? because we noticed errors when installing.

**Comment by patyit** [comment]
I tested it on FPC 3.2.0 rc1, I continue to do the development on FPC 3.0.4. I haven't tried what was released on FPC 3.2.0 !

**Comment by juliomar** [comment]
please send small project attach for test

**Comment by patyit** [comment]
Very simple test project to reproduce problem.
[FRCE_test.zip](https://github.com/fortesinformatica/fortesreport-ce/files/4909264/FRCE_test.zip)

**Comment by dopidaniel** [comment]
I applied a possible fix
https://github.com/fortesinformatica/fortesreport-ce/pull/250

**Comment by patyit** [comment]
I can confirm that the fix solved the problem !
I tested it on the live "big" app and everything works as expected.
Thanks for the fix !

XUbuntu x64, FPC 3.2.1 (3.2.0 fixes), Lazarus 2.0.11 (2.0.10 fixes)
