### ISSUE TITLE
Impressao cortada nf-e

### ISSUE THREAD

**Issue by monegattos** [fortesinformatica/fortesreport-ce#240]
Bom dia , Estou

tendo o seguinte problema na impressão da n-e esa saino cortado
já vi muitos postos que temos qu mexer no zoom do Windows , mas não vejo sentido 
nisso mexer no zoom , expliquei para o cliente ele começo a tira sarro da minha cara , não subir o que falar para ele

alguém já passo por isso

![image](https://user-images.githubusercontent.com/64551105/80628794-48a02080-8a28-11ea-9aed-3bdf197593d3.png)

**Comment by russocorp** [comment]
Não uso o Fortes, mas lendo os Issues, imagino que seu problema seja referente ao item #195 
Talvez fazer alguma alteração no fonte para buscar a scala do sistema ao invés de deixar fixado.

**Comment by juliomar** [comment]
Isso olhe o Zoom do windows ou diminua essa fonte pois é muito grande
mas se for pra chutar é o zoom do windows habilitado.

**Comment by monegattos** [comment]
Entao quando o windows esta com a escala de 100% , imprimi certinho agora se muda a escola a impressao fica toda cortada , nao sei mais o que justificar para o cliente
    Em sábado, 11 de julho de 2020 20:37:16 BRT, Juliomar Marchetti <notifications@github.com> escreveu:  
 
 


Isso olhe o Zoom do windows ou diminua essa fonte pois é muito grande
mas se for pra chutar é o zoom do windows habilitado.

**Comment by giovanimdelcol** [comment]
![image](https://user-images.githubusercontent.com/8997716/91881966-b075aa80-ec58-11ea-83e9-e03edf2ecbe2.png)

Marca sua aplicação como unaware no DPI que vai corrigir, mas pode ter consequencias em outras telas (ficar meio embaçado), veja se funciona pra vc. Assim não precisa ver se tem ou não zoom no windows.
