### ISSUE TITLE
Error Installing Fortes on Delphi 10.4 

### ISSUE THREAD

**Issue by rluschen** [fortesinformatica/fortesreport-ce#243]
Dear all,

I get the same problem over and over again when trying to use the frceInstall.exe from GitHub (64 bits).

Can someone fix this ?

Regards, Rob

p.s.: Added log and printscreen
[log_Delphi_10.4_Sydney.txt](https://github.com/fortesinformatica/fortesreport-ce/files/4851681/log_Delphi_10.4_Sydney.txt)
![Error_FortesReport](https://user-images.githubusercontent.com/67633806/86124407-60a12880-badb-11ea-9fb3-8ad7ef02fd84.jpg)

**Comment by juliomar** [comment]
Hello has the win64 option, but the delphi IDE
and win32, then install Win32 and add the path with the source location and can use it in win64 projects without any problems.
try after that to open a new project in win64 and go to the FRCE palette that will be working.
