### ISSUE TITLE
Lazarus 2.10 - Fortes não compila

### ISSUE THREAD

**Issue by alimasilva2018** [fortesinformatica/fortesreport-ce#244]
RLMetaVCL  linha 305 - no Lazarus 2.08 não ocorre erro
![erro_fr2](https://user-images.githubusercontent.com/34888072/87235616-49541c00-c3b4-11ea-9999-bd57d431977f.png)
![erro_fr1](https://user-images.githubusercontent.com/34888072/87235618-49ecb280-c3b4-11ea-9a7a-6aff7baab2c2.png)

**Comment by juliomar** [comment]
Resolvido no último merge
