### ISSUE TITLE
RLDBMemo com texto muito grande

### ISSUE THREAD

**Issue by igorbastosib** [fortesinformatica/fortesreport-ce#248]
Estou experimentando uma dificuldade.
Tenho um SubDetail, uma Band e um RLDBMemo (nessa ordem). O Memo está com link no Field e apresenta corretamente os dados, mas em umas situações específicas o usuário teve que digitar MUITA informação, algo do tipo 3 páginas de texto. Atualmente ele quebra a página e apresenta a observação em uma página nova, mas ele não quebra em várias páginas, ou seja, fica sendo só aquela página e com a informação pela metade.

Teria uma forma de configurar o RLDBMemo para ele quebrar a página qnd necessário?
Ou uma forma manual de separar isso em páginas?

Obrigado.

**Comment by RafaSartori** [comment]
Olá, também já tive esta dificuldade, e realmente acontece isso mesmo. O que fiz pra resolver foi ler linha a linha do Memo, usando o Evento "OnNeedData" do RLReport. Veja o exemplo na pasta "Sem Dados".

De qualquer maneira é uma sugestão para melhoria.

**Comment by igorbastosib** [comment]
> Olá, também já tive esta dificuldade, e realmente acontece isso mesmo. O que fiz pra resolver foi ler linha a linha do Memo, usando o Evento "OnNeedData" do RLReport. Veja o exemplo na pasta "Sem Dados".
> 
> De qualquer maneira é uma sugestão para melhoria.

Analisando o exemplo acho que entendi a ideia, mas como vc sabe qnd determinada linha está completa?

Segue uma imagem do que tenho, um texto com quebras de linhas e sem quebras de linhas. Essa observação aí vai ter aproximadamente 3 páginas de texto.
Eu não compreendi como organizar a quebra de linhas, visto que no exemplo ele utiliza um ListBox para determinar o texto de cada uma das linhas.
Como eu organizaria por exemplo para que ele não corte a última linha e comece a apresentar corretamente na outra página?

![Capture](https://user-images.githubusercontent.com/9283712/89729518-6a00a780-da2e-11ea-8a35-e6a594a70782.JPG)

**Comment by juliomar** [comment]
Acho que no RLDBMemo tem a propriedade Justificado
