### ISSUE TITLE
Image in report - Error "Bitmap with unknown compression (8192)" FPC 3.2.0- Lazarus 2.0.10

### ISSUE THREAD

**Issue by griebold** [fortesinformatica/fortesreport-ce#249]
i got the same Error in as Issue #239 on a new installation in Lazarus 2.0.10 - FPC 3.2.0 on Win10 - 64bit.

The problem occurs, if there are images in the report or the report has a background image. The report(s) will be shown in a preview.

My applications use this for printing orders and invoices with  a customer specific logo in the report. So there is no chance to migrate applications to Lazarus 2.0.10.

Thank you for your good work! I hope, that you can fix the problem.

Best regards
Gernot

**Comment by griebold** [comment]
1. Problem
Report with RLImage - Image is not shown (see Screenshot)

2. Problem
Report with RLImage - Image is loaded by code
RLImage1.Picture.LoadFromFile('bmp1.bmp');
Error: "Bitmap with unknown compression (8192)

3. Problem
Report with RLImage and a loaded image
Preview Report in RLPreview
Error: "Bitmap with unknown compression (8192)

![Screenshot2](https://user-images.githubusercontent.com/68377982/87769321-c3a1f780-c81d-11ea-8a33-cb4693de7085.png)
![Screenshot1](https://user-images.githubusercontent.com/68377982/87769324-c43a8e00-c81d-11ea-9d57-7ce7240032b9.png)

**Comment by griebold** [comment]
This is the fix for Lazarus 2.0.10. Is NOT tested with Delphi. 
Hope it will work for you.

File: rlmetavcl.pas
Changed: 
function ToMetaGraphic(ASource: TGraphic): string;
function FromMetaGraphic(const ASource: String): TGraphic;

---------------------------------------------------------
function ToMetaGraphic(ASource: TGraphic): string;
var
  S: TStringStream;
  M: TBitmap;
  G: TGraphic;
begin
  M := nil;
  S := TStringStream.Create('');
  try
    G := ASource;

    M := TRLBitmap.Create;
    M.Width := ASource.Width;
    M.Height := ASource.Height;
    G := M;
    M.Canvas.Draw(0, 0, ASource);

    if Assigned(G) then
      G.SaveToStream(S);
    Result := S.DataString;
  finally
    if Assigned(M) then
      M.free;
    S.free;
  end;
end;

---------------------------------------------------------
function FromMetaGraphic(const ASource: String): TGraphic;
var
  S: TStringStream;
  bmp: TBitmap;
begin
  if ASource = '' then
    Result := nil
  else
  begin
    S := TStringStream.Create(ASource);
    try
      bmp:= TBitmap.Create;
      bmp.LoadFromStream(s);
      Result := bmp;
    except
     Result := nil;
    end;
  end;
end;

**Comment by dopidaniel** [comment]
I applied a possible fix
https://github.com/fortesinformatica/fortesreport-ce/pull/250

**Comment by griebold** [comment]
Dear Daniel,

 

thank you very much.

 

Viele Grüße

Gernot Riebold

 

Gernot Riebold

Marktstrasse 2

73779 Deizisau

Telefon: +49 (0)7153 23412

Mobil: +49 (0)160 7838527

 

Von: Daniel Simões de Almeida <notifications@github.com> 
Gesendet: Sonntag, 19. Juli 2020 18:40
An: fortesinformatica/fortesreport-ce <fortesreport-ce@noreply.github.com>
Cc: griebold <griebold@web.de>; Author <author@noreply.github.com>
Betreff: Re: [fortesinformatica/fortesreport-ce] Image in report - Error "Bitmap with unknown compression (8192)" FPC 3.2.0- Lazarus 2.0.10 (#249)

 

I applied a possible fix
#250 <https://github.com/fortesinformatica/fortesreport-ce/pull/250>
