### ISSUE TITLE
Erro ao instalar no XE2

### ISSUE THREAD

**Issue by CarlosTedEx** [fortesinformatica/fortesreport-ce#25]
Boa noite, estou tentando instalar o Fortes no Delphi XE2 mas ao compilar está dando esse erro:

**[DCC Fatal Error] FortesReportCE_Win32_DXE2_vcl.dpk(35): E2202 Required package 'designide' not found**

Caso alguém tenha passado por este problema favor postar aqui.

Windows 8.1 64bits

**Comment by marciomartins** [comment]
Bom dia.
O seu Delphi está com os últimos updates instalado?
Tente remover o designide e compilar novamente.

**Comment by CarlosTedEx** [comment]
Bom dia Marcio, fiz a remoção e a instalação do Delphi e o pacote do Fortes foi instalado corretamente.
Grato pela atenção!

**Comment by diegothome** [comment]
Boa tarde, CarlosTedEx 

Estou com o mesmo erro ao tentar compilar a versão atual do trunk em win64, mesmo removendo o pacote 'designide' como o Marcos falou não vai. 

Você esta conseguindo compilar a versão em win64? 

Vlwww

**Comment by CarlosTedEx** [comment]
Boa tarde Diego, aqui está tudo certo sim!
Estou utilizando o pacote na versão 447 no Windows 10 Pro 64bits
Tente remover o componente e apagar a pasta e baixar tudo novamente. Estou utilizando essa URL "https://github.com/fortesinformatica/fortesreport-ce/trunk"
