### ISSUE TITLE
Arquivo exportado em PDF desconfigurado ao visualizar no navegador

### ISSUE THREAD

**Issue by weberdepaulai12** [fortesinformatica/fortesreport-ce#251]
Olá!
Quando exporto um arquivo PDF do Fortes Report e nesse relatório tem algo em _ITÁLICO_, ao visualizar o PDF em navegadores como Chrome e Edge aparece tudo em itálico de forma desconfigurada.
Achei que poderia ser algo do navegador, porém se eu gerar ao do Word, Excel exibe corretamente.
O problema ocorre somente em navegadores. A exibição em programas de PDF funciona corretamente, Foxit, Adobe Reader, Sumatra etc. 

Visualização no navegador
![image](https://user-images.githubusercontent.com/16706993/88801056-7a3b9b80-d17f-11ea-8cd1-87e45c2f6189.png)

Visualização no Foxit
![image](https://user-images.githubusercontent.com/16706993/88801115-95a6a680-d17f-11ea-9d0b-a068b5d5e4f4.png)

**Comment by juliomar** [comment]
Pode ser a falta de levar a fonte junto, ou dela estar presente no navegador.
chegou a ver isso.?
