### ISSUE TITLE
Não instalou no Lazarus baixando pelo gerenciador de pacotes

### ISSUE THREAD

**Issue by rodrigoce** [fortesinformatica/fortesreport-ce#252]
![image](https://user-images.githubusercontent.com/10128869/89107959-2cd35e80-d40b-11ea-93f2-6f5aad82399d.png)

**Comment by juliomar** [comment]
Boa tarde.
acho que não está correto lá. baixa aqui do git que está funcionanod
Qual versão do Lazarus?
