### ISSUE TITLE
Duas vias na mesma folha

### ISSUE THREAD

**Issue by datilas** [fortesinformatica/fortesreport-ce#253]
eu tenho um cliente que usava impressora matricial com papel meia folha,

agora ele trocou para uma impressoras laser e ele precisa imprimir 2 vias na mesma folha

alguém já fez isso?

**Comment by juliomar** [comment]
Acho que no exemplo que tem aqui dos projetos tu tem isso 
eu acho que fiz ele e subi

**Comment by datilas** [comment]
olhei todos os demos e não achei, mas para relatório simples tipo recibo eu consigo,
a questão é que não consigo fazer meia folha com DataSet mestre detalhe

**Comment by Walfridocesar** [comment]
Conseguiu alguma @datilas?
Estou em busca desta solução também!

**Comment by Walfridocesar** [comment]
Consegui obter o resultado esperado da seguinte forma.
Montei o recibo dentro de um RLGroup conforme preciso... logo abaixo inseri um RLSubDetail e colei esse mesmo RLGroup dentro dele. 

O RlSubDetail vair funcionar como se fosse outro relatório.
