### ISSUE TITLE
RlLabel / RlDbText Orientação, Rotação.

### ISSUE THREAD

**Issue by witerlland** [fortesinformatica/fortesreport-ce#254]
Teria como rotacionar uma rlLabel ou RlDbText?
Ou algum outro componente de texto do fortesReport.
Pois na Font -> Orientation ao ser alterado muda apenas em tempo de design, em execução o mesmo é apresentado sem a mudança.

**Comment by juliomar** [comment]
boa tarde.
por enquanto não. poderia ser uma feature a ser implementado nele.

**Comment by galegoga-pixel** [comment]
boa tarde!
Ainda não está implementado. Fiz umas modificações no código fonte e consegui adicionar o comportamento. Como que faz para contribuir, é só postar aqui ?

**Comment by galegoga-pixel** [comment]
modifiquei os arquivos RLMetaVCL, RLMetaFile e RLPDFFilter (os arquivos foram postado como *.txt devido a política do github)

[RLMetaFile.txt](https://github.com/user-attachments/files/28720934/RLMetaFile.txt)
[RLMetaVCL.txt](https://github.com/user-attachments/files/28720933/RLMetaVCL.txt)

[RLPDFFilter.txt](https://github.com/user-attachments/files/28725686/RLPDFFilter.txt)
