### ISSUE TITLE
Cannot assign a TBlobField to a TPicture

### ISSUE THREAD

**Issue by mariocarro** [fortesinformatica/fortesreport-ce#256]
I have a FirebirdSQL database with a blob field containing a bitmap. The render of the reports fails with the message of the subject when compiled with FPC on Linux using the ZeosLib database components library.

**Comment by mariocarro** [comment]
Forgot to add: The render fails when I add a TRLDBImage to the report bound to the blob field.

**Comment by Jonasslv** [comment]
I use an RLImage instead and in the BeforePrint of the band containing the RLImage I save the blob field to a stream and load it in the image component.

**Comment by juliomar** [comment]
> ‎Esqueci de adicionar: A renderização falha quando adiciono um TRLDBImage ao relatório vinculado ao campo blob.‎

solved with the solution above the friend?



> ‎Eu uso um RLImage em vez disso e na Impressão Anterior da banda contendo o RLImage eu salvo o campo blob em um fluxo e carrego-o no componente de imagem.‎
