### ISSUE TITLE
Dúvidas totalizar grupo.

### ISSUE THREAD

**Issue by RafaelVulpe** [fortesinformatica/fortesreport-ce#258]
Fiz um agrupamento e toda vez no fim de cada pagina ele da o total dessa página, porém o item ainda não terminou tem mais páginas para o mesmo item... gostaria de totalizar apenas quando mudasse o produto. Para totalizar hoje estou usando um footer dentro do Grupo e usando um result.

**Comment by mcristiano** [comment]
Olá estou com o mesmo problema, vc conseguiu solução ?

vlw !

**Comment by juliomar** [comment]
Consegue qualquer um dos dois montar um projeto de exemplo pequeno com um banco local sqlite e anexar aqui com ele para possamos depurar?
qual a versão do delphi ou lazarus que estão usando?
