### ISSUE TITLE
Erro ao criar arquivo temporário

### ISSUE THREAD

**Issue by Jonasslv** [fortesinformatica/fortesreport-ce#259]
No Windows Server com alguns clientes meus por algum motivo na hora do Fortes utilizar o GetTempPath da API do windows retorna um caminho inválido (algo tipo ...appdata/local/temp/4/, sendo que só existe até o temp) e consequentemente ele não consegue criar o arquivo pra preview/impressão (Cannot Open File).

Possíveis soluções para evitar esse tipo de problema: 
- Detectar se o path existe, se não extrai o path da aplicação e usa de caminho temporário.
- Usar ForceDirectories pra obrigar a criação do path antes de utiliza-lo.

**Comment by juliomar** [comment]
Isso tu fez em sua aplicação?
pois senão me engano isso dai remete a permissões do windows, então acho que o correto é verificar as permissões
