### ISSUE TITLE
Ao salvar relatório no formato Excel, não está "exportando" a logo (imagem) do mesmo.

### ISSUE THREAD

**Issue by mjg1909** [fortesinformatica/fortesreport-ce#260]
Ao salvar relatório no formato Excel, não está "exportando" a logo (imagem) do mesmo.

Observações: O imagem aparece corretamente na visualização do relatório.

Tem alguma configuração nos componentes RLXLSFilter e RLXLSXFilter que deva ser setada para que a imagem seja enviada para o documento Excel (xls/xlsx) exportado ?

No aguardo,
Marcelo J. Gonçalves

**Comment by juliomar** [comment]
A principio não, mas não lembro se tem código para ao exportar para xlsx ou xls ele enviei a imagem
