### ISSUE TITLE
Erro ao salvar arquivo em pdf

### ISSUE THREAD

**Issue by 0101tgf** [fortesinformatica/fortesreport-ce#263]
Boa tarde,

Eu utilizava Delphi Rio 10.3 ai migrei para o Delphi Sidney, não fiz nenhuma alteração no código fonte e passou a dar esse erro na hora de fazer .SaveToFile('C:\Proposta.pdf') 

![erro](https://user-images.githubusercontent.com/75810952/101826905-5feed280-3b0e-11eb-87ba-80846f9cdaf6.png)

Se eu fizer .print vai normal..

Por favor, poderia me ajudar ?

**Comment by juliomar** [comment]
O Fortes não funciona em FMX, no caso android , iphone , ios etc. 
esse erro está relacionado com a imagem do mesmo.
consegue fazer um deploy e ver onde ele começa o erro?
