### ISSUE TITLE
Erro ao compilar pacote no Lazarus Trunk

### ISSUE THREAD

**Issue by pedroaaraujo** [fortesinformatica/fortesreport-ce#265]
Ao instalar o pacote no Lazarus Trunk, é gerado erro de compilação.

Correção:
Na Unit RLPreview, alterar a linha 1098 
de `  if Parent is TRLPreview and (ssCtrl in Shift) then    `
para `  if (Parent is TRLPreview) and (ssCtrl in Shift) then    `

**Comment by juliomar** [comment]
Em qual versão do Lazarus? tenho rodando aqui 2.0.10 Win32 no windows e não tenho erro.
poderia informar mais detalhes

**Comment by pedroaaraujo** [comment]
Foi testado no Lazarus 2.1.0 (versão de desenvolvimento)

**Comment by juliomar** [comment]
já está disponível no git a correção.
