### ISSUE TITLE
Impressão TM 20

### ISSUE THREAD

**Issue by jcariasbr** [fortesinformatica/fortesreport-ce#266]
Prezados, estou com problema para imprimir um cupom em uma micro com windows 7 nas impressoras TM-20 e Elgin, a impressora não faz a compactação da impressão, em outros clientes não tenho esse problema, já reinstalei drivers, mudei configuração nos drivers, não queria mexer no sistema, pois, em todos os outros clientes funciona, alguem poderia me dar uma ideia, simples a impressão não sai comprimida.

**Comment by juliomar** [comment]
Isso tu está mandando direto do fortes para ela isso?

**Comment by juliomar** [comment]
eu iria chutar que é o driver instalado errado

**Comment by juliomar** [comment]
fechado por falta de retorno.
