### ISSUE TITLE
Conversão em PDF: problemas com o tamanho das fontes

### ISSUE THREAD

**Issue by rodrigocrovador** [fortesinformatica/fortesreport-ce#268]
Utilizo o Fortes para realizar a impressão de boletos e exportação para PDF. A impressão ocorre normalmente, a geração de PDF via impressora também não apresenta problemas. Porém quando se usa a exportação do próprio Fortes (RLPDFFilter, via botão "salvar" do preview), o tratamento da fonte no PDF fica incorreta (apaguei parcialmente os dados):

![exemplo](https://user-images.githubusercontent.com/55282203/112160550-07c57300-8bc9-11eb-8095-b567f8da3269.png)

Verificando o arquivo gerado pela conversão e pela impressora, notei que a array de tamanhos da fonte ficou diferente, ambas Arial sem estilo (esquerda: gerado pelo RLPDFFilter; a direita, gerado pela impressora de PDF):

![Capturar](https://user-images.githubusercontent.com/55282203/112160906-625ecf00-8bc9-11eb-9aff-d6ccc0de9938.PNG)

Conferindo a procedure FontGetMetrics, o problema estava no BMP usado para montar a array com os tamanhos: é usado um BMP auxiliar compartilhado com outros métodos através da função NeedAuxBitmap. Porém, algum processo está afetando o BMP de forma que modifica o resultado final da FontGetMetrics. Modifiquei o processo para criar o BMP localmente e a array foi gerada corretamente. 

Entretanto, algumas palavras ficaram fora de lugar, algumas indo para esquerda ou para direita. julgando que seria pelo mesmo motivo, reverti a alteração e modifiquei a função NeedAuxBitmap para recriar o BMP sempre que for requisitado: 

![Capturar](https://user-images.githubusercontent.com/55282203/112162460-d64da700-8bca-11eb-9ab7-1294b545eab4.PNG)

Com este ajuste a conversão ocorre normalmente. Não consegui identificar o que modificou o BMP a ponto de gerar todos estes problemas.

**Comment by dopidaniel** [comment]
Parece correto.. Boa pegada,..

Vou enviar o ajuste para o Trunk..
