### ISSUE TITLE
RLRitchText não quebra linhas

### ISSUE THREAD

**Issue by EvandroMassini** [fortesinformatica/fortesreport-ce#270]
Senhores, bom dia! Utilizo o FR junto ao Lazarus. Recentemente passei a perceber um problema relacionado ao uso de textos em negrito (bold) nos objetos RLRichText. Quando a palavra negritada está próxima ao final da linha as quebras deixam de ocorrer e tudo passa a ser impresso na mesma linha, sendo que desta forma o texto sai dos limites do objeto e não pode ser visto. Há algo que possa resolver esta situação? Grato.

**Comment by juliomar** [comment]
Depurar e ver se não é necessário aumentar o tamanho do campo por conta do negrito

**Comment by EvandroMassini** [comment]
Desculpe, não entendi! Você se refere ao campo do BD? Pq este não seria o caso, ele é do tipo blob subtype 1 (Firebird), ou seja, não há tamanho limite. Ou vc se refere ao objeto em si? Grato pelo retorno.

**Comment by juliomar** [comment]
Não. no Fortes mesmo. mas só depurando, entrar no código do fortes e verificar, não uso dia dia linux então não consigo depurar nele.
