### ISSUE TITLE
C++Builder Package

### ISSUE THREAD

**Issue by macicogna** [fortesinformatica/fortesreport-ce#272]
Olá,

Gostaria de perguntar se já foi tentado uma versão para C++Builder do Package de instalação do FortesReport.

Estou tentando criar um, mas encontrei alguns problemas com as diretivas condicionais de compilação para DELPHI ao invés de BCB.

Caso seja possível, gostaria de me oferecer para a construção desse Package.

Grato pela atenção,

Marcelo A. Cicogna

**Comment by juliomar** [comment]
Nunca Tentamos mas creio que pode ser possível sim.

**Comment by macicogna** [comment]
juliomar,

Nesse meio tempo, eu consegui criar um Package funcional no C++Builder 10.2.3 (Tokyo).

Anos atrás fiz uma contrubuição semelhante com os mantenedores do ZeosLib.

Se quiserem, posso encaminhar os arquivos.

Sobre as adaptações, com o objetivo de não alterar o código em Pascal, Fiz algumas modificações em "RLReport_jedi.inc":

`{------------------------------------------------------------------------------}
{ DELPHIX_UP from DELPHIX and BCBX mappings                                    }
{------------------------------------------------------------------------------}

{$IF Defined(DELPHI27) OR Defined (BCB27)} {$DEFINE DELPHI27_UP} {$IFEND}
{$IF Defined(DELPHI26) OR Defined (BCB26)} {$DEFINE DELPHI26_UP} {$IFEND}
{$IF Defined(DELPHI25) OR Defined (BCB25)} {$DEFINE DELPHI25_UP} {$IFEND}
{$IF Defined(DELPHI24) OR Defined (BCB24)} {$DEFINE DELPHI24_UP} {$IFEND}
{$IF Defined(DELPHI23) OR Defined (BCB23)} {$DEFINE DELPHI23_UP} {$IFEND}
{$IF Defined(DELPHI22) OR Defined (BCB22)} {$DEFINE DELPHI22_UP} {$IFEND}
{$IF Defined(DELPHI21) OR Defined (BCB21)} {$DEFINE DELPHI21_UP} {$IFEND}
{$IF Defined(DELPHI20) OR Defined (BCB20)} {$DEFINE DELPHI20_UP} {$IFEND}
{$IF Defined(DELPHI19) OR Defined (BCB19)} {$DEFINE DELPHI19_UP} {$IFEND}
{$IF Defined(DELPHI18) OR Defined (BCB18)} {$DEFINE DELPHI18_UP} {$IFEND}
{$IF Defined(DELPHI17) OR Defined (BCB17)} {$DEFINE DELPHI17_UP} {$IFEND}
{$IF Defined(DELPHI16) OR Defined (BCB16)} {$DEFINE DELPHI16_UP} {$IFEND}
{$IF Defined(DELPHI15) OR Defined (BCB15)} {$DEFINE DELPHI15_UP} {$IFEND}
{$IF Defined(DELPHI14) OR Defined (BCB14)} {$DEFINE DELPHI14_UP} {$IFEND}
{$IF Defined(DELPHI12) OR Defined (BCB12)} {$DEFINE DELPHI12_UP} {$IFEND}
{$IF Defined(DELPHI11) OR Defined (BCB11)} {$DEFINE DELPHI11_UP} {$IFEND}
{$IF Defined(DELPHI10) OR Defined (BCB10)} {$DEFINE DELPHI10_UP} {$IFEND}
{$IFDEF DELPHI9}  {$DEFINE DELPHI9_UP}  {$ENDIF}
{$IFDEF DELPHI8}  {$DEFINE DELPHI8_UP}  {$ENDIF}
{$IFDEF DELPHI7}  {$DEFINE DELPHI7_UP}  {$ENDIF}
{$IF Defined(DELPHI6) OR Defined (BCB6)}  {$DEFINE DELPHI6_UP}  {$IFEND}
{$IF Defined(DELPHI5) OR Defined (BCB5)}  {$DEFINE DELPHI5_UP}  {$IFEND}
{$IFDEF DELPHI4}  {$DEFINE DELPHI4_UP}  {$ENDIF}
{$IFDEF DELPHI3}  {$DEFINE DELPHI3_UP}  {$ENDIF}
{$IFDEF DELPHI2}  {$DEFINE DELPHI2_UP}  {$ENDIF}
{$IFDEF DELPHI1}  {$DEFINE DELPHI1_UP}  {$ENDIF}`

Fico à disposição,

Marcelo.

**Comment by juliomar** [comment]
Sim é manter o arquivo do JEDI pra não sofrer, a menos que tu queira fazer algo em separado para isso. a mais

**Comment by macicogna** [comment]
juliomar,

Vou criar um arquivo "RLReport_BCB.inc" só para esse tratamento das defines de BCBX e incluir em "RLReport.inc".

Tudo bem?

Quando quiser, posso enviar os arquivos do Package e um manual de instruções para usuários C++Builder.

Abraço,

Marcelo.

**Comment by juliomar** [comment]
Deu certo? manda um pull request para testermos. ele não interfere no delphi e lazarus?

**Comment by macicogna** [comment]
juliomar,

O arquivo "RLReport_BCB.inc" que montei não deve interferir, pois os "OR Defined (BCBX)" só funcionam na personalidade C++Builder. No Delphi e Lazarus as diretivas continuam as mesmas.

Vou mandar o pull request.

Abraço,

Marcelo.

**Comment by juliomar** [comment]
Logo valido e subo ele no principal. valeu
