### ISSUE TITLE
Nome do Arquivo em Salvar como do Fortes Report

### ISSUE THREAD

**Issue by Meioquilinho** [fortesinformatica/fortesreport-ce#275]
Como faço para alterar a pasta (path) e o nome do arquivo ao clicar no botão salvar. A função SaveToFile() funciona perfeitamente, mas ao clicar no botão salvar já com o relatório aberto, preciso já direcionar o usuário para a pasta correta e o nome do arquivo sugerido. São vários relatórios e cada um em um pasta. queria direcioná-los já para a pasta e nome correto. 

Alguém pode me ajudar? 

Obrigado!

**Comment by juliomar** [comment]
Creio que como está implementado não seja possível
mas sugiro olhar os fontes já que o mesmo está disponível e tentar entender

**Comment by juliomar** [comment]
Caso queira contribuir tu pode fazer a alteração no seu fork e mandar o pull request.
