### ISSUE TITLE
TRLImage does not work...

### ISSUE THREAD

**Issue by brianlai728** [fortesinformatica/fortesreport-ce#277]
In design mode, it looks fine... but it does not work in runtime.
In the image size is less than 32Kb, the image will corrupt like below,
![image](https://user-images.githubusercontent.com/84885015/119751925-a7a3c380-bece-11eb-8f9e-9a9173b57774.png)

Hence the original image is,
![image](https://user-images.githubusercontent.com/84885015/119751798-690e0900-bece-11eb-8246-9d6f8d083239.png)

Moreover, if it is over 32Kb, it will prompt "Out of Memory" error in runtime...

Please help...

**Comment by juliomar** [comment]
please attach a simple example zipped with the image for us to analyze?
