### ISSUE TITLE
The report setting cannot be sent to print dialog.

### ISSUE THREAD

**Issue by brianlai728** [fortesinformatica/fortesreport-ce#278]
I have set the report size as A5 in landscape.
But this setting cannot be passed to Print Dialog.

Moreover, there are not any properties about "No of Copies", "Input Tray", "Color Setting" and "Duplex Setting"...

Please help...

**Comment by juliomar** [comment]
it's pretty simple so it doesn't have those options.
if you want to contribute and help the project you can send your pull request
