### ISSUE TITLE
Ao gerar o relatório em XLS com mais de 5 páginas, ocorre um erro ao abrir

### ISSUE THREAD

**Issue by wesleygsilva** [fortesinformatica/fortesreport-ce#280]
O curioso é que com alguns editores (Libre office, WPS) abre normalmente. Ocorre somente com o Excel. Testado nas versões 2010, 2013 e 2016 do office. Não identificada a solução ainda.

**Comment by juliomar** [comment]
Certo. sugere alguma correção?

**Comment by juliomar** [comment]
fechado por falta de retorno . se precisar envia pull request com a solução.
