### ISSUE TITLE
Dúvida Delphi+Linux+FortesReport+daemon

### ISSUE THREAD

**Issue by arvanus** [fortesinformatica/fortesreport-ce#281]
Olá a todos
Alguém já tentou usar o Fortes em um projeto (Console Application) Delphi compilado para Linux?
Quero fazer um projeto para rodar como serviço com Horse para gerar um PDF feito em FortesReport, mas queria saber se há suporte para compilação Linux em Delphi
Obrigado!

**Comment by clusterdevm** [comment]
Ja tentei, mas não consegui fazer rodar não

**Comment by juliomar** [comment]
não é possível pois depende de questões gráficas
no server vai precisar do ambiente gráfico

**Comment by dopidaniel** [comment]
Veja sobre Xvfb
https://www.projetoacbr.com.br/forum/topic/57850-como-criar-aplica%C3%A7oes-console-com-acbr-e-lazarusfpc/?do=findComment&comment=411908&_rid=61
