### ISSUE TITLE
Thread-safe

### ISSUE THREAD

**Issue by arvanus** [fortesinformatica/fortesreport-ce#282]
Já tive alguns problemas com relatorios sendo gerados e salvos em PDF em threads separadas, além de isolar a geração do PDF em processos separados, ou colocar todo o processo em sessões críticas, os DEVs do projeto tem alguma outra dica mais simples e/ou eficiente?
PS.: Não sei dizer se o problema é no filtro PDF, ou no report em sí...

**Comment by juliomar** [comment]
a principio esse é o caminho já que precisa que fique sendo gerado simultaneos.
