### ISSUE TITLE
Epson Tm-t20

### ISSUE THREAD

**Issue by clusterdevm** [fortesinformatica/fortesreport-ce#283]
Estou com problema na impressão com impressoras Epson,  com a Bematech funciona certinho quando tenho muitos itens em um cupom a pagina corta na impressora Epson, no preview esta ok somente na impressão como se o tamanho maximo de pagina aceita pela Epson fosse A4 

   RLLayout.PageBreaking := pbNone;
   RLLayout.PageSetup.PaperSize   := fpCustom ;
   RLLayout.PageSetup.PaperHeight   := 400;
   RLLayout.PageSetup.PaperWidth   := 80;
   RLLayout.UnlimitedHeight  :=  true;

**Comment by clusterdevm** [comment]
up?

**Comment by juliomar** [comment]
Tentou deixar autosize o mesmo ?
usamos no projeto ACBr para essa finalidade não temos relato. tente verificar os fontes do Projeto e ver se consegue encontrar o ponto
