### ISSUE TITLE
Adição de Nova Propriedade

### ISSUE THREAD

**Issue by alimasilva2018** [fortesinformatica/fortesreport-ce#284]
[Source.zip](https://github.com/fortesinformatica/fortesreport-ce/files/6727670/Source.zip)

Juliomar para sua apreciação, eu adicionei a propriedade InitialDir ao RLPreviewSetup.

Tive essa necessidade no ACBr pois uns clientes queriam salvar não no path ou nome definido mas na area de trabalho e com nome a gosto.

Com isso não precisa mexer nos fontes do ACBr basta colocar o RLPreviewSetup.

Se entender que traz beneficio, poderia por favor adicionar aos fontes. 

Obrigado.

**Comment by juliomar** [comment]
consegue fazer um pull request com a alteração? assim consigo aqui mesmo tratar
