### ISSUE TITLE
Instalação com Delphi 2006

### ISSUE THREAD

**Issue by vcintra** [fortesinformatica/fortesreport-ce#286]
Pessoal estou tentando fazer a instalação no Delphi 2006 e recebo o seguinte erro.

Borland Delphi for Win32 compiler version 18.0
Copyright (c) 1983,2005 Borland Software Corporation
C:\workspace\fortesreport-ce\Source\RLMetaVCL.pas(681) Error: E2072 Number of elements (11) differs from declaration (9)
C:\workspace\fortesreport-ce\Source\RLMetaFile.pas(1068) Fatal: F2063 Could not compile used unit 'RLMetaVCL'
Compilation failure

**Comment by juliomar** [comment]
Isso via instalador? 
olha no delphi 2006 quantos enumeradores tem TPenStyle

**Comment by vcintra** [comment]
Foi via instalador.

**Comment by juliomar** [comment]
por favor se conseguir corrigir e enviar um pull request
