### ISSUE TITLE
Problema com TDBRichText e textos com formatações

### ISSUE THREAD

**Issue by tiagofr1986** [fortesinformatica/fortesreport-ce#29]
Estou a usar Delphi7 com a ultima versão do FortesReport aqui disponibilizado.
Num relatório que preciso gerar utilizado um TDBRichText 'Linkado' a um campo blob de base de dados.
Quando o campo tem texto simples, o texto é apresentado corretamente no preview do relatório.
Quando o campo tem texto com itálico, o texto nao é apresentado corretamente no preview. O que acontece é que o texto imediatamente antes ou depois do itálica fica sobreposto ao texto em itálico.
Outro problema são linhas em branco, o TDBRichText parece 'comer' as linhas em branco e o texto é apresentado todo seguido.
Estas duas situações, para além de se manifestarem no preview do relatório, também afetam a exportação do relatório para PDF, acontece o mesmo que no preview.

Neste momento não estou em condições de enviar capturas de tela para mostrar o que tentei explicar. Se sentirem duvidas, posso tentar arranjar umas capturas e enviar para vocês verem.

Obrigado,
Tiago França
Portugal

**Comment by marciomartins** [comment]
Olá, Tiago França.
Você poderia nos enviar um exemplo deste RTF para que possamos analisar?
Obrgiado.

Márcio Martins

**Comment by tiagofr1986** [comment]
Ola Amigo,

Envio em anexo umas capturas de tela, para além do RTF.

 

Isto é como se pretende que o texto apareça no relatório:

 

RichEdit.png

 

No Relatório gerado pelo Fortes, as formatações parecem confundir os cálculos de tamanho das letras e as linhas em branco desaparecem:

 

RichEdit FR.png

 

Em anexo, segue então o RTF.

 

Agradecido pela atenção,

Tiago França

 

 

De: Marcio Martins [mailto:notifications@github.com] 
Enviada: 18 de setembro de 2015 21:13
Para: fortesinformatica/fortesreport-ce
Cc: tiagofr1986
Assunto: Re: [fortesreport-ce] Problema com TDBRichText e textos com formatações (#29)

 

Olá, Tiago França.
Você poderia nos enviar um exemplo deste RTF para que possamos analisar?
Obrgiado.

Márcio Martins

—
Reply to this email directly or view it on GitHub <https://github.com/fortesinformatica/fortesreport-ce/issues/29#issuecomment-141554772> .  <https://github.com/notifications/beacon/ANq0JShB8ORUeZN1mX4deFyUVCpSclWLks5ozGexgaJpZM4F_PYe.gif> 


{\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\colortbl ;\red0\green0\blue0;}
\viewkind4\uc1\pard\cf1\lang2070\fs20 Num fundo de col\'f3ide abundante, observam-se c\'e9lulas foliculares pequenas, \cf0\i sem particularidades nucleares\cf1\i0 , dispersas ou em agregados de \cf0\b configura\'e7\'e3o vari\'e1vel e macr\'f3fagos\cf1\b0 .
\par 
\par Um linha em branco antes desta.
\par 
\par 
\par Duas linhas em branco antes desta.
\par Fim
\par }

**Comment by marciomartins** [comment]
Bom dia.
Não veio os anexos.
Você poderia me passar por email?

mm.marciomartins@gmail.com

**Comment by tiagofr1986** [comment]
Boa tarde Marcio,
Eu enviei um mail com os anexos mas não sei se chegou a receber...
Recebeu?

Obrigado,
TF

**Comment by marciomartins** [comment]
Recebi, realmente havia um problema com a quebra de linha e foi corrigido pelo @ronaldoxgh 
Porém não conseguimos ver outros problemas.
Favor baixar a nova versão.

**Comment by tiagofr1986** [comment]
Ola Marcio,
Muito obrigado pelo feedback.
As quebras de linha estão resolvidas, mas o textos com formatações ainda se sobrepõem uns aos outros.

Obrigado,
Tiago França
