### ISSUE TITLE
Fonte no RLmemo mudando durante impressão

### ISSUE THREAD

**Issue by jburda** [fortesinformatica/fortesreport-ce#290]
Estou tendo problemas na impressão de um RLmemo, pois conforme o computador que efetua a impressão, o relatório sai com a fonte correta (courier), em outros, sai como Arial, também
Já tentei várias configurações, e não consigo solucionar,

seguem imagens da visualização e impressão no notebook e no computador
![notebook-visualização](https://user-images.githubusercontent.com/25982707/132589805-b4484b86-3d02-4f9b-bb8d-753442eb5928.png)
**VISUALIZAÇÃO NO NOTEBOOK**

![Notebook - impressão](https://user-images.githubusercontent.com/25982707/132589814-84f0663f-c956-41cc-a37c-c98f4baf90b5.png)
**IMPRESSÃO DO NOTEBOOK - IMPRESSORA HP P1005**

![Servidor - visualização](https://user-images.githubusercontent.com/25982707/132589828-c3ec2c25-497c-43b5-bb00-7a280afd7b81.png)
**VISUALIZAÇÃO NO COMPUTADOR**

![Servidor - Impressão](https://user-images.githubusercontent.com/25982707/132589834-2d89dad1-92eb-4e0e-8778-d71897048b55.png)
**IMPRESSÃO DO COMPUTADOR- IMPRESSORA HP P1005**

**Comment by juliomar** [comment]
a fonte tem que ser monospace
