### ISSUE TITLE
Senha em arquivos PDF

### ISSUE THREAD

**Issue by dnatividade** [fortesinformatica/fortesreport-ce#291]
Olá.
Utilizo o Fortes Report em conjunto com o ACBr para emissão de boletos.

Estou com uma demanda para colocar senha nos arquivos PDF gerados, mas vi em um fórum que o Fortes não implementa essa função. Isso procede? Vocês tem alguma previsão de implementar esse recurso?
Acho válido pois este método de senha em boletos tem sido usado por grandes empresas.

Obrigado pela atenção.

**Comment by juliomar** [comment]
Olha não temos previsão pois é um projeto aberto e é feito conforme a demanda.
caso queira contribuir faça um pull request
