### ISSUE TITLE
Tela fica "deformada" quando usar opção de salvar impressora Microsoft Print to pdf

### ISSUE THREAD

**Issue by DiegoJBPires** [fortesinformatica/fortesreport-ce#294]
Ao imprimir o relatorio do fortes Report, quando uso a impressora que tenho no windows, "Microsoft Print to pdf", aparece assim.
![Erro](https://user-images.githubusercontent.com/94862483/142913132-70126e5b-d9a4-4b36-a34f-3c566b582919.JPG)

**Comment by juliomar** [comment]
XPmanifest em sua aplicação

**Comment by juliomar** [comment]
além do skin que está a usar
