### ISSUE TITLE
PDF errors on HiDPI displays (with fix)

### ISSUE THREAD

**Issue by daniel-rikowski** [fortesinformatica/fortesreport-ce#296]
I hope posting in English is ok... Also I apologize if this is a duplicate, Google Translate doesn't seem to like Github...

In RLPDFFilter.pas in `TRLPDFFilter.WriteFonts`, the individual character widths are determined using `FontGetMetrics`.
On FreePascal `GetCharWidth` is used, on Delphi or Linux `Canvas.TextWidth` is used. Unfortunately both methods take the current screen pixel density into account, i.e. the character widths get larger with higher screen density. The PDF format on the other hand uses the a fixed measurement, i.e. the default PostScript measurements of 72pt = 1in.

So when the PDF is generated on a HiDPI display the generated PDF file has wrong fonts widths, resulting in large gaps between individual characters when displayed (even on the same HiDPI display, because the viewing programs (correctly) scale up the already scaled font widths)

A possible solution is to normalize the font widths and "revert" the HiDPI scaling. In RLPDFFilter.pas around line 1483:

Replace:
```delphi
Write(IntToStr(rec.Widths[J]) + ' ');
```

with:
```delphi
Write(IntToStr(MulDiv(rec.Widths[J], 96, ScreenPPI)) + ' ');
```

That way the widths are written as they would be on a regular display. For other displays that MulDiv expression resolves to `MulDiv(rec.Widths[J], 96, 96) = MulDiv(rec.Widths[J], 1, 1) = rec.Widths[J]` which is the current behaviour, so there is no change for regular 96 PPI screens.

I could only test this on FreePascal 3.3.1/Lazarus 2.3.0 and on Windows, but I also checked the Delphi path, because the `Canvas.TextWidth` code path also works on FreePascal (at least on my version). I have no idea why `GetCharWidth` is used for FreePascal on Windows, perhaps it was a workaround for an earlier bug? 

I can open a pull request for that change, but since it is a one-liner perhaps it is not necessary?

Thank you for this great software!

**Comment by dopidaniel** [comment]
Thanks for your time investigating this problem... 

I believe your propose will run on D7-DAlexandria and Lazarus (Win/Linux)...

Please submit a pull request, I can help on testing it on different environments...
