### ISSUE TITLE
imprime lentamente em impressora HP

### ISSUE THREAD

**Issue by rogeriojlle** [fortesinformatica/fortesreport-ce#3]
Olá.
Na empresa onde trabalho, nosso ERP usa esse componente para gerar relatórios. 
Quando vamos imprimir nas impressoras HP ( LaserJet Pro 400 ) o processo é muito lento ( outras impressoras e aplicativos imprimem rápido ), contactei o suporte do fornecedor do ERP, mas ficou naquela "o problema é na tua impressora", contactei quem me dá suporte na impressora e recebi resposta "inversa".
Não estou afirmando que o problema está no Fortes Report, na verdade gostaria de saber se alguém teve situação semelhante e se teve solução, para compartilhar aqui.
O fornecedor de nosso ERP está nesse endereço: http://g1sistemas.com.br

**Comment by marciomartins** [comment]
Desculpe a demora, você ainda está com o problema?

**Comment by rogeriojlle** [comment]
sim, ainda persiste, nesse período, amenizei o problema imprimindo via compartilhamento pelo cups, dessa forma é mais rápido, mas dependo de um servidor de impressão linux
