### ISSUE TITLE
Número de cópias com problemas

### ISSUE THREAD

**Issue by CarlosTedEx** [fortesinformatica/fortesreport-ce#30]
Boa tarde,

Ao utilizar o recurso de <b>Número de Cópias</b> está ocorrendo o seguinte problema:

Exemplo: Caso seja solicitado a impressão de 2 cópias está sendo impressa 4, ao imprimir 3 está sendo impressa 9 páginas.

Grato pela atenção!

**Comment by marciomartins** [comment]
Boa tarde Carlos, você está usando a versão atual (master)?
Realmente es problema existiu.

**Comment by CarlosTedEx** [comment]
Bom dia Marcio, estou utilizando a versão "FortesReport Community Edition 4.0" (https://github.com/fortesinformatica/fortesreport-ce/)

**Comment by marciomartins** [comment]
Bom dia, mas está atualizada? com os commits mais recentes?
Pois esse problema já foi corrigido.

**Comment by CarlosTedEx** [comment]
Márcio, acabai de fazer a atualização do componente para revisão **88** mas o problema persiste. Segue algumas informações para que você verifique se estou fazendo algo de errado na instalação do mesmo.

1) Estou utilizando o pacote para **Delphi 7** (D:\TEMP\COMPONENTES\FortesReportCE\trunk\Packages\FortesReportCE_Win32_D7_vcl.dpk)

2) Depois clico em Compile e Install

3) E por ultimo faço a inclusão deste caminho no Library Path do Delphi
**D:\TEMP\COMPONENTES\FortesReportCE\trunk\Source**

Grato pela atenção!

**Comment by CarlosTedEx** [comment]
Prezado Marcio, percebi que o post está fechado, porem ainda o problema persiste. Como o post está fechado você sugere abrir outro comentando a respeito deste problema ou você pode reabrir este?

**Comment by denerbuzato** [comment]
Boa tarde Carlos,

Também estou enfrentando os mesmos problemas com impressão dos relatórios quando solicitado mais de uma cópia. Caso tenha encontrado alguma solução, favor postar aqui pois a cobrança deste item está sendo grande.

Estou utilizando a versão do fortesreport mais recente (versão 88), inclusive atualizei hoje para testar se já foi resolvido e nada.

https://github.com/fortesinformatica/fortesreport-ce/

Grato!

**Comment by CarlosTedEx** [comment]
Bom dia Dener,

Continuo com o mesmo problema e estou no aguardo do retorno do Márcio.
