### ISSUE TITLE
Adicionar URL para acesso externo

### ISSUE THREAD

**Issue by lsjack93** [fortesinformatica/fortesreport-ce#302]
É possível adicionar um link url (talvez pelo TRLLabel) para abrir no navegador?

**Comment by zrfisaac** [comment]
Acredito que em documentos PDF Excel e Word isso é possivel, acredito quando possível ele queira isso, a não ser que seja RTF que aí não tem como.

**Comment by lsjack93** [comment]
isso, um texto contendo um link dentro do arquivo PDF...
olhando os códigos, acredito não ser possível, pois é gerado como se fosse um canvas... talvez de certo na exportação para PDF
