### ISSUE TITLE
Erro de violação de acesso ao fechar relatorio aberto com previewmodal

### ISSUE THREAD

**Issue by drummondsp** [fortesinformatica/fortesreport-ce#305]
Boa tarde.

Ha alguns dias, venho recebendo o erro de Access Violation, quando fecho um relatorio aberto em previewmodal.  Se abrir apenas com o preview, não apresenta o erro.

Porém, preciso que seja modal, para que os filtros do rlreport funcionem, pois notei que quando abro em modal, eles ficam indisponíveis...

Obrigado...

**Comment by juliomar** [comment]
Use um dos exemplos e explique como reproduzir. também versão do delphi e windows que está usando assim podemos tentar entender o erro

**Comment by juliomar** [comment]
falta de retorno fechado
