### ISSUE TITLE
Erro ao salvar exportar arquivo PDF/EXCEL no Fortes Report

### ISSUE THREAD

**Issue by pericles-salmazzi** [fortesinformatica/fortesreport-ce#307]
Estou com um problema que não consegui identificar muito bem a solução.

Tentarei ser breve para descrever a ocorrência:

Após gerar um relatório comum, sem muitas informações, tento exportar-lo através do botão "Salvar" do Fortes Report, a janela de exportação então é aberta perguntando o formato (PDF/EXCEL/Padrão) e o local para salvar o arquivo. Ao tentar mudar o diretório AS VEZES é apresentado um "erro genérico do delphi" aqueles "access memory 008...." e mesmo assim funciona, porém AS VEZES o programa "crasha" e o windows identifica informando "o programa parou de funcionar". 

Resumindo, ao mudar o diretório do arquivo e voltar para o Fortes Report acontece esse problema de travar todo o programa. Mesmo tentando exportar em PDF ou mesmo EXCEL o problema é gerado.

Versão do Fortes Report: 4.0.0.1 VCL

Atenciosamente,
Péricles Salmazzi

**Comment by juliomar** [comment]
Versão do Delphi? Versão do windows?
rode um dos exemplos e tente fazer ocorrer o mesmo

**Comment by pericles-salmazzi** [comment]
Versão do Delphi: 10.4.2.
SO: Windows 7 64 bits Ultimate. (Mas acontece em outros windows também, inclusive o w10) .

Vou tentar rodar os exemplos para ver se tem o mesmo efeito.

Atenciosamente,

**Comment by pericles-salmazzi** [comment]
Atualizando!

Encontrei o "problema". Após mais testes,  identifiquei a seguinte questão:

Se no momento de exportar o relatório eu NÃO ALTERAR o caminho para salvar, o relatório é salvo 100% corretamente na pasta raiz do executável! ENTRETANTO se eu ALTERAR o caminho para salvar o relatório e escolher uma pasta qualquer a aplicação "crasha" como mencionado anteriormente! (inclusíve se eu escolher a própria pasta do projeto onde encontra-se o executável)

Resumindo, o problema está ao ALTERAR O CAMINHO PARA SALVAR O RELATÓRIO, TANTO EM EXCEL COMO PDF!

Espero ter ajudado a encontrar o problema,

Atenciosamente,
Péricles Salmazzi

**Comment by juliomar** [comment]
Certo. e conseguiu fazer a correção? se sim envia o pull request

**Comment by juliomar** [comment]
Quando fizer envia o pull request.
