### ISSUE TITLE
Opção Preview não carrega as opções de filtro para salvar (PDF, XLS,...)

### ISSUE THREAD

**Issue by eadveira** [fortesinformatica/fortesreport-ce#308]
Quando visualizo o relatório usando o comando RLReport1.Preview() não carrega as opções de filtro para salvar (PDF, XLS,...),

só carrega os filtros se eu usar o comando RLReport1.PreviewModal.

Versão: 4.0.0.1

**Comment by vgborges** [comment]
Você está informando ao relatório que ele deve ter aquela impressão ao gerar o preview ? 
![image](https://user-images.githubusercontent.com/110197392/184446053-bb2e9d00-56f4-402c-9a7a-a4d9b84df4e4.png)
Você deve colocar aquele ícone de pdf ou outro que precise no corpo do relatório (Ou todos), assim ao gerar o preview e quiser salvar ele vai trazer a extensão .PDF (Ou todas as que escolheu)

Uso o FortesReport no Lazarus IDE 2.2.2

**Comment by hamacker** [comment]
Mesmo com os componentes de filtros adicionados ao formulário a opção de filtro na janela de dialogo não aparece outros filtros. Foi testado também a opção DefaultFilter para fixar PDF ou XLS e com o mesmo resultado. Realmente apenas com PreviewModal os filtros aparecem. Testado com o Delphi 11 update1.

**Comment by eadveira** [comment]
Uma coisa que acabei de constatar

Adicionei os filtros no Form2 e chamo o preview pelo Form1
Form2.RLReport1.Preview();
- Não mostra as opções de filtro quando tento salvar
Form2.RLReport1.PreviewModal;
- Mostra as opções de filtro quando tento salvar

Se eu adicionar os filtros no Form1 e deixar os filtros no Form2
Form2.RLReport1.Preview();
- Mostra as opções de filtro quando tento salvar
Form2.RLReport1.PreviewModal;
- No combo onde lista as opções de filtro fica duplicado as opções de filtro quando tento salvar

**Comment by juliomar** [comment]
Conseguiram verificar como resolver ou como chamar. por favor enviar pull request.

**Comment by hamacker** [comment]
É complicado juliomar, até agora não entendi porque ele esta acontecendo.
No Lazarus, testei e tá funcionando.

**Comment by juliomar** [comment]
> É complicado juliomar, até agora não entendi porque ele esta acontecendo. No Lazarus, testei e tá funcionando.

Certo. se achar a solução e quiser fazer um pull request com a correção
