### ISSUE TITLE
Não retorna a quantidade total de paginas depois da execução do método prepare.

### ISSUE THREAD

**Issue by manoelguedess** [fortesinformatica/fortesreport-ce#310]
As propriedades de controles de paginas não estão retornando corretamente.

- RLReport1.Pages.LastPageNumber;
- RLReport1.Pages.PageCount;

procedure Trel.Run;  
  var ALastPageNumber,
      APageCount,
      APageNumber,
      APageIndex: Integer;
begin
  RLReport1.Prepare;
  ALastPageNumber :=  RLReport1.Pages.LastPageNumber;
  APageCount :=  RLReport1.Pages.PageCount;
  APageNumber :=  RLReport1.PageNumber;
  APageIndex :=  RLReport1.PageIndex;
  RLReport1.PreviewModal;
  (*
    Valores das variaveis:
	=====================
	ALastPageNumber = 0
	APageCount = 0
	PageIndex = 0
	APageNumber = 0
  
  *)
end;  

procedure Trel.RLReport1BeforePrint(Sender: TObject;
  var PrintIt: Boolean);
  var ALastPageNumber,
      APageCount,
      APageNumber,
      APageIndex: Integer;
begin
  ALastPageNumber :=  RLReport1.Pages.LastPageNumber;
  APageCount :=  RLReport1.Pages.PageCount;
  APageNumber :=  RLReport1.PageNumber;
  APageIndex :=  RLReport1.PageIndex;
  (*

    Valores das variaveis:
	=====================
	ALastPageNumber = 0
	APageCount = 0
	PageIndex = -1
	APageNumber = 0
  *)
end;

**Comment by juliomar** [comment]
Conseguiu verificar o que ocorre para gerar o problema?
