### ISSUE TITLE
Impossible install x64 version ...'missing DesignIde package'

### ISSUE THREAD

**Issue by ramosvega** [fortesinformatica/fortesreport-ce#311]
when i delete Designide from proyect the package format is incorrect...
i think the fortes report can´t be installed on x64.

leave a copy of the log file after delete Designide from uses :
"Caminho: C:\componentes\FortesReport\trunk\
Versão do delphi: Delphi 10.3 Rio (0)
Plataforma: Win64(1)
================================================================================
Setando parâmetros de plataforma...
Criando diretórios de bibliotecas...
Adicionando library paths...

Compiling package C:\componentes\FortesReport\trunk\Packages\frce.dpk
"C:\Program Files (x86)\Embarcadero\Studio\20.0\bin\dcc32.exe" "C:\componentes\FortesReport\trunk\Packages\frce.dpk" --no-config -B -$O- -$W+ -$Y- -M -Q -H- -W- -DRELEASE -U"C:\Program Files (x86)\Embarcadero\Studio\20.0\lib\Win64\release" -U"c:\program files (x86)\embarcadero\studio\20.0\lib\Win64\release;C:\Users\maria\OneDrive\Documentos\Embarcadero\Studio\20.0\Imports;c:\program files (x86)\embarcadero\studio\20.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\20.0\include;C:\componentes\DevExpressVCL19.1.2\Library\RS26\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Lib\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Bin\Win64;F:\fortesreport-ce-master\Binary\LibD26x64;C:\Program Files (x86)\FastReport 6 VCL Enterprise\LIBD26x64;F:\fortesreport-ce-master\Source;F:\fortesreport-ce-master;F:\fortesreport-ce-master\Packages;F:\fortesreport-ce-master\Binary;F:\fortesreport-ce-master\Packages\CBuilderXE10.2\Win32\Release;F:\reportman_delphi_3_4_12a\packages\10.3\Win32\Debug;C:\componentes\FortesReport\trunk\Binary\LibD26x64;C:\componentes\FortesReport\tags\v4.0.0.2\Binary\LibD26x64" -U"C:\componentes\FortesReport\trunk\Binary\LibD26x64" -I"c:\program files (x86)\embarcadero\studio\20.0\lib\Win64\release;C:\Users\maria\OneDrive\Documentos\Embarcadero\Studio\20.0\Imports;c:\program files (x86)\embarcadero\studio\20.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\20.0\include;C:\componentes\DevExpressVCL19.1.2\Library\RS26\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Lib\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Bin\Win64;F:\fortesreport-ce-master\Binary\LibD26x64;C:\Program Files (x86)\FastReport 6 VCL Enterprise\LIBD26x64;F:\fortesreport-ce-master\Source;F:\fortesreport-ce-master;F:\fortesreport-ce-master\Packages;F:\fortesreport-ce-master\Binary;F:\fortesreport-ce-master\Packages\CBuilderXE10.2\Win32\Release;F:\reportman_delphi_3_4_12a\packages\10.3\Win32\Debug;C:\componentes\FortesReport\trunk\Binary\LibD26x64;C:\componentes\FortesReport\tags\v4.0.0.2\Binary\LibD26x64" -R"c:\program files (x86)\embarcadero\studio\20.0\lib\Win64\release;C:\Users\maria\OneDrive\Documentos\Embarcadero\Studio\20.0\Imports;c:\program files (x86)\embarcadero\studio\20.0\Imports;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64;c:\program files (x86)\embarcadero\studio\20.0\include;C:\componentes\DevExpressVCL19.1.2\Library\RS26\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Lib\Win64;C:\Program Files (x86)\Devart\MyDAC for RAD Studio 10.3\Bin\Win64;F:\fortesreport-ce-master\Binary\LibD26x64;C:\Program Files (x86)\FastReport 6 VCL Enterprise\LIBD26x64;F:\fortesreport-ce-master\Source;F:\fortesreport-ce-master;F:\fortesreport-ce-master\Packages;F:\fortesreport-ce-master\Binary;F:\fortesreport-ce-master\Packages\CBuilderXE10.2\Win32\Release;F:\reportman_delphi_3_4_12a\packages\10.3\Win32\Debug;C:\componentes\FortesReport\trunk\Binary\LibD26x64;C:\componentes\FortesReport\tags\v4.0.0.2\Binary\LibD26x64" -N0"C:\componentes\FortesReport\trunk\Binary\LibD26x64" -LE"C:\componentes\FortesReport\trunk\Binary\LibD26x64" -LN"C:\componentes\FortesReport\trunk\Binary\LibD26x64" -NS"Winapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell"
Embarcadero Delphi for Win32 compiler version 33.0
Copyright (c) 1983,2018 Embarcadero Technologies, Inc.
frce.dpk(46) Fatal: E2213 Bad packaged unit format: C:\Program Files (x86)\Embarcadero\Studio\20.0\lib\Win64\release\rtl.dcp.System - Expected version: 33.0, Windows Unicode(x86) Found version: 33.0, Windows Unicode(x64)
Compilation failure"

**Comment by juliomar** [comment]
the installer does not compile for x64. you must install win32 because the delphi IDE is, and it will set the path in the x64 library for you to use
