### ISSUE TITLE
Conexão com uma Database Firebird 2.0 

### ISSUE THREAD

**Issue by vgborges** [fortesinformatica/fortesreport-ce#312]
Estou tendo dificuldades ao conectar m uma banco de dados 2.0 do firebird, já fiz uma conexão com um banco 3.5 e não tive problemas, o que poderia ser ? 

Uso o Lazarus IDE 2.2.2

**Comment by juliomar** [comment]
Não tem a ver com o fortes report. o problema está em uso de componentes de acesso a dados e firebird.
