### ISSUE TITLE
Corte no lado esquerdo impressão pos80taicon na NFC 

### ISSUE THREAD

**Issue by absint93** [fortesinformatica/fortesreport-ce#313]
Já tentamos de tudo, a empresa com os técnicos a qualidade. E simplesmente quando salvo em PDF e imprimo normalmente pelo Chrome ou Edge, sai 100% 

Agora se tentar imprimir pelo fortes. Sai faltando uns 3Cmno lado esquerdo do cupom.

É pelo nfc
Impressora taicon pos80 pl500

Tentamos de tudo e realmente deve ser alguma configuração do sistema que está quebrando lateralmente...na pré visualização está ok... O problema é quando imprime mesmo.

**Comment by juliomar** [comment]
NFC? 
bom se estiver falando em emissão de documento fiscal tente informar as margens em tempo de execução

**Comment by juliomar** [comment]
falta de retorno
