### ISSUE TITLE
Não exporta para Excel

### ISSUE THREAD

**Issue by jerrivaldo** [fortesinformatica/fortesreport-ce#314]
ele salva o arquivo em excel mas o excel não consegue abrir o arquivo. Quando tento abrir o arquivo no excel aparece a seguinte mensagem: 'Arquivo.xls' não pode ser acessado. O arquivo pode estar corrompido

**Comment by juliomar** [comment]
consegue anexar um exemplo de como está fazendo?

**Comment by juliomar** [comment]
falta de retorno
