### ISSUE TITLE
Alinhamento vertical RLDBMemo

### ISSUE THREAD

**Issue by danielfrivas** [fortesinformatica/fortesreport-ce#315]
Nos componentes RLDBText e RLLabel existe a propriedade Layout que alinha o texto na vertical. No componente RLDBMemo também tem essa propriedade, mas nada acontece com o texto quando o valor é alterado para tlCenter ou tlBottom.

**Comment by juliomar** [comment]
Creio que não foi implementado nesse componente.
mas caso queira implementar e enviar o pull request.
