### ISSUE TITLE
TRLRichEdit \b casuando quebra de linha

### ISSUE THREAD

**Issue by IagooCesaar** [fortesinformatica/fortesreport-ce#317]
Quando uma palavra ou frase é formatada com negrito (\b .. \b0) está ocorrendo uma quebra de linha.

Veja trecho:
> \line \'c9 importante que este pagamento seja efetuado\b imediatamente\b0, pois o processo de cobran\'e7a j\'e1 foi encaminhado para a nossa {\b\'e1rea jur\'eddica\b0} .

![image](https://user-images.githubusercontent.com/12894025/196684626-bed40393-3922-4c84-b0f1-2c0f8f0d6cc4.png)

**Comment by IagooCesaar** [comment]
Percebi agora que não foi especificamente o **\b**, mas qualquer \ está provocando a quebra

**Comment by IagooCesaar** [comment]
Analisei o fonte, especificamente na unit RLRichText. O problema parece estar no método **RichTextParse**, no seguinte trecho (aprox. linha 722):

```pascal
if (TokenText <> '') or (LevelSets[Level].Alignment <> MetaTextAlignmentLeft) then
begin
  Inc(TextPos.Y, LineHeight);
  TextPos.X := ARect.Left;
  MustResetLineHeight := True;
end;
```

Meu texto apresenta alinhamento justificado, o que é diferente de _MetaTextAlignmentLeft_, o que está forçando resetar a altura da linha. 
Ou seja, cada nova sequência "Literais" está obtendo uma nova posição Y para impressão do texto.

**Comment by IagooCesaar** [comment]
Apenas removendo a condicional do alinhamento o texto parou de ser quebrado em linhas. Acredito que teria de implementar algo como "somente quebrar linha se for EndOfLine.. 

Contudo, isto fez com que uma nova questão surgisse: espaços demasiados entre palavras. 
![image](https://user-images.githubusercontent.com/12894025/196962822-227b3125-bd11-4bb7-a211-acf08c430c87.png)
Isto ocorre mesmo forçando alinhamento à esquerda

**Comment by juliomar** [comment]
envia o pull request
