### ISSUE TITLE
Erro ao imprimir no fortes report

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#32]
Boa tarde,
Estou com um problema, ao imprimir um relatorio, clicando no botão imprimir, ao escolher o numero de copias, se eu escolher 2 está imprimindo 4 paginas, e eu escolher 3 imprime 9 paginas e assim sucessivamente. 

Grato

**Comment by dbrida** [comment]
Estamos com o mesmo problema, no aguardo...

**Comment by CarlosTedEx** [comment]
Também estou no aguardo!

**Comment by denerbuzato** [comment]
Estou na expectativa desta solução também, no aguardo...

**Comment by monarim** [comment]
Mesmo problema... mais de uma cópia com problema

**Comment by CarlosTedEx** [comment]
Bom dia pessoal,

Este problema esta sendo resolvido neste fórum também.

http://www.projetoacbr.com.br/forum/topic/24552-no-imprimir-nfe-se-enviar-2-copias-imprime-4-copias/?page=1

**Comment by denerbuzato** [comment]
OK! Obrigado!

**Comment by marciomartins** [comment]
Favor atualizar para a versão corrente.
Preferencialmente usar o instalador.

**Comment by CarlosTedEx** [comment]
Agora tá ok.
Obrigado!
