### ISSUE TITLE
Quebra de linha com texto sem espaço - TRLMemo/TRLDBMemo

### ISSUE THREAD

**Issue by weberdepaulai12** [fortesinformatica/fortesreport-ce#320]
Pessoal, boa tarde,

Atualmente se colocarmos um texto no TRLMemo sem espaço, o componente não faz a quebra de linha. Isso é muito comum em links como foi no meu caso.
No link de exemplo (abaixo), não ocorre a quebra de linha, mesmo como as propriedades WordWrap=True, AutoSize=True e etc;

Link de exemplo
 https://www.google.com/search?q=word+wrap+fortes+report&sxsrf=ALiCzsYhD5ggk1owjteuvje0xQsUkvvX2A%3A1669297474767&ei=QnVY4CsLqrL1sQP85mOSAved0ahUKEwiA1YfY-cb7AhWqpZUCHfOMAwkQ4dUDCA85&oq=word+wrap+fortes+report&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAEyBQghEKABMgUIIRCgAToECCMQJzoECAAQQzoFCAAQgAQ6CwguEIAEEMcBENEDOgUIABCRAjoFCC4QgAQ6CAguEIAEENQCOgcILhDUAhBDOgQILhBDOgcIIxCxAhAnOgcIABCABBAKOhAILhCABBDHARDRAxDUAhAKOgcIIxDqAhAnOg4ILhCABBDHARDRAxDUAjoKCAAQgAQQhwIQFDoGCAAQFhAeOggIABAWEB4QDzoKCCEQFhAeEA8QHToHCCEQoAEQCkoECEEYAEoECEYYAFAAWOhEYI1GaAJwAXgAgAHMAYgBriKSAQYwLjI1LjGYAQCgAQGwAQrAAQE&sclient=gws-wiz-serp

Fazendo um debug no componente, vi que no arquivo Source\RLConsts.pas na linha 81 existe a constante:

`SOFT_LINEBREAK = [#9,' ','-','.',',']; // TAB`

Adicionando mais opção de quebra resolveu o caso de quebra de link.

`SOFT_LINEBREAK = [#9,' ','-','+','=',#47,'/',',','&',#38,'a','A','e','E','i','I','O','o','U','u','_']; // TAB`

Gostaria de solicitar a análise e estiverem de acordo que façam o merge em produção.

Desde já obrigado.

**Comment by juliomar** [comment]
envia o pull request para verificarmos
