### ISSUE TITLE
Erro de visualização de campo RichEdit - rtf no Fortes

### ISSUE THREAD

**Issue by Nivaldo28** [fortesinformatica/fortesreport-ce#325]
Bom Dia.
Tenho um projeto que faz impressão de contratos. Na maioria das vezes, os contratos são copiados do Word para o TRichEdit e as configurações de letras, cores e alinhamentos, aparece perfeitamente no componente. O problema acontece quando mando visualizar esse conteúdo no Fortes. Algumas configurações desconfiguram o relatório, tais como:
- Ao centralizar um texto, automaticamente aparece uma linha em branco a mais abaixo do texto;
- Parágrafo que começam com "Tab / Espaçamento" são desconsiderados na visualização;
- Aparecem numerações no corpo do texto inexistentes, tais como: -360, -45, -90
Segue o link de um print para entender melhor.
https://1drv.ms/u/s!AiHaA21m7v7_g4wgBQ89OqbYQqgvVA?e=pQCJhF
...
Pesquisei sobre o assunto e cheguei a duas conclusões possíveis:
1º Configuração da font CHARSET, tentei mudar isso no richedit e no report, mas não resolveu, ou,
2º Configuração rtf que não contenham no forte para fazer a transformação do conteúdo, pois analisando o arquivo rtf original, consigo identificar as siglas que geral esses erros.
Se precisar fiz, uma tela que exemplifica essas situações, se precisar me avise e envio.
...
Já estou a algum tempo procurando uma solução para esse problema e sem sucesso.
Agradeço muito se conseguirem me ajudar.

**Comment by juliomar** [comment]
anexe um projeto de exemplo e documentos para poder ver

**Comment by Nivaldo28** [comment]
Segue um projeto que gera o problema que comentei.
[Impressao_Rich.zip](https://github.com/fortesinformatica/fortesreport-ce/files/11009183/Impressao_Rich.zip)
.

**Comment by SuporteSysrs01** [comment]
A tag `\stylesheet` do padrão RTF também não é lida corretamente pelo Fortes. Ao copiar um Word que contenha headings, como Heading 1, por exemplo, o seguinte RTF é gerado:
```rtf
{\rtf1\fbidis\ansi\ansicpg1252\deff0\deflang1046{\fonttbl{\f0\fswiss\fprq2\fcharset0 Calibri Light;}{\f1\fnil\fcharset0 Arial;}}
{\colortbl ;\red47\green84\blue150;}
{\stylesheet{ Normal;}{\s1 heading 1;}}
\viewkind4\uc1\pard\ltrpar\keep\keepn\s1\sb240\sl252\slmult1\cf1\f0\fs32 A\cf0\f1\fs20\par
}
```
O Fortes imprime os nomes do stylesheet "Normal" e "heading 1" como texto, ao invés de apenas a letra "A".

**Comment by Nivaldo28** [comment]
Entendi e obrigado pelo retorno.

**Comment by SuporteSysrs01** [comment]
> Entendi e obrigado pelo retorno.

Comentei apenas mais um problema na impressão de Rich Text no Fortes e não uma solução. O problema ainda persiste.
