### ISSUE TITLE
Compilação 64bit Delphi 11

### ISSUE THREAD

**Issue by DenysPS** [fortesinformatica/fortesreport-ce#326]
Estou com um erro no evento  TRLPreviewForm.FormKeyDown da unit RLPReviewFomr.pas, quando compilado para 64bits:
<img width="487" alt="Captura de Tela 2023-03-05 às 14 18 09" src="https://user-images.githubusercontent.com/59372148/222975604-3f6e80ac-3803-45cd-82d1-45cc4d71b7dd.png">
Tenho também o Delphi Berlin instalado, ja corrigi a variável de ambiente.
Adicionando no uses System.UITypes e alterando de KEY_ESCAPE para vkEscape, por exemplo, passa a funcionar porém não sei se é o correto.

**Comment by juliomar** [comment]
não podemos deixar com system.uitypes pq é compatível com delphi 7 e lazarus.
mas se sentir a vontade. manda um pull request para avaliar

**Comment by DenysPS** [comment]
Minha dúvida é se deveria funcionar para 64bits por padrão, ou se é devido a ter 2 Delphi na mesma maquina?

**Comment by juliomar** [comment]
Sim tem que funciona.
pois a instalação é no win32. a IDE do delphi é Win32.
e no x64 é setado os paths e compilados.
lembrando que seu projeto tem que ter os scope unit names
