### ISSUE TITLE
Dependencia dos controles visuais win32

### ISSUE THREAD

**Issue by gladiston** [fortesinformatica/fortesreport-ce#328]
O fortes tem grande dependencia de units como:
  Interfaces,
  Messages,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
Para dar prepare nos relatórios e que tem grande dependencia da UI, mas pelo que vejo no seu codigo fontes isto acontece mais por causa de coisas como barras de progresso e preview, mas nem sempre precisamos de preview ou uma barra de progresso, se conseguir fazer com que o fortes não dependa da UI para dar "prepare" nos relatórios, poderemos usá-lo para criar relatorios  em APIs/REST ou cmd especialmente em Linux onde não há GUI.

**Comment by juliomar** [comment]
por favor fique a vontade para sugerir melhorias e enviar pull request.

**Comment by juliomar** [comment]
é só fazer um fork do projeto. alterar e mandar o pull request.

**Comment by reinaldoacdc** [comment]
Fiz algumas alterações e consegui gerar um ConsoApplication e fazer a chamada para exportação do relatório. 

Mas tenho uma dúvida: 
Sempre que chamo o RlReport.SaveToFile() ao abrir o arquivo dá o erro:  ` Erro Falha ao carregar documento PDF. ` 
Eu fiz os testes com o Demo/SemDados e tbm acontece a mesma situação. 

Precisa de alguma etapa a mais pra gerar só com o SaveToFile?

**Comment by juliomar** [comment]
mas como assim abrir ele não vai salvar?

**Comment by reinaldoacdc** [comment]
Ops, mybad. Eu não tinha percebido que tem ali um componente de PdfFilter, aí precisa usar ele né?!...
Pensei que filter fosse outra coisa.

**Comment by juliomar** [comment]
Isso mesmo.
