### ISSUE TITLE
Acentuação das palavras (texto e mensagens)

### ISSUE THREAD

**Issue by fabianocunha3a** [fortesinformatica/fortesreport-ce#329]
Boa noite, 
Após atualizar para a última versão do Fortes, as palavras que possuem acentuação, esta mostrando caracteres diferentes no lugar. 
Já baixei o repositório do GIT e do SVN e ambos esta com o mesmo problema. 

Olhando nos fontes, as mensagens e títulos estão com acentuação correta. 

![image](https://user-images.githubusercontent.com/69521316/225791385-6795803e-84a7-4ab5-acde-5e03919876c5.png)

**Comment by juliomar** [comment]
e estão.
a instalação se dá através do instalador.
fiz aqui teste e não tive problemas de acentuação.

**Comment by eduardoricheli** [comment]
Fabiano

Ainda não parei pra corrigir

**Comment by juliomar** [comment]
Jà está Ok. 
faz uns dias que subi a correção.

**Comment by fabianocunha3a** [comment]
> Jà está Ok. faz uns dias que subi a correção.

Muito obrigado Juliomar, por reportar. Fiz os testes e ficou correto a acentuação.
