### ISSUE TITLE
Não consigo mais salvar em PDF no FortesReport

### ISSUE THREAD

**Issue by jerrivaldo** [fortesinformatica/fortesreport-ce#330]
De 4 dias pra cá o FortesReport não salva mais em pdf. Erro:  "Range check error."

código:   
RLReport1.SaveToFile('C:\teste.pdf');

Também testei:
  RLPDFFilter1.FileName := 'h:\temp.pdf';
  RLReport1.Prepare;
  RLPDFFilter1.FilterPages(RLReport1.Pages);
  RLReport1.SaveToFile(RLPDFFilter1.FileName);

Sempre acontece o erro: "Range check error."

Estou usando o Delphi 10.3 mas já voltei para delphi 10.2 e continuou dando erro. voltei para delphi 10.2 e continuou o erro. Usei vários backups antigos do FortesReport, tentei com a versão nova, reinstalei o Windows e nada resolveu.

**Comment by juliomar** [comment]
Lembre-se parou seu executável?
ou atualizou o fortes report.
pois somente se mudou o código local senão não tem como ele parar sozinho

**Comment by jerrivaldo** [comment]
Muito obrigado pelo retorno, mas eu já consegui resolver. O problema todo é que o FortesReport ficou um tempão sem lançar versão nova então eu peguei uma versão muito antiga e fui adaptando ela para os delphi's novos mas chegou uma hora que bugou mas agora tem uma versão atualizada no github. Instalei aqui e funcionou bem.

**Comment by jerrivaldo** [comment]
O problema era que eu tinha a minha própria versao do FortesRepor há muitos anos venho modificando o FR para funcionar nas versões novas do Delphi. Então instalei a versão CE disponibilizada aqui no github e funcionou 100%.
