### ISSUE TITLE
Erro durante geração concomitante de relatórios (via requisições webservice e/ou multi-thread)

### ISSUE THREAD

**Issue by rodrigodiretriz** [fortesinformatica/fortesreport-ce#331]
**Erro durante geração concomitante de relatórios (via requisições webservice e/ou multi-thread)**

- Ambiente de desenvolvimento: Delphi 10.4, update 2 (Version 27.0.40680.4203) + Windows 10 Pro 22H2 (Compilação 19045.2965)
- Unit: trunk\Source\RLReport.pas
- Referência/Linha: function TRLCustomReport.Prepare, linha 13609 [raise Exception.Create(GetLocalizeStr(Name + ': ' + LocaleStrings.LS_PrepareErrorStr + sLineBreak + E.ClassName + '(' + E.Message + ')'));]
- Nota: a cópia de trabalho está atualizada (svn update) até a rev. 538 (https://github.com/fortesinformatica/fortesreport-ce/)

Excessão ocorre durante chamadas de relatórios concomitantes.
É possível reproduzir esse comportamento a partir do exemplo "trunk\Demos\Datasnap\Server" (simular com 3 requisições são sufientes para obter o erro).
Erro obtido: Project server_console.exe raised exception class Exception with message 'Relatorio: Erro durante a preparação do relatório EAccessViolation(Access violation at address 77C1F633 in module 'ntdll.dll'. Write of address 00000014)'.

![image](https://github.com/fortesinformatica/fortesreport-ce/assets/120504450/e4558c11-cfb2-4934-b93f-b70484057a0f)

A solução adotada para o caso foi modificar a "function NeedAuxBitmap: TBitmap" (unit RLUtils) para não mais retornar a variável auxiliar "AuxBitmap: TBitmap" (encapsulada na unit), além tratar a destruição do objeto retornado por ela no locais onde a função "NeedAuxBitmap" é utilizada.
O tratamento foi destruir a instância em cada local onde a mesma é utilizada, exceto aquele que usa o TBitmap do NeedAuxBitmap como Result (caso da  function HexToBitmap(), unit RLUtils).

Anexo estão as units corrigidas, para análise (aprovação e posterior commit no projeto FortesReport-CE).

[Source.zip](https://github.com/fortesinformatica/fortesreport-ce/files/11941806/Source.zip)

Após essas alterações foi possível atender até 40 requisições de geração simultânea de relatórios usando o FortesReport (nosso projeto é um webservice com mecanismo de servidor de relatórios encorporado).

Apesar da geração do relatório ter sido resolvida com as instruções anteriores, há ainda uma situação intermitente em que acima de 40 requisições (gerações simultâneas), após o relatório ser gerado, no final do processamento do método "TRLPDFFilter.FilterPages()" (usado para geração de pdf) obtem-se o erro:
- Project server_console.exe raised exception class Exception with message 'Invalid font for GetOutlineTextMetrics'.
- unit RLMetaVCL.pas
- procedure FontGetMetrics
- ora na linha 765 [raise Exception.Create('Invalid font for GetOutlineTextMetrics')], ora na linha 770 [raise Exception.Create('GetOutlineTextMetrics failed')], e ora funciona normal (intermitente).

![image](https://github.com/fortesinformatica/fortesreport-ce/assets/120504450/4e5273a5-1bd7-4da4-9b7d-f0ebcc8a3600)

**Obs1:** as ferramentas utilizadas para teste/simulação foram Postman (com duplicação de abas e breakpoint no projeto antes da geração ser iniciada) e Apache JMeter.

**Obs2:** o modelo de geração adotado no projeto é similar àquele do exemplo "trunk\Demos\Datasnap\Server", implementado na procedure TWebModule1.SendReport(Report:TRLReport; Response:TWebResponse).

[Source.zip](https://github.com/fortesinformatica/fortesreport-ce/files/11941806/Source.zip)

**Comment by dopidaniel** [comment]
Muito obrigado pela analise e contribuição.. já fiz o Merge nos fontes...

Apenas adicionei um bloco de try/finally e mudei a destruição do objeto para Bmp.Free

**Comment by Alt-C-Developer** [comment]
Eu também estava com problema na geração dos relatórios em paralelo em thread, e atualizei meus fontes e passou a funcionar perfeitamente agora, obrigado pela sua dedicação
