### ISSUE TITLE
opção de "install" não aparece

### ISSUE THREAD

**Issue by nilson-eficaz** [fortesinformatica/fortesreport-ce#332]
Estou tentando instalar o fortesCe no delphi 10.2.3 tokyo mas o botão de install não aparece, ele compila sem problema, pelo instalador dá erro de compilação. Alguém tem alguma sugestão de como resolver?
![image](https://github.com/fortesinformatica/fortesreport-ce/assets/53310689/a1b4bcd9-a9e6-46a7-8ba9-afad3bef418e)

**Comment by juliomar** [comment]
Use o instalador. ele foi feito para tu não sofrer.
o Fortes é composto de dois pacotes. um de compilação e outro de instalaçaõ. compila um , instala o outro.
mas volto a repetir use o instalador.

**Comment by nilson-eficaz** [comment]
> Use o instalador. ele foi feito para tu não sofrer. o Fortes é composto de dois pacotes. um de compilação e outro de instalaçaõ. compila um , instala o outro. mas volto a repetir use o instalador.

Obrigado Juliomar, deu certo, eu instalei no braço mesmo apesar de ter "corrigido" os errinhos.
