### ISSUE TITLE
SaveToStream como utilizar um filtro

### ISSUE THREAD

**Issue by AlexKid777** [fortesinformatica/fortesreport-ce#333]
Estou tentando utilizar o filtro PDF quando dou SaveToStream(IMemoria); Mas aparentemente o Fortes Report não utiliza, qual seria a forma correta de salvar o relatório no Stream utilizando o filtro de PDF ??

Obrigado.

**Comment by dopidaniel** [comment]
Experimente algo como:

      `        RLPDFFilter1.FilterPages(RLLayout.Pages, AStream)`
