### ISSUE TITLE
Alterar a extensão para a mesma do filtro ao Procurar e selecionar o arquivo.

### ISSUE THREAD

**Issue by Meioquilinho** [fortesinformatica/fortesreport-ce#335]
Olá @juliomar,

Não sei bem como fazer por aqui, mas aí vai uma tentantiva. Sou novo por aqui.

https://github.com/fortesinformatica/fortesreport-ce/blob/5d0b444f79e4825873d42d78c46f31dcae725f49/Source/RLSaveDialog.pas#L560

Ao salvar a pesquisa pelo arquivo que se deseja voltar não é alterada a extensão do arquivo para a mesma extensão do filtro selecionado. 

Mudança para alterar a extensão no edit para salvar:
    EditFileName.Text := **ApplyExt(**SaveDialog.FileName**)**;

A função de alteração da extensão já se encontra no projeto, foi criada mas nunca usada na unit.

**Comment by juliomar** [comment]
favor enviar pull request com as alterações
