### ISSUE TITLE
Converter a extensão do arquivo para a mesma do filtro ao salvar o arquivo.

### ISSUE THREAD

**Issue by Meioquilinho** [fortesinformatica/fortesreport-ce#336]
Olá @juliomar,

Não sei bem como fazer por aqui, mas aí vai uma tentantiva. Sou novo por aqui.
Conforme solicitado, segue abaixo mais um pedido de modificação:
 
https://github.com/fortesinformatica/fortesreport-ce/blob/5d0b444f79e4825873d42d78c46f31dcae725f49/Source/RLSaveDialog.pas#L503

Tem um erro ao salvar o arquivo se antes haver a mudança de filtro, esse erro ocorre porque não é alterada a extensão do arquivo e o mesmo abre como arquivo inválido.

A solução aqui percebida foi usar a mudança de extensão da variável FFileName antes de salvar o arquivo:

  if ComboBoxFilters.ItemIndex <> -1 then
    Begin
 L503     SelectedFilter := TRLCustomFilter(ComboBoxFilters.Items.Objects[ComboBoxFilters.ItemIndex]);
             ApplyExt(FFileName);
    End;

Outra percepção no mesmo arquivo é:  Ao salvar a pesquisa pelo arquivo que se deseja voltar não é alterada a extensão do arquivo para a mesma extensão do filtro selecionado. 

https://github.com/fortesinformatica/fortesreport-ce/blob/5d0b444f79e4825873d42d78c46f31dcae725f49/Source/RLSaveDialog.pas#L560

Mudança para alterar a extensão no edit para salvar:
    EditFileName.Text := **ApplyExt(**SaveDialog.FileName**)**;

A função de alteração da extensão já se encontra no projeto, foi criada mas nunca usada na unit.

**Comment by Meioquilinho** [comment]
Segue arquivo com as modificações com extensão txt
[RLSaveDialog.txt](https://github.com/fortesinformatica/fortesreport-ce/files/12562901/RLSaveDialog.txt)

**Comment by juliomar** [comment]
Favor enviar pull request com as alteraç~eos sugeridas
