### ISSUE TITLE
Salvar o arquivo de acordo com o filtro selecionado.

### ISSUE THREAD

**Issue by Meioquilinho** [fortesinformatica/fortesreport-ce#337]
Olá @juliomar 

Verificamos que ao salvar um relatório com outro filtro, o nome passado é sempre alterado para o título do relatório, e não o nome passado e pasta passado para o filtro. Sendo assim o relatório nunca e salvo com o nome e na pasta desejados. 

https://github.com/fortesinformatica/fortesreport-ce/blame/5d0b444f79e4825873d42d78c46f31dcae725f49/Source/RLPreviewForm.pas#L1502

Solução encontrada: 
inversão do primeiro teste if, caso tenha o FFileName que vem do filtro, salvar com o nome e pasta do Filtro que pode ser passado ao componente.

Código Alterado:

        **if (filt <> nil) then**
          **FileName := ApplyExt(filt.FileName)**
        else if Self.Preview.Pages.Title <> '' then
          {$IFDEF FPC}
           FileName := ExpandFileNameUTF8(FileNameFromText(Self.Preview.Pages.Title))
          {$ELSE}
           FileName := ExpandFileName(FileNameFromText(Self.Preview.Pages.Title))
          {$ENDIF}
        else
          FileName := '';

Código atual:

        if Self.Preview.Pages.Title <> '' then
          {$IFDEF FPC}
           FileName := ExpandFileNameUTF8(FileNameFromText(Self.Preview.Pages.Title))
          {$ELSE}
           FileName := ExpandFileName(FileNameFromText(Self.Preview.Pages.Title))
          {$ENDIF}
        else **if (filt <> nil) then**
          **FileName := filt.FileName**
        else
          FileName := '';

Arquivo com mudanças em anexo.
[RLPreviewForm.txt](https://github.com/fortesinformatica/fortesreport-ce/files/12562891/RLPreviewForm.txt)

**Comment by juliomar** [comment]
favor enviar pull request com a alteração sugerida
