### ISSUE TITLE
Memory Leak gerado!

### ISSUE THREAD

**Issue by hsoservicos** [fortesinformatica/fortesreport-ce#343]
Estou tendo um problema quanto ao uso do Fortes Report, está gerando Memory Leak na aplicação, mesmo utilizando o demo que acompanha do próprio componente, segue em anexo exemplo da codificação, arquivo compactado, estou utilizando um PC Intel, i3, 32Gb de Ram , Windows 10 Pro, Delphi 11, Mais testei no 10 também, o Componente do Fortes Report, foi totalmente removido e instalado novamente do zero, apresentando a mesma situação de Memory Leak!

--------------------------- Unexpected Memory Leak ---------------------------
An unexpected memory leak has occurred. The unexpected small block leaks are:
21 - 28 bytes: TBrush x 10
29 - 36 bytes: TPen x 10, Unknown x 2
37 - 44 bytes: TFont x 10
69 - 76 bytes: TRLBitmap x 10
101 - 108 bytes: TBitmapCanvas x 10
117 - 124 bytes: TBitmapImage x 10
157 - 172 bytes: Unknown x 1
---------------------------             OK         ---------------------------

Esse problema observei numa aplicação totalmente orientada a Interfaces e Objetos, quando passei para a parte dos relatórios que a mesma começou a apresentar Memory Leaks!
Então fui para os demos da Fortes e identifiquei que o componente estava apresentando essa situação!

Realizei várias tentativas com e sem imagens, até criei um formulário de relatório limpo, zerado e a mesma situação de Memory Leak!
Fiz o testes com o Demo: "\fortesreport-ce\Demos\Com Dados\FireDAC\ComDadosFireDAC.dproj"

Em anexo segue o projeto utilizado para testes:
[FireDAC.zip](https://github.com/fortesinformatica/fortesreport-ce/files/13507439/FireDAC.zip)

Desde já muitíssimo agradecido pela atenção e ajuda!
![memoryLeak](https://github.com/fortesinformatica/fortesreport-ce/assets/2547525/fd91632e-cd58-4f2b-8054-430531fc6582)

**Comment by juliomar** [comment]
peguei o projeto e removi toda a bagunça que tinha de free pra todo o lado e mandei rodar enão houve nenhum vazamento de memoria.
[FireDAC.zip](https://github.com/fortesinformatica/fortesreport-ce/files/13551273/FireDAC.zip)

**Comment by GuilhermeDischer** [comment]
@juliomar, eu também estou tendo este mesmo problema relacionado ao ML, depois de ter atualizado para a ultima versão.
Estou usando o Delphi 11 aqui em meus testes.

![image](https://github.com/fortesinformatica/fortesreport-ce/assets/73898413/71809b90-0170-4f2e-b8dc-653296c89db9)
Segue o print com as informações passadas pelo MadExcept

**Comment by hsoservicos** [comment]
Boa tarde a todos!

Montei um terminal novo, estou fazendo as devidas instalações para
verificar se acontecerá a mesma situação!

Anteriormente, atualizei o componente no Delphi 10.4 e 11, em ambos os
casos tive problemas de Memory Leak, por conta disso levantei a questão,
quanto ao código que enviei, testei de várias formas e em todos os caso
sempre gerando ML!

No caso, se o juliomar Marchetti, pudesse disponibilizar a versão que
utiliza ou alguma informação que possa ajudar, desde já fico muitíssimo
agradecido pela atenção e ajuda, por tudo!

Atenciosamente,


*Humberto Santos de Oliveira*
*Consultor de Soluções em TIC*
***@***.*** ***@***.***> *

*Mobile: (81) **98121.4008 - Vivo *


*Antes de imprimir, pense em sua responsabilidade com o MEIO AMBIENTE *Esta
mensagem, incluindo os seus anexos, contém informações confidenciais
destinadas a indivíduo e propósito específicos, sendo protegida por lei.
Caso você não seja a pessoa a quem foi dirigida a mensagem, deve apagá-la.
É terminantemente proibida a utilização, acesso, cópia ou divulgação não
autorizada das informações presentes nesta mensagem.


Em sex., 15 de dez. de 2023 às 14:58, Guilherme Discher <
***@***.***> escreveu:

**Comment by GuilhermeDischer** [comment]
@hsoservicos acabei que subir um PR que aparentemente corrige o ML: #345

**Comment by dopidaniel** [comment]
Humm.. pelo que analisei nos Fontes,  a função `HexToBitmap`, está retornando um Objeto TBitmap...
(Eu acho um crime, métodos retornarem objetos, pois fica confuso saber quando o objeto precisa ser destruido..)

O correto seria avaliar todas as ocorrências de chamada de `HexToBitmap` para inserir uma rotina de limpeza...

Vou analisar as mudanças

**Comment by dopidaniel** [comment]
Apliquei uma possível correção em
https://github.com/fortesinformatica/fortesreport-ce/commit/48f64a4fc5cf13699f9b4a5ed85a96d3e102bbe7

**Comment by hsoservicos** [comment]
Agradecido a todos pela ajuda e atenção!

Fiz a instalação da versão de capa do Fortes Report e acabe de testar na aplicação que estou desenvolvendo e tudo certo!
