### ISSUE TITLE
Erro Mudança Versão Delphi/Fortes Report

### ISSUE THREAD

**Issue by ESSanches02** [fortesinformatica/fortesreport-ce#348]
Boa tarde pessoal. Usei por muito tempo o Delphi XE com Fortes Report 3.71B. 

No final de 2023 resolvemos atualizar a versão do Delphi. Compramos a versão 12. Consegui instalar a versão 4.0.0.2 do FR (as versões com dclfrce.dpk não consegui instalar, mas isso é coisa para outro issue).

Feita a instalação, consegui compilar meu projeto de boas.

Começando a usar reparei que alguns forms de relatório o delphi simplesmente não abria (outros abrem problema algum) . Ele tentava abrir mas a ide fechava e não retornava nenhum erro.
Com o tempo, reparei que consigo abrir esses forms mas NÃO consigo coloca-los dentro de um projeto (xxx.dproj).

Entrei em contato com o suporte da Embarcadeiro e o que foi constatado é que estava gerando um erro relacionado ao uso de estilos. Porem o Fernando Rizzado (suporte Embarcadeiro) achou estranho esse tipo de erro pois, em teoria, reports não fazem uso de estilos.
O Fernando reparou tb que reports com uso de RLDetailGrid e com multiplos reports eram os que geravam o erro.
Por recomendação do Fernando, abri esse issue.

No arquivo anexado, o arquivo untContFci_RelPendencias é um exemplo que **não** funciona. Já o arquivo untDpRel_RelFun016 é um exemplo que funciona.

Para efeito de teste, basta abrir um projeto qualquer em delphi e tentar incluir esses arquivos no projeto criado.

A solução dada pelo Fernando é desabilitar o suporte a estilos em tempo de design nas opção.

Será que é possível alguma alteração no código pra corrigir esse problema?

Obrigado comunidade.

![image](https://github.com/fortesinformatica/fortesreport-ce/assets/158192359/202c39da-6ef4-426a-886f-c46ee1f289a9)

[Exemplos.zip](https://github.com/fortesinformatica/fortesreport-ce/files/14101456/Exemplos.zip)

**Comment by juliomar** [comment]
sempre existe. até temos todos dos fontes e caso queira nos ajudar como é um projeto aberto . pode tentar aplicar algo e submeter um pull request.

**Comment by ESSanches02** [comment]
Juliomar, infelizmente, não tenho competência pra mexer em um código fonte com esse complexidade técnica. Gostaria muito de ajudar, mas realmente não tenho essa competência.
