### ISSUE TITLE
Fortes RLReport + RLPDFFilter: constant "Range check error" in debug mode if Overflow checking and Range checking ON

### ISSUE THREAD

**Issue by EDW9700** [fortesinformatica/fortesreport-ce#350]
See https://www.projetoacbr.com.br/forum/topic/76429-fortes-rlreport-rlpdffilter-constant-range-check-error/

I use DELPHI 11.3 Community.
When I tried to save a RLReport as PDF using a RLPDFFilter, I always got a "Range Error Check" error and the writing of the PDF stopted after 163bytes (= after the first ">> endobj"). This happened always in DEBUG + RUNTIME mode, but not when double clicking in the IDE.

I did not have the problem when compiling and running the  "FILTROS"-demo that worked normally (I could save as PDF without problems).

The only difference between the demo and my app was the DPROJ-file: my project settings had Overflow checking and Range checking ON  (in debug mode).
After unchecking both settings I was able to save a PDF without errors.

So I added {$Q-} and {$R-} in the RLPDFFilter.pas. 

Not knowing if this is the right solution, I didn't open a pull request.

**Comment by juliomar** [comment]
please send the pull request

**Comment by juliomar** [comment]
in GIT
