### ISSUE TITLE
Fortes RLReport + RLPDFFilter: wrong EURO symbol when saving as PDF

### ISSUE THREAD

**Issue by EDW9700** [fortesinformatica/fortesreport-ce#351]
In Europe we use the Euro as currency: € = Alt 0128

In the IDE, in the preview of a report and when printing a report to 'Microsoft print to PDF', the euro symbol is perfect.

When a save the same report using the printdialog + Save As PDF, I get something strange instead of the euro symbol, something like 
54 with a comma under the number 5.
- Windows Print to PDF: €10.874,65
- RLPDFFilter Save as PDF: something like ‚5410.874,6 with the comma attached to the 5.

**Comment by EDW9700** [comment]
![EURO WindowsPrintToPDF vs RLPDFFilter](https://github.com/fortesinformatica/fortesreport-ce/assets/155301321/569ecff4-c20d-4817-994b-a3359eb9d4b6)

**Comment by EDW9700** [comment]
![EURO WindowsPrintToPDF vs RLPDFFilter](https://github.com/fortesinformatica/fortesreport-ce/assets/155301321/895ca993-3a7e-479f-b8ba-d7a79ac3bf6e)

**Comment by juliomar** [comment]
the font does not support the currency character type
try to modify it
