### ISSUE TITLE
Webpage www.fortesreport.com.br is down

### ISSUE THREAD

**Issue by PizzaProgram** [fortesinformatica/fortesreport-ce#353]
Hi,
 I'm looking for a better riport generator than FreeReport for Delphi7.
So I've found this site [here](https://github.com/Fr0sT-Brutal/awesome-pascal) , but there is very little info about it on this github page _(especially in english)_,
 and the link to the main page is dead.
Opened through archive.org, but do not find anything about it...
https://web.archive.org/web/20190201032120/https://www.fortestecnologia.com.br/

Any (English!) examples / screenshots / finished riports to view?

**Comment by juliomar** [comment]
No
but there are some examples in git
site no exist
