### ISSUE TITLE
Delphi 12.1 Compilando [dcc64 Fatal Error] 

### ISSUE THREAD

**Issue by carlospo** [fortesinformatica/fortesreport-ce#354]
Opa, vi em outros erros que isso ja ocorreu mas não consegui resolver com as soluções mostradas.
Erro:
ACBrBoletoFCFortesFr.pas(46): F2048 Bad unit format: 'C:\fortesreportD12\Binary\LibD29\RLReport.dcu' - Expected version: 36.0, Windows Unicode(x64) Found version: 36.0, Windows Unicode(x86),
*** atualizer a versão do para ultima.
*** instalação escolhi win32 
*** somente adicionei o path no win64.

**Comment by juliomar** [comment]
No caso tu não seta o path do compilando para usar m versão x64 e sim os paths
então tu roda o instalador, instala win32 pois a IDE é win32 e na library do x64 ele já coloca o path dos fontes para compilar quando compilar seu projeto em x64
