### ISSUE TITLE
Etiquetas cortando ao meio

### ISSUE THREAD

**Issue by rodrigo-ogioni** [fortesinformatica/fortesreport-ce#358]
Bom dia,
Depois da Ultima atualização, as etiquetas passaram a imprimir cortadas.

![image](https://github.com/fortesinformatica/fortesreport-ce/assets/64044584/2e7f489e-85ee-4c7b-9cc8-5dcfa7c1b56b)

o que pode estar acontecendo?

Grato

**Comment by juliomar** [comment]
configuração de margens?
mas para isso use lá componentes para isso ACBrETQ e sem sofrimento.

**Comment by rodrigo-ogioni** [comment]
nao consegui entender como funciona o acbretq

**Comment by juliomar** [comment]
Como assim?
tem o exemplo tem os manuais das programações de cada impressora de etiqueta 
e muito simples e muito mais facil que gerar uma imagem
