### ISSUE TITLE
Quebra de linha RLDBMemo

### ISSUE THREAD

**Issue by alexalvescrp** [fortesinformatica/fortesreport-ce#359]
Não esta ocorrendo quebra de linha
![Screenshot_7](https://github.com/fortesinformatica/fortesreport-ce/assets/149176678/219a6195-1fa0-49bc-a51e-5628a2db7162)
![Screenshot_6](https://github.com/fortesinformatica/fortesreport-ce/assets/149176678/332bd50f-fd30-44a9-aa50-fa3f898fb951)
![Screenshot_5](https://github.com/fortesinformatica/fortesreport-ce/assets/149176678/fb6b29be-d51d-45ff-ba78-87e1d3cfdfc4)

**Comment by juliomar** [comment]
Tem que existir espaços
crie um projeto demo com texto e anexe aqui para conseguir simular

**Comment by alexalvescrp** [comment]
Eu coloquei um RLMemo e atribui o valor do FDQuery antes do preview, ai deu certo, mas com o RLDBMemo não vai nem com os espaços.
