### ISSUE TITLE
Erro ao instalar delphi 2010

### ISSUE THREAD

**Issue by Tagales** [fortesinformatica/fortesreport-ce#38]
Ao tentar instalar no delphi 2010, esta dando erro:

[DCC Error] RLXLSXFileFormat.pas(339): E2003 Undeclared identifier: 'SplitString'

Alguém pode me ajudar?

**Comment by Tagales** [comment]
Verificando aqui na classe RLXLSFileFormat.pas
ele tem um if para quando for delphi 7(imagino eu) e esse método esta no meio.

{$ifdef DELPHI7}
type RawByteString = UTF8String;

var UTF8ToUnicodeString: function(const RawBytes: RawByteString): WideString = UTF8Decode;
  {$endif}
function SplitString(const S: string; Sep: Char): TStringDynArray;
var
  I, SepCount, SplitIndex, CopyStart: Integer;
begin
  if Length(S) = 0 then
  begin
    SetLength(Result, 0);
    Exit;
  end;
  SepCount := 0;
  for I := 1 to Length(S) do
    if S[I] = Sep then
      Inc(SepCount);
  SetLength(Result, SepCount + 1);
  CopyStart := 1;
  SplitIndex := 0;
  for I := 1 to Length(S) do
    if S[I] = Sep then
    begin
      Result[SplitIndex] := Copy(S, CopyStart, I - CopyStart);
      Inc(SplitIndex);
      CopyStart := I + 1;
    end;
  Result[SplitIndex] := Copy(S, CopyStart, MaxInt);
end;

**Comment by Tagales** [comment]
com as mudanças que teve na classe, aqui continua com erro. Estou usando o exe. 

Embarcadero Delphi for Win32 compiler version 21.0
Copyright (c) 1983,2009 Embarcadero Technologies, Inc.
C:\Program Files\Embarcadero\fortesreport-ce\trunk\Source\RLXLSXFileFormat.pas(350) Error: E2003 Undeclared identifier: 'SplitString'
C:\Program Files\Embarcadero\fortesreport-ce\trunk\Source\RLXLSXFilter.pas(72) Fatal: F2063 Could not compile used unit '..\Source\RLXLSXFileFormat.pas'
Compilation failure

**Comment by marciomartins** [comment]
Favor atualizar com a versão atual.
Preferencialmente usar o instalador.

**Comment by Tagales** [comment]
Continua com o mesmo erro, o que eu estou fazendo e abrir o RLXLSXFileFormat.pas e tiro o if do método, ai ele instala.

{$ifdef NO_SPLITSTRING}
function SplitString(const S: string; Sep: Char): TStringDynArray;
var
  I, SepCount, SplitIndex, CopyStart: Integer;
begin
  if Length(S) = 0 then
  begin
    SetLength(Result, 0);
    Exit;
  end;
  SepCount := 0;
  for I := 1 to Length(S) do
    if S[I] = Sep then
      Inc(SepCount);
  SetLength(Result, SepCount + 1);
  CopyStart := 1;
  SplitIndex := 0;
  for I := 1 to Length(S) do
    if S[I] = Sep then
    begin
      Result[SplitIndex] := Copy(S, CopyStart, I - CopyStart);
      Inc(SplitIndex);
      CopyStart := I + 1;
    end;
  Result[SplitIndex] := Copy(S, CopyStart, MaxInt);
end;
{$endif}

![fortes_erro](https://cloud.githubusercontent.com/assets/14877986/10194366/a5ca9110-675e-11e5-8100-aea94ab4c6c3.png)

**Comment by cezarlopes** [comment]
Estou com o mesmo problema. Acabo de baixar os fontes mais recentes, mas só consigo instalar quando comento as diretivas abaixo. Comentei e compilei. Funcionou. Mas, será que não vai dar problemas mais adiante?
![fortes bug](https://cloud.githubusercontent.com/assets/15030445/10363458/0726e1c0-6d8b-11e5-9d77-93130f7c44ed.png)

**Comment by luisarruda** [comment]
@cezarlopes Qual o seu ambiente? E versão?

**Comment by cezarlopes** [comment]
Bom dia Luis Arruda. Estou compilando em delphi 2010 SO win7.

**Comment by luisarruda** [comment]
@cezarlopes O que você fez não vai gerar problemas não, ou você pode alterar somente o {$IfNDef DELPHI8_UP} para {$IfNDef DELPHIXE_UP} que ele vai compilar normalmente, já fiz um pull request para essa correção para a master, estou aguardando a aprovação.

Isso acontece porque as versões mais novas do Delphi já tem essa função por padrão na StrUtils, enquanto o nosso 2010 não tem.

**Comment by Tagales** [comment]
eu já estava achando que problema era comigo, no meu eu tirava, mas vou fazer isso que luisarruada falou então :D

**Comment by cezarlopes** [comment]
Ok @luisarruda obrigado pelo retorno. Valeu!
