### ISSUE TITLE
Qtd de Paginas no Preview do Fortes Report.

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#39]
Bom dia a todos,

Com o fortes report na versao 3.23, no componente ACBRDanfeNfe, alterando a propriedade NUMCOPIAS para 3 por exemplo, se a opção mostrar preview estiver como true, ao mostrar o preview do relatorio, ao clicar em imprimir aparecia qtd de copias como 3 paginas, obedecendo o valor do componente. Com a versão FortesreportsCE, não funciona dessa maneira. Não sei se foi alterado de proposito, mas se não quiserem alterar no componente, por favor, me expliquem onde eu posso fazer essa alteração no componenente, para mim continuar usando como era anteriormente.
Grato
Rodrigo

**Comment by marciomartins** [comment]
Estamos providenciando o ajuste.
Esta semana ainda liberaremos no branch master.

**Comment by marciomartins** [comment]
Favor atualizar com a versão mais recente e usar o instalador.

**Comment by dominioararangua** [comment]
Bom dia,
Fiz a atualização do componente e continua a mesma situação.
Grato
Rodrigo

**Comment by dopidaniel** [comment]
Certeza que o problema ainda persiste ? Talvez o comportamento esteja diferente da versão anterior... mas o número de cópias é respeitado...

- No Preview será exibida apenas uma Cópia do relatório (DANFE), o que faz sentido, pois economiza recursos...
- Quando você clicar em "Imprimir"  (na opção janela do Preview)... observe que o Número de Cópias pré-definido, irá aparecer no Diálogo de Impressão... bastando confirmar... OK
