### ISSUE TITLE
Problems installing FortesReport Lazarus Linux

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#4]
Hello Guys,

I am trying to install FortesReportCE on Lazarus 1.4 RC1 Linux Fedora 21 x 64.
Features the errors below:

Compiling package FortesReportCE_Lazarus 0.0: Exit code 256, Errors: 1
RLTypes.pas(7,3) Fatal: Cannot find unit Windows used by RLTypes of package FortesReportCE_Lazarus.

**Comment by marciomartins** [comment]
Sorry version for Lazarus is maintained by another user and has not yet been fully integrated into this. We are working to be a single version.
Thank compeensão.
