### ISSUE TITLE
Erro ao instalar com o fortes

### ISSUE THREAD

**Issue by Tagales** [fortesinformatica/fortesreport-ce#42]
Estou usando executável para instalar o Fortes. e deu esse erro, alguém poderia me ajudar?

![fortesreport](https://cloud.githubusercontent.com/assets/14877986/10177184/215e2a20-66cf-11e5-9441-40b31e6af72d.png)

**Comment by juliomar** [comment]
Se observar ele instalou igualmente!
pode abrir seu delphi que está lá!

estou tentando entender o problema e logo subimos uma correção!

**Comment by juliomar** [comment]
Já subi a correção agora é só aguardar integrar o pull request que fiz
