### ISSUE TITLE
Erro no Delphi2007 usando o instalador frceInstall.exe e instalando direito o pacote frce.dpk

### ISSUE THREAD

**Issue by olavojr** [fortesinformatica/fortesreport-ce#44]
Instalando com o frceInstall, gerou o Log de erro no final da mensagem (removi abaixo o parametro -U que é muito grande para facilitar o entendimento):

O problema é na Unit RLUtils, vi que logo no inicio do código foi colocado condicionais, para criação da diretiva: NO_CHARINSET que cria a função CharInSet, confome codigo abaixo, mais aparentemente o compilador do DELPHI2007 não esta entendendo e não declara o que gera o erro do LOG.

{$IfNDef DELPHI2007_UP}
 {$Define NO_CHARINSET}
{$EndIf}
{$IfDef FPC}
 {$Define NO_CHARINSET}
{$EndIf}

Outro problema "semelhante" esta na Unit RLXLSXFileFormat, que tem o codigo abaixo e no compilador do DELPHI2007 não declara o NO_SPLITSTRING que cria função SplitString, tambem gerando erro, para conseguir instalar tive de colocar na diretiva do projeto frce.dpk o seguinte: RELEASE;DELPHI;VCL;NO_CHARINSET;NO_SPLITSTRING;DELPHI7_DOWN:

{$IfDef DELPHI7_DOWN}
 {$Define NO_SPLITSTRING}
{$EndIf}
{$IfDef FPC}
 {$Define NO_SPLITSTRING}
{$EndIf}

LOG de erro do instalador:

Caminho: C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\
Versão do delphi: Delphi 2007 (0)
Plataforma: Win32(0)
================================================================================
Setando parâmetros de plataforma...
Criando diretórios de bibliotecas...
Adicionando library paths...

Compiling package C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Packages\frce.dpk
"C:\Program Files\CodeGear\RAD Studio\5.0\bin\dcc32.exe" "C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Packages\frce.dpk" --no-config -B -$O- -$W+ -$Y- -M -Q -H- -W- -DRELEASE -U"C:\Program Files\CodeGear\RAD Studio\5.0\lib" -U"REMOVIPARAMELHORVISUALIZACAO" -N0"C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Binary\LibD11" -LE"C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Binary\LibD11" -LN"C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Binary\LibD11"
CodeGear Delphi for Win32 compiler version 18.5
Copyright (c) 1983,2007 CodeGear
C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Source\RLUtils.pas(989) Error: E2003 Undeclared identifier: 'CharInSet'
C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Source\RLUtils.pas(989) Error: E2015 Operator not applicable to this operand type
C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Source\RLUtils.pas(994) Error: E2015 Operator not applicable to this operand type
C:\Program Files\CodeGear\RAD Studio\5.0\fortesreport-ce\trunk\Source\RLMetaFile.pas(66) Fatal: F2063 Could not compile used unit '..\Source\RLUtils.pas'
Compilation failure

**Comment by marciomartins** [comment]
O Juliomar do ACBr está adicionando o jedi.inc que provavelmente irá resolver este problema.

**Comment by juliomar** [comment]
Favor atualizar e testar a recompilação

**Comment by olavojr** [comment]
Eu atualizei e da erro o mesmo erro acima, se tentar usar o frceInstall.exe, então testei instalar o frce.dpk (que o frceInstall faz a chamada de compilação) e tambem apresenta o mesmo erro.

Observei que o frce.dpk, insere ($I) o RLReport.inc e RLReport_jedi.inc (que é praticamente as mesmas diretivas do ACBr_jedi.inc do Juliomar), só que em ambos (no caso do DELPHI2007) o que volta definido é DELPHI2007_UP (e varias outras) e no codigo RLUtils.pas o NO_CHARINSET só é definido se atender a condição: {$IfNDef DELPHI2007_UP} , ou seja, vai dar o erro no meu caso para funcionar tiver trocar a condição: {$IfNDef DELPHI2007_UP} por {$IfDef DELPHI2007_UP} para ser declarado o NO_CHARINSET

Já na unit RLXLSXFileFormat.pas levando em contas os arquivos .inc citados, o NO_SPLITSTRING só é atribuido na condição: {$IfDef DELPHI7_DOWN} que no caso do DELPHI2007 não atende, então tive de adicionar o trecho abaixo:

{$IfDef DELPHI2007_UP}
 {$Define NO_SPLITSTRING}
{$EndIf}

E ainda na mesma unit, foi necessário duplicar o codigo abaixo tambem por que somente era criado na condição: {$IfDef DELPHI7_DOWN}

{$IfDef DELPHI2007_UP}
type RawByteString = UTF8String;

var UTF8ToUnicodeString: function(const RawBytes: RawByteString): WideString = UTF8Decode;
{$EndIf}

Resumindo, no caso do DELPHI2007, na RLUtils.pas precisa entrar na declaração do NO_CHARINSET e no RLXLSXFileFormat.pas precisa criar o NO_SPLITSTRING, criado o tipo  RawByteString e UTF8ToUnicodeString.

**Comment by juliomar** [comment]
se perceber o daniel fez um pull request corrigindo isso!
mas ainda não foi integrado ao master do fortesreport

**Comment by juliomar** [comment]
Pronto o pull request está integrado

**Comment by marciomartins** [comment]
Olavo, verifica pra gente se corrigiu.
Obrigado.
