### ISSUE TITLE
Erro ao abrir o delphi

### ISSUE THREAD

**Issue by Tagales** [fortesinformatica/fortesreport-ce#45]
Fiz update da pasta do fortes, fiz instalação pelo executável e instalou sem erro, mas ao abrir o delphi, esta dando esse erro, podem me ajudar?

![fortes_erro_02](https://cloud.githubusercontent.com/assets/14877986/10195481/379fe748-6764-11e5-9a30-e5acee2385d6.png)

**Comment by juliomar** [comment]
Sim 
tu não tem mais esse !
olhou para os fontes após atualizar?
percebeu que foram aplicados diversas mudanças e uma delas é o nome do pacote que passou a ser único
a segunda é que tem o instalador agora pra usar!
e está compatível o mesmo código para delphi e lazarus 
com correções de bugs então 
remova de seu micro essa versão, faça um pull feche o delphi e use o instalador não tem erro e nem problema

**Comment by Tagales** [comment]
Beleza, erro meu, como tinha instalado o acbr tb em cima do fortes antigo, foi só fazer denovo instalacao do acbr e deu certo, mal :D
