### ISSUE TITLE
Não instalou no Lazarus 3.1.1

### ISSUE THREAD

**Issue by OsvaldoTCF** [fortesinformatica/fortesreport-ce#46]
Ambiente:
Ubuntu 15.04
Lazarus 1.5
FPC 3.1.1

Ao compilar o pacote considera usar a CLX e apresenta vários erros. 
O pacote pode ser instalado no ambiente descrito acima?

**Comment by franciscoluiz** [comment]
Apenas para constar, aqui instalou perfeitamente. 
Lazarus 1.4.0 com FPC 2.6.4 (ambos 32 bits)
Windows 7 32 bits

**Comment by OsvaldoTCF** [comment]
Como informado meu ambiente é outro!

2015-09-30 14:35 GMT-03:00 Francisco <notifications@github.com>:

> Apenas para constar, aqui instalou perfeitamente.
> Lazarus 1.4.0 com FPC 2.6.4 (ambos 32 bits)
> Windows 7 32 bits
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fortesinformatica/fortesreport-ce/issues/46#issuecomment-144485293>
> .
>



-- 
                    - Osvaldo T Crispim Filho -

"Conhecer não é demonstrar nem explicar, é aceder à razão."
*(Antoine de Saint Exupery)*

**Comment by rftd** [comment]
@OsvaldoTCF vai em RLReport.inc e altere a linha

{$IFDEF LINUX} {$DEFINE KYLIX} {$ENDIF}

para

{$IFNDEF FPC}{$IFDEF LINUX} {$DEFINE KYLIX} {$ENDIF}{$ENDIF}

isto deve corrigir seu problema.

**Comment by juliomar** [comment]
Para corrigir isso iremos adicionar o jedi.inc que possuem diversas configurações e uma delas contempla!

**Comment by dopidaniel** [comment]
Até onde sei, o Jedi.inc já está inserido nos fontes do Fortes...

O problema já foi resolvido ? o caso pode ser fechado ?

**Comment by marciomartins** [comment]
Como não houve retorno, vou dar o caso como encerrado.
Se persistir o problema, favor avisar que reabriremos.
