### ISSUE TITLE
Qtd de Paginas no Preview do Fortes Report. #39

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#47]
Bom dia,

Atualizei os componentes, mas continua com o mesmo problema.

Grato
Rodrigo

**Comment by juliomar** [comment]
Viu já foi visto!
mas o marcara que tu diz é quando clicar pra imprimir já trazer a quantidade de copias no campo?
ou está falando em ficar criando diversas páginas no preview iguais?

**Comment by dominioararangua** [comment]
Bom dia,
Quando eu configuro o componente ACBRDanfeNFe para QtdPaginas para 3 por exemplo, não esta aparecendo o preview do fortes, quando clico em imprimir no campo Qtd Paginas. Fica aparecendo 1 quando no compoonente foi configurado para 3.

Grato

**Comment by dominioararangua** [comment]
a

**Comment by marciomartins** [comment]
O Daniel do ACBr, corrigiu, favor atualizar.

**Comment by dominioararangua** [comment]
Boa noite! 

Atualizei o componente, mas ainda não esta passando o parametro.

Grato,
Rodrigo
