### ISSUE TITLE
Compilar no Delphi XE2 Update 4 HotFix 1

### ISSUE THREAD

**Issue by abraao895** [fortesinformatica/fortesreport-ce#49]
Boa tarde pessoal, 
       Quando fui utilizar o instalador e compilar a nova versão do Fortes Report com a última versão da ACBr do trunk2, obtive o seguinte erro:

C:\Aplicativo\LibraryXE2\fortes-report\Source\RLDraftFilter.pas(609) Error: E2033 Types of actual and formal var parameters must be identical
frce.dpk(61) Fatal: F2063 Could not compile used unit 'RLDraftFilter.pas'

Eu tive que efetuar a seguinte alteração na unit 'RLDraftFilter.pas' na linha 597:

{$IfDef DELPHIXE3_UP}

Para:

{$IfDef DELPHIXE2_UP}

       Acredito que a linha acima possa ser atualizada no source principal do fortes report, mas deixo a critério de vocês, se essa alteração será possível. Desde já parabenizo vocês por este trabalho.

**Comment by marciomartins** [comment]
Foi corrigido com o commit 9e21650
