### ISSUE TITLE
Imprimir XPS

### ISSUE THREAD

**Issue by rodrigopandini** [fortesinformatica/fortesreport-ce#5]
(Windows 7 - 32bits)

Olá,
Quando tento imprimir em XPS o programa trava e não gera o arquivo neste formato.
Outros programas conseguem gerar o arquivo xps normalmente. Então por isso acredito que o Fortes está com problemas ao tentar imprimir em xps.
Alguém mais já passou por isso e sabe como resolver?
É bug do Fortes mesmo?
Grato.

**Comment by marciomartins** [comment]
Desculpe a demora, se o problema persistir na versão atual, favor reabrir o chamado ou me contactar por e-mail.
