### ISSUE TITLE
Qtd de Paginas no Preview do Fortes Report. #39 #47

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#52]
KKK Acho que fecharam sem resolver.

**Comment by juliomar** [comment]
Acho que tu não conseguiu atualizar e não recompilou pois os códigos estão funcionando certinho

**Comment by dominioararangua** [comment]
Bom dia Juliomar,
Ontem atualizei pelo tortoise, recompilei o fortes e fiz o teste. Não deu certo.
O que mais precisa ser feito?
Grato

**Comment by dominioararangua** [comment]
Boa tarde, Fiz a atualização do fortes hoje, mas ainda continua o problema. Neste caso é um ajuste no fortes ou no acbr?
Estou atualizando apenas o fortes
Grato
Rodrigo

**Comment by dopidaniel** [comment]
Certeza que você está baixando da URL correta ?

Isso já foi corrigido e testado por vários usuários...

**Comment by dominioararangua** [comment]
Boa tarde, baixei o componente do zero agora, instalei pelo frceinstall.exe, e instalou normalmente sem erros. Mas o problema continua.
Grato

**Comment by dopidaniel** [comment]
Não conseguimos reproduzir o problema... sugiro você criar um mini projeto, que demonstre o problema

**Comment by marciomartins** [comment]
@dominioararangua o problema continua? Se sim, favor no enviar um exemplo, pois como o Daniel falou não foi possível reproduzir. Vou dar como concluído, qualquer coisa avisa que reabrimos.
