### ISSUE TITLE
Erro ao compilar fortes

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#55]
Boa tarde a todos,
Baixei novamente o fortes para ver se resolvia o problema que esta acorrendo no post anterior, agora quando vou compilar da os seguintes erros:

[Error] RLXLSXFileFormat.pas(348): Undeclared identifier: 'SplitString'
[Error] RLXLSXFileFormat.pas(763): Undeclared identifier: 'RawByteString'
[Error] RLXLSXFileFormat.pas(766): Incompatible types
[Error] RLXLSXFileFormat.pas(1381): Undeclared identifier: 'RawByteString'
[Error] RLXLSXFileFormat.pas(1385): Incompatible types
[Error] RLXLSXFileFormat.pas(1407): Incompatible types
[Error] RLXLSXFileFormat.pas(1408): Incompatible types
[Error] RLXLSXFileFormat.pas(1415): Undeclared identifier: 'RawByteString'
[Error] RLXLSXFileFormat.pas(1422): Incompatible types
[Error] RLXLSXFileFormat.pas(1425): Undeclared identifier: 'UTF8ToUnicodeString'
[Fatal Error] RLXLSXFilter.pas(72): Could not compile used unit '..\Source\RLXLSXFileFormat.pas'
[Fatal Error] Required package 'vclimg' not found
[Fatal Error] Required package 'vclimg' not found

Uso delphi 7.
Grato

**Comment by carlosmarian** [comment]
Tbm estou com este erro, nem o instalador(exe) nem compilando pela IDE.
Revisão 252

**Comment by carlosmarian** [comment]
Para contornar eu removi a tag de compilação do método SplitString.
Ai consegui compilar e instalar..
Estou usando Delphi 2009

**Comment by juliomar** [comment]
é algo no .inc que foi modificado por mim !
acredito que quando chegar em casa a noite possa testar no delphi7 e informar e rsolver o problema

**Comment by carlosmarian** [comment]
Olá.
  Será que eu preciso criar alguma tag específica no INI?

**Comment by luisarruda** [comment]
Ainda não alterei de forma correta para abrir um pull request, mas faça o seguinte :
No arquivoRLXLSXFileFormat.pas remova o ifndef do início que valida delphi_UP8 deixando somente o define nosplitstring até o delphi 2010 deve funcionar (testei no 2010).

**Comment by alewerner** [comment]
Também tive o mesmo problema no delphi 2010, no arquivo RLXLSFileFormat.pas.
Tive que remover código das linhas 49 a 54 
{$IfNDef DELPHI8_UP}
 {$Define NO_SPLITSTRING}
{$EndIf}
{$IfDef FPC}
 {$Define NO_SPLITSTRING}
{$EndIf}

E também das linhas 312 a 320 
{$IfNDef FPC}
{$IfNDef DELPHI8_UP}
type RawByteString = UTF8String;

var UTF8ToUnicodeString: function(const RawBytes: RawByteString): WideString = UTF8Decode;
{$EndIf}
{$EndIf}

{$ifdef NO_SPLITSTRING}

**Comment by dominioararangua** [comment]
fiz o download hoje e esse problema foi resolvido.

Obrigado a todos
