### ISSUE TITLE
Filtro XLSX

### ISSUE THREAD

**Issue by miaritecnologia** [fortesinformatica/fortesreport-ce#57]
boa dia, apos atualizar para nova versão do fortes, nos relatórios estou usando RLXLSFilter só que os aquivos ficam totalmente desconfigurado com caracteres ASCII, troquei para RLXLSXFilter os arquivos ficam com as colunas com o tamanho de 255, já olhei nas propriedade não encontrei nada  que possa resolver, tentei  anexar um arquivo mas não consegui. Estou usando o delphi 7 e XE7 ambos com este problema

**Comment by marciomartins** [comment]
Boa tarde, você teria como enviar um app de exemplo?

**Comment by miaritecnologia** [comment]
Boa tarde 
Marcio como eu posso te enviar o exemplo.

**Comment by miaritecnologia** [comment]
Marcio, ainda o novo filtro para excel  não salva corretamento, as colunas estão muito
grande e o tamanho da pagina esta desconfigurado, também estou enviando um e-mail
pra você com um exemplo em anexo.

**Comment by marciomartins** [comment]
@miaritecnologia Desculpe a demora, você pode me dizer se o problema foi resolvido?
Qualquer dúvida, favor entrar em conato.

**Comment by marciomartins** [comment]
@miaritecnologia Estou tentando localizar seu e-mail, mas não tenho tido sucesso.
Você poderia enviar novamente?

**Comment by elidorio** [comment]
clique na foto do Márcio que vc verá o e-mail dele.

**Comment by miaritecnologia** [comment]
Boa tarde 
Marcio hoje atualizei o fortes, que piorou a situação, agora ele salva tudo desconfigurado. Antes as colunas fica com tamanho de 255, então selecionava toda planilha e definia a coluna com o tamanho igual a 8. Também não consigo anexar arquivo junto com a mensagem.

Ornei

**Comment by miaritecnologia** [comment]
Bom dia,

Marcio, me desculpa, passei batido, e que uso o TRLPreview com o TSaveDialog na propriedade Filter tinha colocado *.PDF e *.XLS, mesmo com o RLXLSXFilter era salvo no formato anterior, por isto o arquivo ficava desconfigurado, a principio esta tudo certo agora . Obrigado

**Comment by juliomar** [comment]
Como foi resolvido estou fechando.
