### ISSUE TITLE
Problemas ao instalar no XE8

### ISSUE THREAD

**Issue by conectvideo** [fortesinformatica/fortesreport-ce#6]
O erro também ocorre no Xe7.

[dcc32 Fatal Error] RLReport.pas(27): F2613 Unit 'Qt' not found.

e para nessa parte do codigo RLReport.pas:

{$else}
  Qt, QTypes, QExtCtrls, QDBCtrls, QControls, QForms, QDialogs,
  QStdCtrls, QButtons, QGraphics, MaskUtils,

Tens como dizer como retirar para que compile? Pois só deixando o MaskUtils dá mais erros a frente.

obg.

**Comment by renatopandolfo** [comment]
Estou com o mesmo problema no XE8.

Obrigado

**Comment by marciomartins** [comment]
Caros, se o problema persistir na versão atual favor reabrir o chamado ou me contactar por e-mail para que eu possa providenciar o ajuste o mais rápido possível.
