### ISSUE TITLE
Imprimindo como cupom na impressora HP

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#62]
Bom dia,

Tenho um cliente que tem uma impressora HP Deskjet e uma impressora de cupom não fiscal ao qual está como padrao. Quando gero o relatorio, aparece na listagem de impressoras, a Elgin I9. Então o Cliente altera para HP Deskjet e manda imprimir. Na tela, o preview gera corretamente, mas na impressão, ele imprime somente uma faixa que é o tamanho do cupom e o restante fica em branco.

Testei em uma epson e problema não ocorreu. Parece ser um problema com HP. 

Usando a versão 3.23 do fortes esse problema não acontece.

Grato

**Comment by marciomartins** [comment]
@dominioararangua, boa tarde.
É bem estranho este seu caso, pois o FortesReport utiliza a o SO para fazer a impressão.
Você teria um protótipo para nos enviar, assim facilitaria a simulação.
Se possível enviar o modelo exato da impressora.
No aguardo.

**Comment by juliomar** [comment]
Veja que a sua versão é antiga do Fortes !
atualize e teste novamente caso continue a ocorrer abra novo issue e anexe um projeto com o erro ocorrendo de exemplo
