### ISSUE TITLE
TRLDBResult não soma mais

### ISSUE THREAD

**Issue by bnobre** [fortesinformatica/fortesreport-ce#66]
Olá,

Efetuei a atualização do Fortes tem umas 2 semanas, mais ou menos, a versão que eu tinha antes era a 4, mas não tinha nem o instalador na época que instalei no meu Delphi 7.

Após tal atualização, nos meus relatórios que usam o TRLDBResult com a info "riSum" aparecem apenas 0, não estão mais fazendo o somatório. Tentei atualizar o componente agora, mas continua o mesmo problema.

Desde já agradeço a atenção

**Comment by faustoalves1968** [comment]
Você codificou o evento OnCompute do TRLDBResult?
A construção do evento é assim:
RLDBResult3Compute(Sender: TObject;  var Value: Variant; var Text: string; var ComputeIt: Boolean);
então eu codifico da seguinte forma:
RLDBResult3Compute(Sender: TObject;  var Value: Variant; var Text: string; var ComputeIt: Boolean);
begin
   Value := NomedoCampo.AsCurrency;
end;

**Comment by bnobre** [comment]
Olá... Não fiz isso antes, pois nunca precisei.

O meu RLDBResult está dando um SUM no campo total. Pelo que entendi da sua explicação tentei o seguinte no evento Compute:

Value := z_read_agendamentostotal.AsCurrency;

Mas só aparece um valor estranho "1,2E2". Esse campo total é do tipo Inteiro, aparece no Object Inspector como TLargeintField.

**Comment by faustoalves1968** [comment]
Eu utilizei..
AsCurrency, apenas como exemplo.. tente AsInteger, ou então  SeuCampo.Value


Em 11 de novembro de 2015 00:58, bnobre <notifications@github.com> escreveu:

**Comment by bnobre** [comment]
Olá,

Então... testei com todas essas opções e sempre recebo o valor "1,2E2", onde o correto era pra ser 122. Um detalhe, ao tentar .Value, nesse caso e somente nesse caso recebo o valor 0.

**Comment by jrstefani** [comment]
Olá!

Conforme o amigo bnobre citou, também encontro dificuldade com esse componente. Fiz alguns testes conforme o faustoalves1986 comentou, no entanto não tive sucesso.

Estou analisando o fonte para tentar entender o que pode estar errado e aplicar uma correção.

**Comment by marciomartins** [comment]
Pessoal, desculpem a ausência.
Você teriam um protótipo para eu analisar?

**Comment by bnobre** [comment]
Olá amigos... Desculpem a ausência. 

Nesse problema que postei, uso o Zeos + Mysql para conexão ao banco. Os fields que não somavam estavam sendo atribuídos pelo componente como TLargeintField...

Dei um CAST no campo em questão e o mesmo passou a ser atribuído como TFloatField. Com isso passou a funcionar o SUM normalmente. 

Exemplo do CAST que usei: CAST(COUNT(V8.id_vendas) AS DECIMAL(10,2)

**Comment by leferrazsilva** [comment]
Eu estou com esse problema

**Comment by juliomar** [comment]
chegou a fazer o sugerido pelo colega?

**Comment by delphigov** [comment]
SOLUÇÃO:
1 - coloca ele na banda 
2 - liga no datasource
3 - liga no datafield
4 - Evento: Compute coloca o seguinte: Value := RLDBResult.Field.AsFloat;
5 - DisplayMask: ###,###,0.00 
6 - Seja feliz!

**Comment by admin-hans** [comment]
Hi,

 

Need urgent a pointer to folgem problem:Must in a report a calculated insert Field.

 

My accumulation field is available and ought to e.g. with 14 multiplies are, the outcome should in another array of data appear.

 

 

Vieleicht can me here somebody help.

 

 

A lot of thank you very much in front of.

 

 

 

Regards

 

 

John Ettl

 

 

Mit freundlichen Grüssen

 

----------------------------------------------------------------------------------
Mail: ***@***.***

 

Von: [ DELPHI GOV ] ***@***.***> 
Gesendet: Mittwoch, 28. August 2024 01:19
An: fortesinformatica/fortesreport-ce ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [fortesinformatica/fortesreport-ce] TRLDBResult não soma mais (#66)

 

SOLUÇÃO:
1 - coloca ele na banda
2 - liga no datasource
3 - liga no datafield
4 - Evento: Compute coloca o seguinte: Value := RLDBResult.Field.AsFloat;
5 - DisplayMask: ###,###,0.00
6 - Seja feliz!
