### ISSUE TITLE
Na visualização, aparece, mas na impressão perde parte da impressão

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#67]
Bom dia a todos,

Varios Clientes tem reclamado que na hora da impressão, perde caracteres. Por exemplo, no boleto bancario, o codigo de barras, não imprime o ultimo numero, sendo que na visualização aparece normalmente. A qtd de paginas não se atualiza. Tem um cliente que tem duas impressoras, como padrão fica uma de cupom, e como segundaria uma laser HP. Quando vai visualizar, perfeito, na hora de imprimir imprime pela metade, exatamente o espaço de um cupom. 

Pelo jeito, o pessoal que ficou responsavel pelo fortes ce esta meio sem tempo de olhar esses problemas. Tentei fazer algumas alterações, mas me faltou conhecimento tecnico para faze-lo.

 Por hora vou ter que voltar para a versão 3.23 do fortes, mesmo contra a minha vontade, pois gostaria muito de continuar usando a CE, mas esta com muitos bugs.

Grato

**Comment by marciomartins** [comment]
Bom dia.
Tive um problema com meu notebook (quebrou a tela em uma acidente) onde está todo o ambiente para desenvolvimento e estou há mais de duas semanas sem poder utilizar.
Gostaria que ser possível passar um protótipo, além de fotos do impresso e print screen, para que agilize a nossa análise.

**Comment by dominioararangua** [comment]
Bom dia Marcio,
Obrigado pela preocupação e sinto muito pelo seu aparelho.
Vou providenciar e posto aqui. Talvez demore um pouco porque vou ter que me deslocar até os clientes que estão tendo esses problemas.
Grato

Rodrigo

**Comment by marciomartins** [comment]
Obrigado, ontem a nova tela chegou e já estou colando os trabalhos em dia.

**Comment by dominioararangua** [comment]
Boa tarde Marcio, acho que não vai adiantar fazer um demo, porque ja voltei para a versão antiga do Fortes. Mas mesmo assim vou enviar o arquivo contendo o problema no meu cliente.
Grato
![impressao forte c](https://cloud.githubusercontent.com/assets/14807893/10853169/ed191e54-7f1b-11e5-8988-6adcc4b96456.jpeg)

**Comment by dominioararangua** [comment]
Em outro cliente o boleto bancario perdeu a ultima linha que contem o ultimo numero do codigo de barras. Será que pode ser incompatibilidade com os modelos diferentes de impressora?
Grato

**Comment by dangrasoftware** [comment]
Pessoal, eu também estou com esse mesmo problema de caracteres cortando.

**Comment by juliomar** [comment]
Boa tarde
conferiram a configuração de margens tanto no fortes quanto na impressora.
senão façam e se necessário reportem com um novo issue usando um exemplo para que possamos averiguar.
