### ISSUE TITLE
Exportação de relatórios no Formato Xls

### ISSUE THREAD

**Issue by faustoalves1968** [fortesinformatica/fortesreport-ce#68]
Boa tarde pessoal..
Estou com um problema na exportação de relatórios para XLS, pois os mesmos estão saindo desconfigurados. 
Tenho um cliente que não utiliza a suite OFFICE da MS, e sim suites Open, como  OpenOFFICE e LIBREOFFICE. existe alguma possibilidade de exportar relatórios para estas suites?

Em anexo estou enviando uma imagem ref. ao erro que é levantado quando tento abrir o relatório exportado no excell, uma imagem do relatório correto e uma imagem de como fica após o mesmo ser aberto no excell
Grato
![relatorioexportadoparaexcell](https://cloud.githubusercontent.com/assets/9949768/10792368/90b08fca-7d73-11e5-9902-5bec3c1fd155.png)
![erroexportarexcell](https://cloud.githubusercontent.com/assets/9949768/10792369/90b1dfb0-7d73-11e5-8572-b76a48ac156a.png)
![relatoriocorreto](https://cloud.githubusercontent.com/assets/9949768/10792370/90b50618-7d73-11e5-8618-6ae89beb2a12.png)

Fausto Alves
Franca SP

**Comment by marciomartins** [comment]
Fausto, bom dia.
Tem como você poderia enviar o arquivo gerado, e salvar o relatório no formato do próprio FortesResport e enviar junto para que eu possa analisar?

Atenciosamente,
Marcio Martins

**Comment by faustoalves1968** [comment]
Bom dia Márcio..
Conforme solicitado seque os arquivos nos dois formatos.
Grato
Fausto Alves
Franca-SP

Em 31 de outubro de 2015 10:04, Marcio Martins <notifications@github.com>
escreveu:

**Comment by marciomartins** [comment]
Acho que você esqueceu de anexar?
Qualquer coisa pode enviar direto para o meu email.
mm.marciomartins@gmail.com

Atenciosamente,
Márcio Martins

**Comment by faustoalves1968** [comment]
Márcio.. enviei para seu e-mail.. o github não aceita os anexos que você solicitou..
[]´s
Fausto  Alves
Franca-SP

**Comment by miaritecnologia** [comment]
Boa tarde ,
faustoalves1968 você conseguiu resolver o problema da exportação para excel, pois estou com o mesmo problema, e sempre estou vendo pelo SVN se teve alguma atualização do componente e nunca vem alteração.

att.
Ornei

**Comment by tonygyn** [comment]
Ola, 
Também estou com problema na exportação do relatório para excel. Após instalar a versão do Fortes Report CE ao exportar um relatório para excel o mesmo não exporta as informações contidas em RLDBText, apenas o que estão em RLLabel.
Alguém já possou por isto ?

**Comment by juliomar** [comment]
Testem usando a extensão xlsx
se persistir o problema abram novo issue com um exemplo
