### ISSUE TITLE
Contrato no Fortes

### ISSUE THREAD

**Issue by stclara** [fortesinformatica/fortesreport-ce#69]
Salve, pessoal. Não sei se aqui é o local, mas preciso de uma ajuda:
Quais componentes utilizo para gerar contratos no fortes justificado, com algumas palavras em negrito e com dados vindo de um BD?
Hoje utilizo o word e gero um pdf, mas queria utilizar apenas um gerador de relatórios.

[]´s

Stclara.

**Comment by marciomartins** [comment]
Bom dia, @stclara 
Utilize o TRLRichText .

Você pode consultar o site www.fortesreport.com.br ou no Yahoo Groups https://groups.yahoo.com/neo/groups/fortesreport.

Marcio Martins
