### ISSUE TITLE
TRLLabel não aceita cast no evento before print

### ISSUE THREAD

**Issue by faustoalves1968** [fortesinformatica/fortesreport-ce#70]
Bom dia..
Tenho em um form, vários relatórios e em ambos tenho um TRLLabel onde informo o período ao qual se refere o relatório..
Para não ter que codificar o beforeprint de cada TRLReport com a instrução abaixo:
  LblPeriodoPedAbe.Caption := 'Período: ' + FiltroSitPed.CdsFiltroPeriodo.Value;
  LblPeriodoPedBai.Caption := 'Período: ' + FiltroSitPed.CdsFiltroPeriodo.Value;
  LblPeriodoPedCan.Caption := 'Período: ' + FiltroSitPed.CdsFiltroPeriodo.Value;

Tentei codificar a propriedade BeforePrint do TRLLabel..
Onde tenho a seguinte construção:
LblPeriodoPedCanBeforePrint(Sender: TObject; var Text: String; var PrintIt: Boolean);
begin

end;

Tentei de duas formas...
1ª Text := 'Período: ' + FiltroSitPed.CdsFiltroPeriodo.Value; 
2ª TRLLabel(Sender).Caption := 'Período: ' + FiltroSitPed.CdsFiltroPeriodo.Value; 
 Em ambas as formas, nada é mostrado no TRLLabel, mesmo utilizando cast.

Fausto Alves
Franca - SP

**Comment by marciomartins** [comment]
Bom dia.
Primeiro o TRLLabel só funciona no TRLReport.
Segundo você deve usa o BeforePrinta da Band.

**Comment by faustoalves1968** [comment]
Boa tarde Márcio..
Teria como me enviar um exemplo?
Pois não entendi sua resposta..
Todos os meus TRLLabel estão em um TRLReport
Grato
Fausto Alves
Franca-SP

2015-11-10 9:27 GMT-02:00 Marcio Martins <notifications@github.com>:

**Comment by juliomar** [comment]
Boa tarde
segue o mesmo principio do beforeprint do label mas é da banda onde está o label.
caso não tenha conseguido abra um novo issue que ajudaremos
