### ISSUE TITLE
Erro instalação no Delphi 2005

### ISSUE THREAD

**Issue by ealemes** [fortesinformatica/fortesreport-ce#73]
Ola,

Quando vou instalar FortesReport recebo seguinte erro:

Caminho: F:\Delphi\FortesReport D2005\
Versão do delphi: Delphi 2005 (0)
Plataforma: Win32(0)
================================================================================
Setando parâmetros de plataforma...
Criando diretórios de bibliotecas...
Adicionando library paths...

Compiling package F:\Delphi\FortesReport D2005\Packages\frce.dpk
"C:\Program Files\Borland\BDS\3.0\bin\dcc32.exe" .......
Borland Delphi for Win32 compiler version 17.0
Copyright (c) 1983,2004 Borland Software Corporation
frce.dpk(41) Fatal: E2202 Required package 'vclimg' not found
Compilation failure

Grato

**Comment by marciomartins** [comment]
@ealemes Desculpe a demora, estive afastado por um tempo por excesso de trabalho.
Gostaria de saber se ainda está tendo problemas para instalar.

**Comment by ealemes** [comment]
Ola, só consegui instalar quando fiz mudanças no código, não sei melhor forma mas abaixo segue mudanças:
frce.dpk (apartir linha 40)
de   {$IFDEF VER180} vcljpg, {$ELSE}  // D2007    vclimg,   {$ENDIF}
para    {$IFDEF VER170} vcljpg,{$ELSE}    // D2005      {$IFDEF VER180} vcljpg, {$ELSE}  // D2007        vclimg,      {$ENDIF}    {$ENDIF}

RLXLSXFileFormat.pas (Linha 317)
de{$IfNDef DELPHI8_UP}
para{$IfNDef DELPHI2006_UP}
Date: Wed, 3 Feb 2016 10:40:39 -0800
