### ISSUE TITLE
Problemas com a impressão de Relatorio

### ISSUE THREAD

**Issue by Marina4852** [fortesinformatica/fortesreport-ce#75]
Boa noite,

Em um servidor com Windows Server 2012 há uma impressora HP LaserJet M1530 compartilhada de outra maquina da rede. Quando mando uma impressão do Fortes Reports em outras impressoras, tudo ocorre normalmente. Entretanto, ao enviar a esta impressora, aparece a mensagem:

Printer Driver host  for applications parou de funcionar
Assinatura do problema:
  Nome do Evento de Problema:   APPCRASH
  Nome do Aplicativo:   splwow64.exe
  Versão do Aplicativo:    6.2.9200.16384
  Carimbo de Data/Hora do Aplicativo:   50109d1a
  Nome do Módulo de Falhas:    hpc6r101.dll
  Versão do Módulo de Falhas: 0.3.1544.8561
  Carimbo de Data/Hora do Módulo de Falhas:    4c9bb483
  Código de Exceção: c0000005
  Deslocamento de Exceção:    000000000008f37a
  Versão do sistema operacional:   6.2.9200.2.0.0.272.7
  Identificação da Localidade:    1046
  Informações Adicionais 1:   b297
  Informações Adicionais 2:   b29728f665804635fc3e4debfd5a2dfb
  Informações Adicionais 3:   47c2
  Informações Adicionais 4:   47c2c93c05fc757b9e94f4cfa912df8f

Outros programas, a partir desse mesmo servidor, imprimem nesta impressora normalmente. Ou seja, o conflito parece ser gerado apenas com a impressão do Fortes Reports na impressora HP.
O que pode estar gerando este conflito?
![erro_impressao](https://cloud.githubusercontent.com/assets/16326741/11852654/5cacda52-a420-11e5-9b43-4977490a15f4.png)

**Comment by juliomar** [comment]
Boa tarde
pode ser driver da impressora.
chegou a atualizar o windows?
se continuar o erro favor abrir novo issue com mais detalhes.
