### ISSUE TITLE
Erro ao mostrar preview, utilizando o componente RLPreview

### ISSUE THREAD

**Issue by brsena** [fortesinformatica/fortesreport-ce#76]
Criei um novo form e coloquei os componentes: "RLPreview" e "RLPreviewSetup"

Feito isso, criei esse form e atribui o "RLReport", da seguinte forma:
RLReport.Preview(FormPreviewFortesReport.RLPreview);

Quando executo dá a seguinte mensagem de erro: "Erro durante a preparação do relatório"
![captura de tela 2015-12-17 as 17 11 44](https://cloud.githubusercontent.com/assets/5443823/11880985/cc495f3a-a4e2-11e5-9d83-70e9f6d6fbe4.png)

**Comment by juliomar** [comment]
Resolveu seu problema?
caso negativo abra um novo issue e anexe um projeto de exemplo para que possamos ajudar
