### ISSUE TITLE
Erro ao gerar relatório com imagem no Delphi 2009

### ISSUE THREAD

**Issue by awendisch** [fortesinformatica/fortesreport-ce#77]
Olá,
Estou usando o FortesReportCE em conjunto com o componente ACBrNFe + ACBrNFeDANFE_RL da ACBr, com a IDE Delphi 2009, acontece que sempre quando vou imprimir com o Fortes, ele me apresenta a seguinte mensagem: "Out of memory". 
Porém foi constatado que o componente da ACBr + FortesReportCE funciona perfeitamente em outras versões do delphi. o que me faz acreditar ser um bug do FortesReportCE com o Delphi 2009.

Eu tentei debugar e acredito que o problema deva estar na unit RLMetaVCL.pas, porém é apenas um palpite.

Segue a imagem do erro:

![erro_danfe_fortesce](https://cloud.githubusercontent.com/assets/16394288/11946069/df18142c-a83d-11e5-8df5-80a010b2ae0f.png)

**Comment by dopidaniel** [comment]
Tentou usar o FastMM ?
https://sourceforge.net/projects/fastmm/

**Comment by juliomar** [comment]
Boa tarde
fechando issue caso o problema persista abra um novo com um projeto de exemplo
