### ISSUE TITLE
Erro na Compilação no Lazarus 1.4.0 e 1.4.4 Linux

### ISSUE THREAD

**Issue by ManoelPjr** [fortesinformatica/fortesreport-ce#82]
Lazarus 1.4.0 e 1.4.4 
Ubuntu 15.10 - 64 bits 
Ao tentar compilar resulta na seguinte mensagem de erro [RLXLSXFileFormat.pas(497,3) Error: Argument can't be assigned to] como mostrado nas Imagens abaixo, Alguém poderia me ajudar?:
![captura de tela de 2016-01-06 14-53-27](https://cloud.githubusercontent.com/assets/9893150/12149973/8527e9ca-b485-11e5-8ad0-9b5e97e4e780.png)
![captura de tela de 2016-01-06 14-53-52](https://cloud.githubusercontent.com/assets/9893150/12149974/85360ac8-b485-11e5-83b1-d26d1bdfb982.png)
![captura de tela de 2016-01-06 14-54-19](https://cloud.githubusercontent.com/assets/9893150/12149975/853d7a92-b485-11e5-97ae-f525471f1976.png)

**Comment by andromeda66** [comment]
The same issue here, fpc 3.0.0 lazarus 1.4.4 svn 51570 built with fpcup on linux Mint.

**Comment by williamcrocha** [comment]
Mesmo problema no Windos 7 64, FPC 3.0.0, Lazarus 1.6 SVN 51630

**Comment by welkson** [comment]
Mesmo problema no Windows 7 64, FPC 2.6.4, Lazarus 1.4.2  SVN 49524

**Comment by zoran-vucenovic** [comment]
Please see my comment here:
https://github.com/fortesinformatica/fortesreport-ce/issues/93#issuecomment-199384799

**Comment by juliomar** [comment]
git fetch all nos fontes e refazer a instalação
se o problema persistir favor criar novo issue com maiores detalhes.
