### ISSUE TITLE
Suporte a porta USB Filtro RLDraftFilter

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#83]
Olá Pessoal,

Teria a possibilidade de implementar suporte a porta USB Filtro RLDraftFilter?
Porque o mesmo só suporta porta Paralela LPT. Hoje a maiorias das impressoras já vem de fabrica  com porta USB.
Me parece que dar para imprimi com FortesReport usando USB,mais tem que fazer Gabiarras, fazer mapeamento. Estou tentando a dias e ate agora não consegui imprimir.

Obrigado, pela atenção.
## 

Edson

**Comment by juliomar** [comment]
Está em nossos planos. mas falta tempo
caso queira contribuir faça um fork do projeto implemente e envie um pull request
