### ISSUE TITLE
Mascara não se aplica.

### ISSUE THREAD

**Issue by jefersonrodrigostefani** [fortesinformatica/fortesreport-ce#84]
Olá!

Estou fazendo alguns testes com o fortes, e notei que a propriedade DisplayMask não está apresentando a formatação conforme o esperado. Analisando um pouco do código, pude encontrar dentro da rotina ApplyMask [TRLCustomDBText] duas situações:

1- Caso a propriedade EditFormat estiver preenchida, ele assumirá a formatação do mesmo.
2- Caso a propriedade DisplayMask estiver preenchida, e o caso acima não seja satisfeito, essa será a formatação assumida pelo componente.

Fiz um teste com as duas situações, e em ambas não obtive sucesso. Estou procurando entender melhor a rotina para poder aplicar uma correção [caso de fato seja necessário].

**Comment by reginaldoallpharma** [comment]
Olá amigo, já encontrou uma solução para esse problema? houve alguma atualização a respeito desse problema?

**Comment by juliomar** [comment]
Conseguiram resolver?
caso negativo favor anexar um projeto de exemplo com o erro em um novo issue
