### ISSUE TITLE
Girar 180 graus

### ISSUE THREAD

**Issue by aslsoftware** [fortesinformatica/fortesreport-ce#85]
Quando mando imprimir na impressora Zebra, preciso girar em 180 graus para que seja impresso corretamente, porém na impressora está habilitada para girar em 180 graus e quando mando imprimir não gira, já fiz testes na impressora laser hp e também não girou. Alguém sabe o que pode ser??? Obrigado

**Comment by marciomartins** [comment]
Você já tentou utilizar o relatório em paisagem?
O FortesReport não se comunica direto com a impressora, ele envia para o SO gerenciar.
Dúvidas sobre o uso do FortesReport, favor utilizar o Grupo https://br.groups.yahoo.com/neo/search?query=fortesreport
