### ISSUE TITLE
Como faço para ocultar a barra de progresso do Imprimir e Salvar?

### ISSUE THREAD

**Issue by dominioararangua** [fortesinformatica/fortesreport-ce#86]
Boa tarde,

Como faço para ocultar a barra de progresso do Imprimir e Salvar?

Grato

Rodrigo

**Comment by marciomartins** [comment]
@dominioararangua Caro, bom dia.
Este espaço é para sugerir melhorias ou correções.
Favor utilizar o grupo https://groups.yahoo.com/neo/groups/fortesreport/info

**Comment by dominioararangua** [comment]
Bom marciomartins, exatamente, showprogress não esta funcionando. Pode colocar true ou false, tanto faz, continua aparecendo.
Para não ficar aparecendo tive que remover diretamente no codigo fonte.

Grato

**Comment by marciomartins** [comment]
Bom dia @dominioararangua!
Você está com os fontes mais recentes?
Acabei de fazer um teste e funciona perfeitamente.
Sugestão: Remover completamente a versão que está instalado e instalar a nova.

**Comment by dominioararangua** [comment]
Ok, vou tentar, obrigado!
