### ISSUE TITLE
  Erro ao clicar em enviar no fortes CE

### ISSUE THREAD

**Issue by ClaudioJose** [fortesinformatica/fortesreport-ce#87]
Ola pessoal, após ter migrado para o FORTES-CE não consigo mais enviar email
clicando no botão ENVIAR, o sistema até gera e abre o Outlook, porem se eu tentar
abrir o arquivo em PDF ele me da um erro dizendo que não pode abrir este arquivo porque não tem 
nenhuma página. 
Dai mudei o 0(zero) na função abaixo e coloquei 1(um) dai gera, mas dai não me mostra todas as páginas.    

função->    filterpages(pages,ftr,0,999,'',0);

O que poderia estar acontecendo?

Grato

Cláudio

**Comment by juliomar** [comment]
Boa tarde
foram feito alterações favor testar
se o problema persistir abrir novo issue com maiores detalhes.
