### ISSUE TITLE
Nome do arquivo pdf salvo aparece com caracteres estranhos

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#88]
Olá,

Ao salvar um arquivo de relatório gerado pelo fortes, o o nome do arquivo pdf salvo aparece com caracteres estranhos. Conforme anexo.
![fortes_sem titulo](https://cloud.githubusercontent.com/assets/2966579/12870456/da408be6-cd2c-11e5-97f0-cb7ffbcd8114.png)

**Comment by dopidaniel** [comment]
Apliquei modificações recentes, que podem sanar o problema... favor atualizar e testar..

**Comment by elidorio** [comment]
Boa tarde Daniel,

Sanado esse problema também.
