### ISSUE TITLE
Instalar no Delphi 2006

### ISSUE THREAD

**Issue by sisnoturno** [fortesinformatica/fortesreport-ce#9]
Boa noite,

Amigos, preciso muito instalar o ForstReport mais atual no Delphi 2006 Turbo, já tentei de tudo é nada, por favor, se alguém pode me ajudar... Ficarei Grato.

Glênio Duarte Moura
Duarte@noturnosoftwares.com.br

**Comment by marciomartins** [comment]
Desculpe a demora, se ainda estiver com problemas favor reabrir o chamado ou me contactar por e-mail.

**Comment by Elias-Diagnosys** [comment]
Glênio, bom dia.
Acaso você consegui resolver está questão ?

**Comment by sisnoturno** [comment]
Não, não tive nenhum sucesso, então migrei para o XE5. nele conseguir resolver o meu problema.

**Comment by Elias-Diagnosys** [comment]
Entendi, de qualquer forma, obrigado.
