### ISSUE TITLE
Caracteres Estranho

### ISSUE THREAD

**Issue by adaltosilvahdacom** [fortesinformatica/fortesreport-ce#91]
Ao abrir a janela de dialogo para salvar o relatório em PDF e clicando com o botão direito do mouse para se criar uma pasta, todo o conteúdo do menu esta com caracteres chineses.

Obrigado

**Comment by dopidaniel** [comment]
Apliquei modificações recentes, que podem sanar o problema... favor atualizar e testar..

**Comment by juliomar** [comment]
caso não tenha resolvido favor abrir novo issue com maiores detalhes
