### ISSUE TITLE
Fortes Report com último Lazarus 1.6 Fpc 3.0 

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#92]
Olá Pessoal,

Fui fazer uns teste com o Fortes Report com último Lazarus 1.6 Fpc 3.0 
![pr-visualiza](https://cloud.githubusercontent.com/assets/2966579/13164000/1140e2e2-d699-11e5-8f72-078ad5b14809.png)
e o fortes esta apresentado problemas com a acentuação no Preview.
Conforme anexo.

**Comment by dopidaniel** [comment]
Apliquei modificações recentes, que podem sanar o problema... favor atualizar e testar..

**Comment by elidorio** [comment]
Acabei de testar e esta ok.
