### ISSUE TITLE
Erro A.V. na incialização do fortes

### ISSUE THREAD

**Issue by IaniceLanziloti** [fortesinformatica/fortesreport-ce#95]
Boa tarde, 
Nosso sistema utiliza as bibliotecas em Runtime, e estamos tendo problema na inicialização do fortes.
O erro ocorre na unit RLReg e função AddSplash:
`procedure AddSplash;
  var
      bmp: TBitmap;
  begin
     bmp := TBitmap.Create;
     bmp.LoadFromResourceName(HInstance, 'FRCE');
      SplashScreenServices.AddPluginBitmap(cRLSobreDialogoTitulo,bmp.Handle,false,cRLSobreLicencaStatus,'');
    bmp.Free;
end;`

especificamente na linha:
`SplashScreenServices.AddPluginBitmap(cRLSobreDialogoTitulo,bmp.Handle,false,cRLSobreLicencaStatus,'');`

chamanda na incialização do componente:
`
{$IFDEF DELPHI2007_UP}
initialization
  AddSplash;
  RegisterAboutBox;

finalization
  UnregisterAboutBox;
{$ENDIF}`

Estamos utilizando o Delphi xe6 na compilação do nosso projeto, lembrando que se removermos a propriedade RunTime tudo passa a funcionar corretamente.

Obrigado.

**Comment by juliomar** [comment]
Pergunta: você usa também em sua aplicação o Jedi ou Fast Report? ou até mesmo a DevExpress?

**Comment by IaniceLanziloti** [comment]
Bom dia,

Atualmente não estou usando Jedi, Fast e nem DevExpress.

Consegui resolver o problema colocando as Units do fortes no USES do formulário principal da aplicação.
Assim o sistema carrega e executa de forma correta as procedures de incialização.
Não acredito que seja a maneira correta, pois seria interessante para nós colocarmos somente no USES dos formulários que usam relatórios pelo fortes.

**Comment by Walfridocesar** [comment]
Estranhamente ocorre muitos A.V. no meu projeto simplistemente ao passar o mouse sobre os botões do gerador... Como resolver?


![errofortesreport](https://cloud.githubusercontent.com/assets/315829/18456101/c33c86b2-7924-11e6-8a02-5d52adc8fbc3.jpg)

**Comment by juliomar** [comment]
Conseguiu resolver seu problema?
atualizou o git e reinstalou o componente?
se persistir favor abrir novo issue
