### ISSUE TITLE
Comportamento na quebra de linha do TRLDBMemo

### ISSUE THREAD

**Issue by Paulo-Amorim** [fortesinformatica/fortesreport-ce#96]
Bom dia.

Estou com um problema de quebrar a linha com o componente TRLDBMemo quando o valor ultrapassa o espaço delimitado. 

Essa situação ocorre quando o valor não tem nenhum caractere de espaço. Quando possui o caractere de espaço, ele quebra corretamente.

Exemplo: 

O valor no componente é A154AS54EREREF454ASDDASDEADAASDSA454546ADSADSA4564ASDDER4AD.

O espaço reservado para esse valor cabe por linha 10 caracteres. Então ele deveria permanecer assim:

Linha 1 = A154AS54ER
Linha 2 = EREF454ASD
Linha 3 = DASDEADAAS
Linha 4 = DSA454546A
Linha 5 = DSADSA4564
Linha 6 = ASDDER4ADS

Porém o resultado encontrado é:

Linha 1 = A154AS54ER

Ele despreza o restante do texto.

Gostaria de saber se esse é o comportamento correto deste componente.

Entendo que quebrar só quando existe espaços é uma opção inteligente para não partir palavras incorretamente, porém gostaria de saber se existe alguma propriedade que quebra a linha independente de possuir ou não espaços.

Se precisar de mais alguma informação ou arquivo é só falar.

Estava tratando este comportamento também com o pessoal do ACBr.

http://www.projetoacbr.com.br/forum/topic/28420-campo-cprod-cortando-no-acbrnfedanferlfortes-report/

Muito obrigado.

**Comment by juliomar** [comment]
Foi resolvido seu problema?
caso negativo abra um novo issue com maiores detalhes para poder ajudar
