### ISSUE TITLE
Lazarus 1.7 fpc 3.1.1

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#98]
Novo erro:

Lazarus 1.7 fpc 3.1.1

RLPreviewForm.pas(387,10) Error: Identifier not found "FileExistsUTF8"

**Comment by giquieu** [comment]
No FPC 3.+ deixaram FileExistsUTF8 como deprecated.
Veja o que esta comentado em FileUtil.pas:

>  // AnsiToUTF8 and UTF8ToAnsi need a widestring manager under Linux, BSD, MacOSX
> // but normally these OS use UTF-8 as system encoding so the widestringmanager
> // is not needed.
> {$IFDEF EnableWrapperFunctions}  

Pra corrigir esse problema vc tem que subistituir no uses do _RLPreviewForm.pas_ o _FileUtil.pas_ pelo **LazFileUtils.pas**

Depois posso fazer um pull-request.

**Comment by elidorio** [comment]
Vou testar, por favor faz um pull-request.
Obrigado;

**Comment by elidorio** [comment]
Olá giquieu,

Aproveitando o gancho vc já teve esse problema que postei na issue abaixo?
https://github.com/fortesinformatica/fortesreport-ce/issues/94

**Comment by giquieu** [comment]
alidorio, ainda não tive esse problema não...  Se estiver afim podemos verificar juntos.

**Comment by elidorio** [comment]
Vamos sim, já vasculhei e não consegui resolver esse BO. Até postei um exemplo de código exemplificando o problema, mais não conseguir achar a solução, acho que esse erro só esta no Fortes com Lazarus.

**Comment by elidorio** [comment]
Fiz a substituição conforme solicitado e não deu certo. 

RLUtils.pas(284,18) Error: Identifier not found "SysToUTF8"

**Comment by elidorio** [comment]
Olá Guioque,

Baixei uma versão mais recente do Lazarus 1.7 e agora deu certo.
Por favor, faz um pull-request.

Obrigado.

**Comment by giquieu** [comment]
Com qual FPC vc tá?

**Comment by elidorio** [comment]
fpc 3.0

**Comment by juliomar** [comment]
Boa tarde
acredito que já esteja resolvido pois foram subido mudanças no git .
caso negativo favor criar novo issue com maiores detalhes.
