### ISSUE TITLE
erro ao instalar no delphi2005

### ISSUE THREAD

**Issue by jefkm** [fortesinformatica/fortesreport-ce#99]
Caminho: C:\fortesreport\trunk\
Versão do delphi: Delphi 2005 (0)
# Plataforma: Win32(0)

Setando parâmetros de plataforma...
Criando diretórios de bibliotecas...
Adicionando library paths...

Compiling package C:\fortesreport\trunk\Packages\frce.dpk
"C:\Program Files (x86)\Borland\BDS\3.0\bin\dcc32.exe" "C:\fortesreport\trunk\Packages\frce.dpk" -B -$O- -$W+ -$Y- -M -Q -H- -W- -DRELEASE -U"C:\Program Files (x86)\Borland\BDS\3.0\lib" -U"C:\LMD70SE\LIB\D9;$(BDS)\LIB;C:\PROGRAM FILES (X86)\BORLAND\BDS\3.0\IMPORTS;$(BDS)\LIB\INDY9;C:\Program Files (x86)\Borland\BDS\3.0\RaveReports\Lib;C:\Program Files (x86)\Raize\RC3\Lib9;C:\Program Files (x86)\Devart\dbExpress\InterBase\Lib\Delphi9;C:\Users\Jeferson\Desktop\componentes\fortesreport-ce-master\Binary\LibD9;C:\fortesreport\Binary\LibD9;C:\ACBR\Fontes\ACBrBoleto;C:\ACBR\Fontes\ACBrBoleto\FC;C:\ACBR\Fontes\ACBrBoleto\FC\Fast;C:\ACBR\Fontes\ACBrBoleto\FC\Fortes;C:\ACBR\Fontes\ACBrBoleto\Logos;C:\ACBR\Fontes\ACBrBoleto\Logos\Colorido;C:\ACBR\Fontes\ACBrBoleto\Logos\PretoBranco;C:\ACBR\Fontes\ACBrCapicom;C:\ACBR\Fontes\ACBrComum;C:\ACBR\Fontes\ACBrDFe;C:\ACBR\Fontes\ACBrDFe\ACBrBlocoX;C:\ACBR\Fontes\ACBrDFe\ACBrCTe;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\PCNCTe;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\PCNGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\PCNMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\ACBrECFVirtualNFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\EscPos;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\PCNNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\PCNNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\Provedores;C:\ACBR\Fontes\ACBrDiversos;C:\ACBR\Fontes\ACBrDiversos\ACBrFalaWaves;C:\ACBR\Fontes\ACBrOpenSSL;C:\ACBR\Fontes\ACBrSAT;C:\ACBR\Fontes\ACBrSAT\ACBrECFVirtualSAT;C:\ACBR\Fontes\ACBrSAT\Extrato;C:\ACBR\Fontes\ACBrSAT\Extrato\EscPos;C:\ACBR\Fontes\ACBrSAT\Extrato\Fortes;C:\ACBR\Fontes\ACBrSAT\PCNSAT;C:\ACBR\Fontes\ACBrSerial;C:\ACBR\Fontes\ACBrTCP;C:\ACBR\Fontes\ACBrTEFD;C:\ACBR\Fontes\ACBrTXT;C:\ACBR\Fontes\ACBrTXT\ACBrConvenio115;C:\ACBR\Fontes\ACBrTXT\ACBrDeSTDA;C:\ACBR\Fontes\ACBrTXT\ACBrLFD;C:\ACBR\Fontes\ACBrTXT\ACBrPAF;C:\ACBR\Fontes\ACBrTXT\ACBrPonto;C:\ACBR\Fontes\ACBrTXT\ACBrSEF2;C:\ACBR\Fontes\ACBrTXT\ACBrSintegra;C:\ACBR\Fontes\ACBrTXT\ACBrSPED;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDContabil;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDECF;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFCont;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFiscal;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofins;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofinsImportar;C:\ACBR\Fontes\ACBrTXT\SintegraSultan;C:\ACBR\Fontes\Imagens;C:\ACBR\Fontes\PCNComum;C:\ACBR\Fontes\Terceiros;C:\ACBR\Fontes\Terceiros\AJBarcode;C:\ACBR\Fontes\Terceiros\DelphiZXingQRCode;C:\ACBR\Fontes\Terceiros\JediWin32API;C:\ACBR\Fontes\Terceiros\synalist;C:\ACBR\Fontes\Terceiros\TGif;C:\ACBR\Fontes\Terceiros\ZLibExGZ;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win32;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win64;C:\ACBR\Fontes\Terceiros\ZLibExGZ\zlib;C:\ACBR\Lib\Delphi\LibD9;C:\fortesreport\trunk\Binary\LibD9" -U"C:\fortesreport\trunk\Binary\LibD9" -I"C:\LMD70SE\LIB\D9;$(BDS)\LIB;C:\PROGRAM FILES (X86)\BORLAND\BDS\3.0\IMPORTS;$(BDS)\LIB\INDY9;C:\Program Files (x86)\Borland\BDS\3.0\RaveReports\Lib;C:\Program Files (x86)\Raize\RC3\Lib9;C:\Program Files (x86)\Devart\dbExpress\InterBase\Lib\Delphi9;C:\Users\Jeferson\Desktop\componentes\fortesreport-ce-master\Binary\LibD9;C:\fortesreport\Binary\LibD9;C:\ACBR\Fontes\ACBrBoleto;C:\ACBR\Fontes\ACBrBoleto\FC;C:\ACBR\Fontes\ACBrBoleto\FC\Fast;C:\ACBR\Fontes\ACBrBoleto\FC\Fortes;C:\ACBR\Fontes\ACBrBoleto\Logos;C:\ACBR\Fontes\ACBrBoleto\Logos\Colorido;C:\ACBR\Fontes\ACBrBoleto\Logos\PretoBranco;C:\ACBR\Fontes\ACBrCapicom;C:\ACBR\Fontes\ACBrComum;C:\ACBR\Fontes\ACBrDFe;C:\ACBR\Fontes\ACBrDFe\ACBrBlocoX;C:\ACBR\Fontes\ACBrDFe\ACBrCTe;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\PCNCTe;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\PCNGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\PCNMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\ACBrECFVirtualNFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\EscPos;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\PCNNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\PCNNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\Provedores;C:\ACBR\Fontes\ACBrDiversos;C:\ACBR\Fontes\ACBrDiversos\ACBrFalaWaves;C:\ACBR\Fontes\ACBrOpenSSL;C:\ACBR\Fontes\ACBrSAT;C:\ACBR\Fontes\ACBrSAT\ACBrECFVirtualSAT;C:\ACBR\Fontes\ACBrSAT\Extrato;C:\ACBR\Fontes\ACBrSAT\Extrato\EscPos;C:\ACBR\Fontes\ACBrSAT\Extrato\Fortes;C:\ACBR\Fontes\ACBrSAT\PCNSAT;C:\ACBR\Fontes\ACBrSerial;C:\ACBR\Fontes\ACBrTCP;C:\ACBR\Fontes\ACBrTEFD;C:\ACBR\Fontes\ACBrTXT;C:\ACBR\Fontes\ACBrTXT\ACBrConvenio115;C:\ACBR\Fontes\ACBrTXT\ACBrDeSTDA;C:\ACBR\Fontes\ACBrTXT\ACBrLFD;C:\ACBR\Fontes\ACBrTXT\ACBrPAF;C:\ACBR\Fontes\ACBrTXT\ACBrPonto;C:\ACBR\Fontes\ACBrTXT\ACBrSEF2;C:\ACBR\Fontes\ACBrTXT\ACBrSintegra;C:\ACBR\Fontes\ACBrTXT\ACBrSPED;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDContabil;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDECF;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFCont;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFiscal;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofins;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofinsImportar;C:\ACBR\Fontes\ACBrTXT\SintegraSultan;C:\ACBR\Fontes\Imagens;C:\ACBR\Fontes\PCNComum;C:\ACBR\Fontes\Terceiros;C:\ACBR\Fontes\Terceiros\AJBarcode;C:\ACBR\Fontes\Terceiros\DelphiZXingQRCode;C:\ACBR\Fontes\Terceiros\JediWin32API;C:\ACBR\Fontes\Terceiros\synalist;C:\ACBR\Fontes\Terceiros\TGif;C:\ACBR\Fontes\Terceiros\ZLibExGZ;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win32;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win64;C:\ACBR\Fontes\Terceiros\ZLibExGZ\zlib;C:\ACBR\Lib\Delphi\LibD9;C:\fortesreport\trunk\Binary\LibD9" -R"C:\LMD70SE\LIB\D9;$(BDS)\LIB;C:\PROGRAM FILES (X86)\BORLAND\BDS\3.0\IMPORTS;$(BDS)\LIB\INDY9;C:\Program Files (x86)\Borland\BDS\3.0\RaveReports\Lib;C:\Program Files (x86)\Raize\RC3\Lib9;C:\Program Files (x86)\Devart\dbExpress\InterBase\Lib\Delphi9;C:\Users\Jeferson\Desktop\componentes\fortesreport-ce-master\Binary\LibD9;C:\fortesreport\Binary\LibD9;C:\ACBR\Fontes\ACBrBoleto;C:\ACBR\Fontes\ACBrBoleto\FC;C:\ACBR\Fontes\ACBrBoleto\FC\Fast;C:\ACBR\Fontes\ACBrBoleto\FC\Fortes;C:\ACBR\Fontes\ACBrBoleto\Logos;C:\ACBR\Fontes\ACBrBoleto\Logos\Colorido;C:\ACBR\Fontes\ACBrBoleto\Logos\PretoBranco;C:\ACBR\Fontes\ACBrCapicom;C:\ACBR\Fontes\ACBrComum;C:\ACBR\Fontes\ACBrDFe;C:\ACBR\Fontes\ACBrDFe\ACBrBlocoX;C:\ACBR\Fontes\ACBrDFe\ACBrCTe;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\DACTE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrCTe\PCNCTe;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\GNRE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrGNRE\PCNGNRE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\DAMDFE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrMDFe\PCNMDFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\ACBrECFVirtualNFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\EscPos;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFCe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\DANFE\NFe\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFe\PCNNFe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fast;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\DANFSE\Fortes;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\PCNNFSe;C:\ACBR\Fontes\ACBrDFe\ACBrNFSe\Provedores;C:\ACBR\Fontes\ACBrDiversos;C:\ACBR\Fontes\ACBrDiversos\ACBrFalaWaves;C:\ACBR\Fontes\ACBrOpenSSL;C:\ACBR\Fontes\ACBrSAT;C:\ACBR\Fontes\ACBrSAT\ACBrECFVirtualSAT;C:\ACBR\Fontes\ACBrSAT\Extrato;C:\ACBR\Fontes\ACBrSAT\Extrato\EscPos;C:\ACBR\Fontes\ACBrSAT\Extrato\Fortes;C:\ACBR\Fontes\ACBrSAT\PCNSAT;C:\ACBR\Fontes\ACBrSerial;C:\ACBR\Fontes\ACBrTCP;C:\ACBR\Fontes\ACBrTEFD;C:\ACBR\Fontes\ACBrTXT;C:\ACBR\Fontes\ACBrTXT\ACBrConvenio115;C:\ACBR\Fontes\ACBrTXT\ACBrDeSTDA;C:\ACBR\Fontes\ACBrTXT\ACBrLFD;C:\ACBR\Fontes\ACBrTXT\ACBrPAF;C:\ACBR\Fontes\ACBrTXT\ACBrPonto;C:\ACBR\Fontes\ACBrTXT\ACBrSEF2;C:\ACBR\Fontes\ACBrTXT\ACBrSintegra;C:\ACBR\Fontes\ACBrTXT\ACBrSPED;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDContabil;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDECF;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFCont;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDFiscal;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofins;C:\ACBR\Fontes\ACBrTXT\ACBrSPED\ACBrSPEDPisCofinsImportar;C:\ACBR\Fontes\ACBrTXT\SintegraSultan;C:\ACBR\Fontes\Imagens;C:\ACBR\Fontes\PCNComum;C:\ACBR\Fontes\Terceiros;C:\ACBR\Fontes\Terceiros\AJBarcode;C:\ACBR\Fontes\Terceiros\DelphiZXingQRCode;C:\ACBR\Fontes\Terceiros\JediWin32API;C:\ACBR\Fontes\Terceiros\synalist;C:\ACBR\Fontes\Terceiros\TGif;C:\ACBR\Fontes\Terceiros\ZLibExGZ;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win32;C:\ACBR\Fontes\Terceiros\ZLibExGZ\win64;C:\ACBR\Fontes\Terceiros\ZLibExGZ\zlib;C:\ACBR\Lib\Delphi\LibD9;C:\fortesreport\trunk\Binary\LibD9" -N0"C:\fortesreport\trunk\Binary\LibD9" -LE"C:\fortesreport\trunk\Binary\LibD9" -LN"C:\fortesreport\trunk\Binary\LibD9"
Borland Delphi for Win32 compiler version 17.0
Copyright (c) 1983,2004 Borland Software Corporation
frce.dpk(41) Fatal: E2202 Required package 'vclimg' not found
Compilation failure

**Comment by StalinBR** [comment]
https://github.com/fortesinformatica/fortesreport-ce/issues/73

**Comment by juliomar** [comment]
Continua a ter problemas? 
se sim abra novo issue com maiores detalhes mas parece que o #73 resolveu
